### ISSUE TITLE
Only mainnet xpubs can be loaded from Ledger Nano S

### ISSUE THREAD

**Issue by alecalve** [wizardsardine/liana#1002]
I’m using a Ledger Nano S (2.1.0), Bitcoin App 2.1.3

Liana is 4.0-1 running on Linux Mint.

When creating a wallet, using the HW wallet works fine for Bitcoin Mainnet but adding a HW signer for Testnet/Signet/Regtest fails with this modal:
![image](https://github.com/wizardsardine/liana/assets/3832610/91495160-ddfc-492b-8291-c4dfeab84956)

Interacting with the device using `hwi` works fine:

```
$ hwi --chain=regtest --fingerprint=<redacted> getmasterxpub
{"xpub": "<redacted>"}
```

The device asks for user confirmation as the generated path looks weird to it though.

**Comment by alecalve** [comment]
I tried re-installing the Bitcoin app on the ledger as well as rebooting the computer Liana is running on, to no avail. It’s happening with two different Ledger Nano S.

**Comment by edouardparis** [comment]
Hello @alecalve, Ledger has two different app, one for mainnet and one for testnet. You have to install the second one. I agree that the error message could be more helpful.

**Comment by alecalve** [comment]
Ahh, thanks for the info. Indeed, the error message could be clearer.

**Comment by darosior** [comment]
Also, love the detailed report in the OP.
