### ISSUE TITLE
Unable to start `lianad` with sample configuration file

### ISSUE THREAD

**Issue by torkelrogstad** [wizardsardine/liana#1012]
I'm unable to start `lianad`. I've compiled the binaries from master (1310896bf62290bb9d9da47968ac07854053b442). 

```bash
$ ./target/release/lianad --conf $PWD/config.toml
Error parsing config: Failed to read configuration file: Parsing configuration file: Error parsing 'wsh(or_d(pk([92162c45]tpubD6NzVbkrYhZ4WzTf9SsD6h7AH7oQEippXK2KP8qvhMMqFoNeN5YFVi7vRyeRSDGtgd2bPyMxUNmHui8t5yCgszxPPxMafu1VVzDpg9aruYW/<0;1>/*),and_v(v:pkh(tpubD6NzVbkrYhZ4Wdgu2yfdmrce5g4fiH1ZLmKhewsnNKupbi4sxjH1ZVAorkBLWSkhsjhg8kiq8C4BrBjMy3SjAKDyDdbuvUa1ToAHbiR98js/<0;1>/*),older(2))))#uact7s3g': Invalid key 'tpubD6NzVbkrYhZ4Wdgu2yfdmrce5g4fiH1ZLmKhewsnNKupbi4sxjH1ZVAorkBLWSkhsjhg8kiq8C4BrBjMy3SjAKDyDdbuvUa1ToAHbiR98js/<0;1>/*'. Need a wildcard ('ranged') xpub with an origin and a multipath for (and only for) deriving change addresses. That is, an xpub of the form '[aaff0099]xpub.../<0;1>/*'. for key `main_descriptor` at line 3 column 1
```

I've created a TOML config file, based on the [sample config file](https://github.com/wizardsardine/liana/blob/1310896bf62290bb9d9da47968ac07854053b442/contrib/lianad_config_example.toml) found in this repo.

```bash
$ cat config.toml
main_descriptor = "wsh(or_d(pk([92162c45]tpubD6NzVbkrYhZ4WzTf9SsD6h7AH7oQEippXK2KP8qvhMMqFoNeN5YFVi7vRyeRSDGtgd2bPyMxUNmHui8t5yCgszxPPxMafu1VVzDpg9aruYW/<0;1>/*),and_v(v:pkh(tpubD6NzVbkrYhZ4Wdgu2yfdmrce5g4fiH1ZLmKhewsnNKupbi4sxjH1ZVAorkBLWSkhsjhg8kiq8C4BrBjMy3SjAKDyDdbuvUa1ToAHbiR98js/<0;1>/*),older(2))))#uact7s3g"

[bitcoin_config]
network = "signet"
```

Based on some basic perusing of the repo, I can't seem to find any documentation on how to generate a valid `main_descriptor`. Would be great on some pointers on this!

**Comment by pythcoiner** [comment]
here find a valid one:
```
"wsh(or_d(pk(
[15098463/48'/1'/0'/2']tpubDEG5XYC228KA3YnUk7swJYYwoc7Ntb4SknEUPLePbVUdpDpNHvq2UQXAMwnMbQvyX2upzcahGfJGMg7mbuudKzbCJBB5gujHkjN4X1ikC31/<0;1>/*
),and_v
(v:pkh(
[15098463/48'/1'/0'/2']tpubDEG5XYC228KA3YnUk7swJYYwoc7Ntb4SknEUPLePbVUdpDpNHvq2UQXAMwnMbQvyX2upzcahGfJGMg7mbuudKzbCJBB5gujHkjN4X1ikC31/<2;3>/*
),older(65535))))#xp6sf7zq"
````

in comparison w/ yours:

``` 
"wsh(or_d(pk(
[92162c45]tpubD6NzVbkrYhZ4WzTf9SsD6h7AH7oQEippXK2KP8qvhMMqFoNeN5YFVi7vRyeRSDGtgd2bPyMxUNmHui8t5yCgszxPPxMafu1VVzDpg9aruYW/<0;1>/*
),and_v(
v:pkh(
[92162c45]tpubD6NzVbkrYhZ4WzTf9SsD6h7AH7oQEippXK2KP8qvhMMqFoNeN5YFVi7vRyeRSDGtgd2bPyMxUNmHui8t5a1ToAHbiR98js/<0;1>/*
),older(2))))#uact7s3g"
```

few points:

- your first key is missing the derivation path:

[92162c45`<derivation_path>`]tpubD6NzVbkrYhZ4WzTf9SsD6h7AH7oQEippXK2KP8qvhMMqFoNeN5YFVi7vRyeRSDGtgd2bPyMxUNmHui8t5

- your second key is missing both fingerprint & derivation path:

`[<fingerprint><derivation_path>]`[92162c45]tpubD6NzVbkrYhZ4WzTf9SsD6h7AH7oQEippXK2KP8qvhMMqFoNeN5YFVi7vRyeRSDGtgd2bPyMxUNmHui8t5

**Comment by torkelrogstad** [comment]
Thanks. The value I used for my `main_descriptor` was taken from the sample config file - probably a good idea to update that, then?

**Comment by pythcoiner** [comment]
good catch! Thanks!
you can also generate a wallet w/ Liana GUI, then use it w/ daemon if that fit your needs!

**Comment by torkelrogstad** [comment]
I'm looking into multiple different ways of programmatically handling a large number of multisig vaults using pre-existing coordination software, and `lianad` is on my shortlist of hopeful candidates!

**Comment by darosior** [comment]
Nice. Feel free to join our [Telegram](https://t.me/lianabitcoin) group if you've got questions for setting this up. I also just started a [Discord server](https://discord.gg/6NYuKKuV) today with the intent of having technical discussions there (still not entirely public but probably preferable).

To answer your original question about how to generate the descriptor, you probably want to compile it from a Miniscript policy. For instance there is a demo compiler at [sipa's website](https://bitcoin.sipa.be/miniscript/). However it needs to be Liana-compatible. The simplest avenue for this would be to use the installer provided with the GUI. You can use the GUI to create the descriptor once, and then manage your wallets entirely programmatically with `lianad`.
