### ISSUE TITLE
[Remote bitcoind] Remove watchonly wallet when removing local wallet

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1046]
If we remove a wallet that have a remote backend, we do not remove it on bitcoind side, it can lead to issue hit in #1045

**Comment by darosior** [comment]
I think we should rather fix the buggy support for non-local bitcoind nodes instead. (https://github.com/wizardsardine/liana/issues/1059)

**Comment by jp1ac4** [comment]
Even if we fix where the watchonly wallet is created, I think we'll still have this issue if we try to create a new wallet unless the watchonly wallet has a different name.

**Comment by darosior** [comment]
True. So in addition to correctly creating the wo wallet (#1059), we should also delete it if `watchonly_wallet_in_bitcoind_datadir` is set when removing a local datadir.

**Comment by pythcoiner** [comment]
> Even if we fix where the watchonly wallet is created, I think we'll still have this issue if we try to create a new wallet unless the watchonly wallet has a different name.

i think we should have a unique name for each wallet like liana<hash>

**Comment by pythcoiner** [comment]
i'm currently working on #1059, and i don't see how we can remove the watchonly wallet on a remote mode, as bitcoin-core does not have a command (or i miss it) for this and we do not have access to the remote filesystem.

**Comment by jp1ac4** [comment]
Hmm I don't think it's possible. The most we can probably do is unload the wallet via RPC and display a message to the user that they need to delete the bitcoind wallet file before creating a new Liana wallet.

> i think we should have a unique name for each wallet like liana

This would also help if we want to support multiple wallets on a remote node.

**Comment by pythcoiner** [comment]
It looks to me #1115 closes this issue, as new wallet names are in the form `liana-<fingerprint>`, tested today:
- create a legacy named wallet on remote from master (b36220504fd895d69d59325eae6527708736b272)
- remove this wallet client-side
- try to create a new one (still from master): it fail like #1045
- try to create a new one from #1115 (549b8f2b7c567861b2817af9f82a11b50fc35b25) works fine, create a new wo wallet w/ new naming

**Comment by pythcoiner** [comment]
now #1141 is merged i think we can close this => 
- we technicaly cannot remove the remote wo wallet from liana
- we avoid user to create new ones

I close it for now, anyone feel free to reopen if we should do something else.
