### ISSUE TITLE
build error for wasm compatible example

### ISSUE THREAD

**Issue by aki-mizu** [wizardsardine/liana#1072]
I tried to build the wasm compatible example in design-system folder but there are some build errors. I'm using the latest master branch.

> error[E0432]: unresolved import `self::platform`
error[E0412]: cannot find type `Context` in module `platform_impl`
error[E0433]: failed to resolve: could not find `Context` in `platform_impl`
error[E0433]: failed to resolve: could not find `Context` in `platform_impl`
error: could not compile `glutin` (lib) due to 4 previous errors

**Comment by edouardparis** [comment]
Thank you for reporting the issue.
The design-system example is not really maintained and we should remove it from our repository.
