### ISSUE TITLE
[Installer] If we set a duplicate alias name, we cannot change it then

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1075]
![image](https://github.com/wizardsardine/liana/assets/124568858/f3b880cf-c74f-4d2e-b50c-cb361c1a16c5)

![image](https://github.com/wizardsardine/liana/assets/124568858/99b312db-98fa-43ab-89c3-0d50d25ff5c4)

**Comment by edouardparis** [comment]
I cannot reproduce the problem on master, I can click on Edit and change the alias and close the modal.

**Comment by pythcoiner** [comment]
humm its fresh v5.0 installed from AUR repo (arch)

**Comment by pythcoiner** [comment]
try to reproduce, cannot, so i close
