### ISSUE TITLE
Can't connect LIana to an Umbrel node

### ISSUE THREAD

**Issue by piratebiscuit** [wizardsardine/liana#1082]
Hey guys,

I'm trying to connect Liana to an Umbrel node I have lying around, I get an unexpected result...
Altough the "Check connection" succeeds, I still get an error saying to "Enter a correct address".

Did the check connection actually fail or did it succeed and Liana simply fails a check because of how the umbrel local address is written?

<img width="968" alt="Screenshot 2024-04-19 at 23 40 14" src="https://github.com/wizardsardine/liana/assets/154634278/547b9068-3c50-4b6f-86be-d53a860aded2">

Thanks

**Comment by pythcoiner** [comment]
humm can you try w/ the direct IP address instead? I think it's oubout the text input validation in our side

**Comment by pythcoiner** [comment]
I guess [here](https://github.com/wizardsardine/liana/blob/f9ea8ec0b6edc533159601d828ffd25134d324ae/gui/src/installer/step/bitcoind.rs#L447) `SocketAddr::from_str()` accept only ip addresses

**Comment by piratebiscuit** [comment]
> Is the `next` button clickable?
> 
> if not can you try w/ the direct IP address instead?
> 
> I think it's oubout the text input validation in Liana side

The Next button is not clickable in this case.

**Comment by jp1ac4** [comment]
> Did the check connection actually fail or did it succeed

I think the check succeeded. The connection check here is done using just the string without trying to convert it to an IP address.

It might be possible to use something like https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html to convert the hostname to an IP address, but the IP address would still be saved in the Liana config file and so you might still have trouble connecting the next time. Please let us know if you're able to connect using just the IP address and we can consider how to proceed.

**Comment by pythcoiner** [comment]
> > Did the check connection actually fail or did it succeed
> 
> I think the check succeeded. The connection check here is done using just the string without trying to convert it to an IP address.
> 
> It might be possible to use something like https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html to convert the hostname to an IP address, but the IP address would still be saved in the Liana config file and so you might still have trouble connecting the next time. Please let us know if you're able to connect using just the IP address and we can consider how to proceed.

i'm wondering if umbrel is using local url because the node ip can change?

**Comment by piratebiscuit** [comment]
For some reason, when I use the IP address of the umbrel node, it fails...

The node ip of the umbrel node can change, but I have it setup to a static IP, so it does not change in my case. I am also farily certain that I am using the right IP because I can connect to the umbrel node using that same IP.

**Comment by jurgen2005** [comment]
Umbrel does not expose RPC to the network:
https://github.com/getumbrel/umbrel/issues/506

**Comment by pox** [comment]
The connection check fails for me when trying to connect to an Umbrel node on the same network.
Port 8332 is listened to on the Umbrel node (`0.0.0.0`), as I've noted in this comment:

https://github.com/getumbrel/umbrel/issues/506#issuecomment-2156319909

It's not a firewall issue. I can curl from the same machine I run Liana on to the bitcoin RPC port. It just fails the connection check without any additional information that could be useful for debugging. Any way to turn on some logging?

**Comment by pythcoiner** [comment]
you can run from cli:
```
LOG_LEVEL=debug liana-gui
```

**Comment by pox** [comment]
Thanks.
All it shows is the following line exactly every 6 seconds, seemingly with no correspondence to click on `Check connection`:
```DEBUG liana_gui::hw:376: Connection refused (os error 61)```

**Comment by pythcoiner** [comment]
> Thanks. All it shows is the following line exactly every 6 seconds, seemingly with no correspondence to click on `Check connection`: `DEBUG liana_gui::hw:376: Connection refused (os error 61)`

hum, looks like this log is about your hardware device, if you try w/o your hardware device connected you should not have this log i think.

**Comment by pox** [comment]
I'm not using any HW wallet. Just trying Liana out with a hot software seed it generates.

**Comment by pythcoiner** [comment]
> I'm not using any HW wallet. Just trying Liana out with a hot software seed it generates.

looks like you have a specter simulator installed on your machine and Liana try to open a connection to it...

**Comment by pox** [comment]
I have no idea what a specter simulator is. Never installed one, I'm pretty sure. I'm trying to connect Liana to a remote node, so I don't really see how that would matter even? Is Liana probing my computer in some way despite being told the IP of the node host?

**Comment by pythcoiner** [comment]
> I have no idea what a specter simulator is. Never installed one, I'm pretty sure. I'm trying to connect Liana to a remote node, so I don't really see how that would matter even? 

Specter DIY is an hardware wallet, SpecterSimulator, its simulator.
this error `DEBUG liana_gui::hw:376: Connection refused (os error 61)` happen when liana detect a SpecterSimulator and try to open a conexion to it.

This did not matter, just flooding your logs.

> Is Liana probing my computer in some way despite being told the IP of the node host?

No its not related, liana probe HW devices (or their simulators) in order to know if they are connected, but do not start interaction w/o user action.

**Comment by pythcoiner** [comment]
Re reading the umbrel issue mentioned early i think:
- umbrel is still not exposing RPC port and they don't plan to do so as they closed the issue as completed.
- Specter Wallet should be installed on your umbrell node (maybe by default?) and should have an embeded SpecterSimulator that related to the previous recurent log message.

**Comment by pox** [comment]
I realize this is what the issue says, but the facts are different:

```
$ nc -z umbrel.local 8332
Connection to umbrel.local port 8332 [tcp/*] succeeded!
```
And you can see the ports exposed in `docker inspect`. 

Also this is the relevant line in their docker-compose which clearly shows they expose the RPC port 🤷 : https://github.com/getumbrel/umbrel-apps/blob/1fdb18b54a8cc1d82834076cdcab7a0381abf9af/bitcoin/docker-compose.yml#L50

Specter Wallet is indeed installed on my Umbrel. 

Is Liana expected to log the reason for a failed "Check connection"?

**Comment by pox** [comment]
From further examining the Umbrel codebase it appears they do expose ports but don't actually define `rpcpassword` in `bitcoin.conf`

Very odd, especially given the UI presents a supposed RPC password that you can copy to connect remotely. Seems kind of broken.

Anyway, clearly this isn't a Liana issue (although the diagnostics could have been a tad clearer), so thank you for taking the time to help me with this and sorry for the noise.

**Comment by pythcoiner** [comment]
I closed it as its definitely not an liana issue.
