### ISSUE TITLE
GUI: have a color scheme

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#109]
Instead of the current black and white theme.

**Comment by darosior** [comment]
Pushing this to v2!

**Comment by darosior** [comment]
Note this issue is about updating the font, icons and colors. Not the layout of the elements from the new design.

Let's post the colors here once we have them.

**Comment by darosior** [comment]
@edouardparis i think this is addressed?

**Comment by edouardparis** [comment]
Yes, Icons needs to be updated still

**Comment by darosior** [comment]
I think this is done. Feel free to reopen if i'm mistaken.
