### ISSUE TITLE
Antoine Poinsot signature has expired

### ISSUE THREAD

**Issue by ElucGeek** [wizardsardine/liana#1101]
When I try to verify the software I get an error because the PQG signature has expired on 07.02.2024.
Will the softwares be signed by a new signature? Or will the same be renewed (not sure if possible)?

**Comment by pythcoiner** [comment]
it's just mean you have to refresh key, see #1077

**Comment by ElucGeek** [comment]
OK thanks, didn't know it was that simple. But I still don't understand why Github mark it as expired too. See screenshot below. This check is not coming from my computer but from Guthub, right?
![image](https://github.com/wizardsardine/liana/assets/10714227/cb1361d2-d7c1-4223-a796-b54f8340abe8)

**Comment by pythcoiner** [comment]
i guess @darosior key have been updated on openpgp servers, and not on the server where github try to fetch it...

**Comment by darosior** [comment]
Yeah i'm not sure where Github is fetching it from. I've tried sending my renewed key to Ubuntu's key server.

Anyways, don't trust what Github is showing you otherwise there is no point in using PGP in the first place. :)

**Comment by darosior** [comment]
Since my up to date key is available on both OpenPGP's and Ubuntu's keyservers i'm going to close this issue.
