### ISSUE TITLE
Have a "average-user readable" representation of the wallet spending policy

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1109]
Currently when a user creates a new Liana wallet, there is no way (if I didn't miss anything) to know which is the wallet spending policy other than checking the descriptor in the settings, which of course is not average-user friendly.

I believe it could be a nice improvement to show it in some more friendly way, either graphical or otherwise. The use case that I have in mind is: average Bob creates a new Liana wallet and before starting receiving his funds wants to be sure that he set the correct spending policy. If he doesn't have a way to do it, he could be refrained from using Liana.

We should probably first discuss usefulness and importance of this feature to decide whether to put this in settings together with the descriptor or in a more visible place.

It kind of relates to https://github.com/wizardsardine/liana/issues/516, even if not for a specific coin but for the general policy information. Anyway some part of the design could be in common.

In my mind, ideally we could also add such view while the wallet creation is ongoing (showing the paths populate at each step), but this is probably part of the ongoing review of the onboarding process.

**Comment by darosior** [comment]
Seems similar to #620

**Comment by nondiremanuel** [comment]
@darosior thanks for pointing it out! I'm closing this and commenting on that issue
