### ISSUE TITLE
After updating Ubuntu, when launching Liana, I don't view the logo anymore

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1117]
After updating Ubuntu to 22.04.04 LTS, when launching Liana the icon doesn't have the logo anymore:

![image](https://github.com/wizardsardine/liana/assets/63922722/200154b7-ed65-4fde-956e-17da7b1568bd)

At first it was a bit confusing since I didn't understand where the window was gone.

**Comment by pythcoiner** [comment]
can you type in a terminal:
```
ls /usr/share/icons/ | grep liana
```

**Comment by nondiremanuel** [comment]
@pythcoiner the first command gave no result (there is in fact no *liana* icon in that folder). The second a "No such file or directory"

**Comment by pythcoiner** [comment]
how do you install liana?

**Comment by nondiremanuel** [comment]
At the beginning, I was using the liana_quicktry tar and built it with cargo and the logo was there. After updating the OS, the logo was not present anymore. Now, for testing purposes I rebuilt liana from master branch and still the logo is not present.

**Comment by pythcoiner** [comment]
can you try to install the *.deb package, it should install the .desktop file & logo

**Comment by nondiremanuel** [comment]
I think we clarified it was due to the way I built the software. So probably it's better to close this issue.
