### ISSUE TITLE
[Installer] do not let user remove first recovery path

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1123]
![image](https://github.com/wizardsardine/liana/assets/124568858/d20e8b74-f331-4b84-8d20-7ae3f13fbba1)

**Comment by nondiremanuel** [comment]
Thanks for pointing this out! I think it will be part of the onboarding UX review process

**Comment by pythcoiner** [comment]
btw it's a nit, as if we hover the error we have a good description of the issue

**Comment by pythcoiner** [comment]
i close this issue in favor of #1407
