### ISSUE TITLE
Add Bump + Cancel to outgoing payment screen

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1129]
We reach this screen frome `Home` page by clicking on one of the last payments:
![image](https://github.com/wizardsardine/liana/assets/124568858/46fc2bd7-e157-4239-81f7-b00947222d5a)

It should be nice to have `Bump` and `Cancel` button here, we actually need to click on `See transaction details`

**Comment by darosior** [comment]
We restricted the RBF buttons to the transactions on purpose, because it may be surprising otherwise.
