### ISSUE TITLE
GUI: Should we do something about the installer being spawned if we start without `--testnet`?

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#113]

**Comment by edouardparis** [comment]
Proposition:
- If a network flag is present
   - no datadir exists -> "Install"
   - no directory exists for this network in the datadir -> **Install**
   - a directory exists for this network in the datadir -> **Run**
- If no network flag is present
   - datadir does not exist -> **Install**
   - datadir exists and multiple network directorires are present ->  try to **Run** by order of priority [mainnet, testnet, signet, regtest], stop at first fail. (ex: liana is setup for regtest and testnet, `cargo run` must run liana with testnet)

**Comment by darosior** [comment]
If no network flag is present and multiple network directories are present i think we should not make a decision for the user. Instead what about having a small popup for choosing the network to start on?

**Comment by darosior** [comment]
cc @kloaec

**Comment by darosior** [comment]
Adding this to the release milestone so we don't forget about it, but it less important to tackle than the other fixes.

**Comment by edouardparis** [comment]
> If no network flag is present and multiple network directories are present i think we should not make a decision for the user. Instead what about having a small popup for choosing the network to start on?

I am not a fan of this, not network flag should go to default like bitcoind

**Comment by kloaec** [comment]
I thought i had put my thoughts here. I'm fine with whatever. My considerations:
- default (99.9% of actual users in the future) will be main-net
- we will probably have a "multi wallet" option, including for the same network. This may change the ux.
- if there ARE ALREADY multiple networks, and none is chosen, it's a tricky question. Probably the best choice is to display the options, with main-net already pre-selected.
- if main-net is NOT already there, I wouldn't pre-select anything, just leave the choice.

extra: I like what Core did with the colors changing depending on the actual network running.

**Comment by edouardparis** [comment]
fixed by #223 
Multiple wallet UX may require more discussions that we can do in another issue
