### ISSUE TITLE
If we register descriptor then edit policy, we cannot register desciptor anymore

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1157]
On colcard, but should also happen w/ sprecter/bitbox/jade

**Comment by pythcoiner** [comment]
step to reproduce:
- create a policy
- go up to descriptor registration step
- register on coldcard
- go back to policy setup screen
- change policy
- go up to descriptor registration step
- the state is still registered

**Comment by darosior** [comment]
Good catch!
