### ISSUE TITLE
Download also bitcoin-cli together bitcoind

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1159]
In order a regtest user can use regtest

**Comment by darosior** [comment]
I don't think we should download a binary for all our users just because a Regtest user *might* sometime need it and not have it already installed by other means.

**Comment by pythcoiner** [comment]
maybe only when we download `bitcoind` for a managed regtest?

**Comment by pythcoiner** [comment]
ok, close it then

**Comment by pythcoiner** [comment]
Note: we already download it as we dl the .tar.gz
