### ISSUE TITLE
GUI: have the derivation index next to the address in the receive screen

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#116]
Not sure how it could be displayed.

**Comment by kloaec** [comment]
Many wallets also let you see the (previous) addresses as a list, it's useful to double check things, as an advanced view.

**Comment by darosior** [comment]
I think this is a typical case for a designer. They can basically re-design the whole screen from scratch. Instead of trying to improve it bit by bit ourselves we could just do that: pay a designer to make a Figma for an improved address generation screen and we implement it at once.

**Comment by edouardparis** [comment]
I think the historic of previous address should be in another issue. Focusing here only on adding the derivation index number.

**Comment by jp1ac4** [comment]
Hi, I could try working on this issue.

**Comment by darosior** [comment]
@jp1ac4 thanks for volunteering! However i don't think this one should be tackled just yet. For two reasons:
1. As i mentioned above we should make a consistent overhaul of this screen and ask a designer to make us a mockup otherwise we'll end up with a Frankestein.
2. This issue was motivated by @kloaec talking about seeing past addresses. But this doesn't really fix it. Instead we should rather have something like an "address explorer" allowing one to see addresses at all (and any index). But as Edouard says it should be tracked in another issue. So i think we can actually close this.

Sorrry for the confusion here. We should be clearer what issues really need to be addressed and what are still under discussion. If you want i could guide you toward another issue, feel free to reach out to me.

**Comment by jp1ac4** [comment]
Hi @darosior, that's no problem. Thanks for explaining that.

I'll send you a message on the IRC channel so that you can point me towards another issue.
