### ISSUE TITLE
Settings > Bitcoin Core: password should be selectable

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1160]
in order regtest user to use the cli for instance

**Comment by aaroncarlucci** [comment]
I took a quick look at this. According to [this](https://github.com/iced-rs/iced/issues/36) `iced` issue, selectable text is not yet natively supported. Some other projects suffering from the same pointed to the workaround [here](https://github.com/iced-rs/iced/issues/645#issuecomment-738525332), which makes use of a `TextInput` widget, restyling it and muting the update/callback.

Currently on-hold as per @darosior on Discord.

**Comment by pythcoiner** [comment]
the easy way is to use the `TextInput` w/o restyling it, setting a dummy message w/ `on_input()` that is not handled in `update()`, so the displayed data cannot be enabled.
