### ISSUE TITLE
Cannot register descriptor from `settings` w/ Jade

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1162]
Jade detected here

![image](https://github.com/wizardsardine/liana/assets/124568858/a2a538c9-ac25-4e9c-a145-39739e211898)

but not here

![image](https://github.com/wizardsardine/liana/assets/124568858/b1a3e2d4-65d9-4d50-a763-cfa6aee731d1)

then if i unplug and re-plug it, it's detected:

![image](https://github.com/wizardsardine/liana/assets/124568858/e8fc03aa-4ce5-4e72-a57f-7b3440cffbc1)

**Comment by edouardparis** [comment]
I can register it, right after wallet creation
![20240701_12h08m38s_grim](https://github.com/wizardsardine/liana/assets/6933020/5a2ac216-887f-4784-b714-cc6871a29703)

**Comment by pythcoiner** [comment]
yes, maybe as the state is keep when we change page, it also keep the connection open
