### ISSUE TITLE
[GUI] Updated wallet settings sometimes not displayed

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#1170]
This happens when clicking on "Wallet" in "Settings -> Wallet" after updating a value.

To reproduce, go to Settings -> Wallet:

![image](https://github.com/wizardsardine/liana/assets/121959000/abd8f1ca-e241-4268-9e13-f28bbc2b74eb)

Change a fingerprint alias and click "Update":

![image](https://github.com/wizardsardine/liana/assets/121959000/896dae20-8365-419b-a182-9582393cad6b)

Then click on "Wallet" in "Settings -> Wallet" and the previous value is shown:

![image](https://github.com/wizardsardine/liana/assets/121959000/3044e904-74de-46d8-9701-911609baf9b1)

The updated value is shown again after navigating away from this page and returning.

**Comment by jp1ac4** [comment]
I haven't checked the code, but I think it's safer to leave it for v7 as it might be necessary to change how the page is loaded.

**Comment by edouardparis** [comment]
I think we are waiting for #1200 to close the issue

**Comment by pythcoiner** [comment]
yes my bad i've misclicked
