### ISSUE TITLE
[GUI] Transaction labels don't refresh from PSBTs screen

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#1174]
After editing the label of a PSBT, the updated value doesn't appear on the Transactions page (either list view or after selecting the individual transaction), unless the Transactions page has not yet been loaded since starting the GUI.

The updated label appears on Transactions page when restarting the GUI.

The other way works: a label that is edited on the Transaction page appears on the PSBTs page.

![image](https://github.com/wizardsardine/liana/assets/121959000/078dcba2-1493-4bd5-9659-e680a9d9c01b)

![image](https://github.com/wizardsardine/liana/assets/121959000/46947475-25fd-420b-babb-bbfe8f8da1dd)

**Comment by kloaec** [comment]
Interesting. Might be (probably is) due to the "state" that we now have in the GUI.
