### ISSUE TITLE
Coldcard taproot integration

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1179]
Based on what we were saying earlier, it should now (or soon) be possible to integrate Taproot using Coldcard. 

Feel free to add details and/or discuss.

**Comment by pythcoiner** [comment]
do we have a firmware for test? @kloaec

**Comment by darosior** [comment]
Their public Edge release should support unspendable internal key as we do them: https://github.com/Coldcard/firmware/blob/new_edge/docs/taproot.md.

**Comment by pythcoiner** [comment]
nice, will give a try

**Comment by pythcoiner** [comment]
done by #1193
