### ISSUE TITLE
[GUI] show version in the "installer" 

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#1181]
We currently only show the version in the Settings, which is after the installer.
Could we display a version number at the bottom/top of the window at all time? Or even in the title of the window, as long as it's easy for support to explain where to find it.

**Comment by pythcoiner** [comment]
agree for the window title bar

**Comment by nondiremanuel** [comment]
I would go with the solution with less effort (which intuitively seems to be in the title, but need to check). We can briefly discuss it in the technical call.

**Comment by pythcoiner** [comment]
imho window title bar is less effort, can be tackle together #1048 if decided to go this way
