### ISSUE TITLE
UI: Add optional setting for number of blocks vs time remaining for recovery path

### ISSUE THREAD

**Issue by schmitmd** [wizardsardine/liana#1195]
I was kicking the tires on Liana via regtest and the "16 hours left before first recovery path becomes available" message isn't really all that useful if the chain isn't moving.

Obviously regtest doesn't move unless you tell it to, so my request is: Can you folks to add back in the "in X blocks" version of recovery path estimation as an optional display format?  Not a huge deal (it can be worked out with the info available, such as by clicking on specific items in `Coins`), but having it in the main page would be really convenient for testing.

**Comment by pythcoiner** [comment]
related (duplicate) to #1161

**Comment by schmitmd** [comment]
My mistake. Sorry!
