### ISSUE TITLE
Reasoning on 65535 max recovery block time?

### ISSUE THREAD

**Issue by schmitmd** [wizardsardine/liana#1196]
Is there a reason that Liana hard-caps the possible recovery block count to this number (besides "u16 doesn't go any higher")?

Is there a Bitcoin-native reason for this restriction?

**Comment by pythcoiner** [comment]
Yes relative bitcoin timelock are encoded on 16 bits,  cf [BIP068](https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki#specification)

**Comment by schmitmd** [comment]
Welp, more RTFM needed. Thanks for pointing me at the right BIP!  This can be closed, sorry for the bother. 

Maybe worth putting a link to this BIP (or similar short explanation) in the error message at https://github.com/wizardsardine/liana/blob/ccc88421b36840bdf9d3a7790edf0eea5738b068/gui/src/installer/view.rs#L1616 ..?
