### ISSUE TITLE
[GUI] v6 panic crash at launch

### ISSUE THREAD

**Issue by venator** [wizardsardine/liana#1197]
I get the following error when trying to start `liana-gui` v6 (I tried the v5 on the exact same configuration, and it's working fine).
```
ERROR liana_gui:491: panic occurred at line 1208 of file /vendor/winit/src/platform_impl/linux/x11/window.rs: Some("Failed to call XMapRaised: XError { description: \"BadMatch (invalid parameter attributes)\", error_code: 8, request_code: 149, minor_code: 4 }")
```

Environment
```
OS: Arch Linux
Kernel: x86_64 Linux 6.9.9-arch1-1
Resolution: 4000x2560
DE: KDE
WM: KWin
CPU: 11th Gen Intel Core i7-1160G7 @ 8x 4.4GHz [49.0°C]
GPU: NVIDIA GeForce GTX 1060 6GB
```

Do you know what could be the cause?

**Comment by edouardparis** [comment]
Thank you for reporting the issue. We are sorry for the inconvenience.

Liana Gui is using the Iced framework to render a native rust UI. This library uses wgpu as a graphics API that has sometimes compatibility problems with all the flavor of drivers, graphics libraries that exists.
Please have a look to the solutions suggested here: https://github.com/iced-rs/iced/issues/2314

**Comment by venator** [comment]
Great, thank you for pointing the `iced` issue to me. Setting these environment variables fixes the problem:
```
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json VK_LAYER_PATH=/usr/share/vulkan/explicit_layer.d liana-gui
```

**Comment by pythcoiner** [comment]
> Great, thank you for pointing the `iced` issue to me. Setting these environment variables fixes the problem:
> 
> ```
> VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json VK_LAYER_PATH=/usr/share/vulkan/explicit_layer.d liana-gui
> ```

Thanks for the feedback!

**Comment by nondiremanuel** [comment]
I will close this issue since it seems to have been solved.
