### ISSUE TITLE
[GUI] unsigned PSBT state not saved

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1206]
Instruction to reproduce:
- Create a wallet w/ a signing device w/o registering descriptor (Jade here)
- fund the wallet
- prepare a spend tx and go up to signing step
- you cannot sign w/ device a descriptor not registered
- go to settings > wallet > register on hardware device
- register the descriptor
- go back to send panel : reseted
- go to PSBTs panel: the PSBT is not recorded

**Comment by pythcoiner** [comment]
note: recorded in PSBTs if partially signed

**Comment by edouardparis** [comment]
Yes, A psbt is saved in two cases: you successfully signed it or you clicked on save.
If not we consider you abandon the spending process or you clicked on previous to change the feerate for example. Maybe we should have a modal to warn user to save when he clicks on the menu items.

**Comment by pythcoiner** [comment]
ok so i close

**Comment by pythcoiner** [comment]
I reopen while testing:

![image](https://github.com/user-attachments/assets/77aeedce-e5df-4eb4-a11d-09dd4f0d1494)

there is no save button for a self transfert
