### ISSUE TITLE
No amount displayed for 0.0BTC

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1218]
intruduces by #1198 i guess
![image](https://github.com/user-attachments/assets/344a7201-080c-4502-a88f-8edab58ce9d8)

**Comment by pythcoiner** [comment]
and i'm not sure we previously had this space:
![image](https://github.com/user-attachments/assets/92dd5f64-66c8-48e7-8c9d-dd9befa5ebd1)

**Comment by edouardparis** [comment]
Arf good catch

**Comment by aaroncarlucci** [comment]
I've taken a look at this and submitted a potential solution in #1219. Removing the spacing has fixed the issue @pythcoiner points out in the second screenshot. I haven't reproduced the conditions in the first screenshot locally, but I assumed it has to do with defaulting blank strings? I've made the `None` case return "0.00000000".

I hope it works, just let me know if you see other issues.

**Comment by nondiremanuel** [comment]
This issue should have been addressed by #1219. Thanks for that!
