### ISSUE TITLE
Use transactions table in commands for better performance

### ISSUE THREAD

**Issue by edouardparis** [wizardsardine/liana#1220]
Actually daemon is fetching from bitcoind a lot of transactions for some commands, it would be more performant to use #1180 to fetch it in batch from the database.

**Comment by darosior** [comment]
I'm not sure what you are suggesting. After #1180 transactions are only fetched once from bitcoind and otherwise always queried from DB.

**Comment by edouardparis** [comment]
Ah right https://github.com/wizardsardine/liana/commit/90df14ce57596d9735e6183b9df197b4b2c1de6c#diff-bf2f650cdc66abd13076c47b25e8c9f783f06ec335bbd30822fdd690547615fdR1034
I thought #1180 will not handle this kind of batch fetch.

**Comment by jp1ac4** [comment]
Oh sorry, I thought there might have been something still to do, but yes it seems that PR already took care of everything.
