### ISSUE TITLE
Add remote Node in the same network

### ISSUE THREAD

**Issue by pizzesser** [wizardsardine/liana#1225]
Hi! I want to set up liana.
i run two fullnodes in my network with Electrum. is it really necessary to install Bitcoin Core on my laptop? is there no way to connect my Raspiblitz odr my Minibolt? If not, can you make it possible?
I dont want to install Bitcoin Core on my Laptop.

thanks!

**Comment by pythcoiner** [comment]
#1222 adress this, it's on our todo for Liana v7!

**Comment by nondiremanuel** [comment]
Thanks for you request. As pythcoiner already explained, we are implementing Electrum BE support. I'm closing this issue since we are tracking the activity with #56. Feel free to add more details if you need :)
