### ISSUE TITLE
integration with PSBT airGAP signers (Krux, seedsigner). Should I wait?

### ISSUE THREAD

**Issue by Garrysoon** [wizardsardine/liana#1227]
You are missing a great feature.  Separate the coordinator function from the signer.

When do you integrate airgap signers such as Krux and Seedsigner?

**Comment by pythcoiner** [comment]
as told on our telegram group, we waiting them to integrate miniscript first, thats a blocking point for now, we cannot do it w/o them :grin:

**Comment by pythcoiner** [comment]
i close this issue in favor of #539
