### ISSUE TITLE
QA - Change requests (wording, UX) on the Liana Connect flow

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1240]
As agreed, I report here some of the change requests to wording and similar related to the liana backend integration:

- [x] 1. The text in the choice of backend step should be adjusted. Now it looks like this:
![image](https://github.com/user-attachments/assets/174bf86d-280a-4b0b-8adf-6a2b6dc21393)
We should insert something like:
- **Your own node**
"Use your already existing Bitcoin node or automatically install one. The Liana wallet will not connect to any external server."
Info/warning: This is the most private option, but the data is locally stored on this computer, only. You must perform your own backups, and share the descriptor with other people you want to be able to access the wallet"
[Select]
- **Liana Connect**
"Use a hosted service to talk to the Bitcoin network and store data. Wizardsardine runs the infrastructure, keeps a backup of your wallet descriptor, and allow for synchronization between multiple computers and participants."
Info/warning: This is a safer option for users who want Wizardsardine to keep a backup of your descriptor. Wizardsardine will be able to see the information of your wallet, associated to an email address. Privacy focused users should run their own infrastructure instead
[Select]
- [x] If feasible, the email and token insertion should be in a following step or in a dedicated popup if the "Liana Connect" option is selected. The text should be something like: "Enter the email address you want to associate to this wallet:"

- [x] 2. The token email title is not correct:
![image](https://github.com/user-attachments/assets/fc108571-b3c7-49b0-ae4b-1958698b99d0)
It should be "Login to Liana Connect"
- [ ] 3. The token email body should be edited to: 
"Connect to the Wizardsardine infrastructure.
This is your one time authentication token: XXXXXX"
The size of the authentication token should be increased.
- [x] 4. When the user enters the token, we should go to the next step without needing the user to click on "Continue"
- [x] 5. In the "Add an existing wallet", right now we have the following options:
![image](https://github.com/user-attachments/assets/82151c03-8766-4a2b-a7df-8e69574ef7d3)
Wording should be reviewed to something like:
- **Load a previously used wallet**
(list the wallets) -> is it possible to show this option only if at least one wallet is present?
- **Load a shared wallet**
Type the invitation token you received by email
Paste token:
- **"Load from a descriptor"**
Use only if the previous don't apply
- [x] 6. The invitation email needs more detail on how to participate in a wallet. Right now it looks like this:
![image](https://github.com/user-attachments/assets/591ebeb5-0f08-4820-947b-e0d76c427a83)
We should add, below the authentication token, the process the user needs to follow. Something like: "**Instructions to load the wallet:** Download Liana [link], click on "Create wallet on Bitcoin Mainnet", select "Add an existing wallet", choose the "Liana Connect" backend option, login inserting your email and a new authentication token, select "Load a shared wallet" and enter this email's invitation token"
7. Discussion ongoing on the invitation process: https://discord.com/channels/1219211834029244466/1219221622053933076/1278263436291084339
8. Discussion ongoing on the load wallet process: https://discord.com/channels/1219211834029244466/1219221622053933076/1278268981819609141

**Comment by edouardparis** [comment]
> If feasible, the email and token insertion should be in a following step or in a dedicated popup if the "Liana Connect" option is selected. The text should be something like: "Enter the email address you want to associate to this wallet:"

Why ? It is more click for the user no ? Or because you want to give more information in an other step ?

**Comment by nondiremanuel** [comment]
> > If feasible, the email and token insertion should be in a following step or in a dedicated popup if the "Liana Connect" option is selected. The text should be something like: "Enter the email address you want to associate to this wallet:"
> 
> Why ? It is more click for the user no ? Or because you want to give more information in an other step ?

I believe having to insert the email there could make the user loose the focus on the difference between the two options. It seems a bit weird to me having to insert the email and then the token all in the same page with all that information about the choice of backend while effectively I already made that choice. Maybe it's just my impression, we can consider other POVs.

**Comment by nondiremanuel** [comment]
As we were saying during the last meeting, the points on the participation flow can also be tackled separately in a follow-up since they are not strictly required for v7 (point 6 and 7).

**Comment by nondiremanuel** [comment]
Actually, I would leave the two options as big headings: "Your Own Node" and " Liana Connect" without any image, also because I believe having "Liana" image for the "Your own node" option is confusing. Do you see any issue with it?

**Comment by nondiremanuel** [comment]
> So I remove also the wizardsardine logo at the login step ? Or just at the two options step ?

To align the issue with what we were saying in the call, I would align it with "Liana Connect" also there.
