### ISSUE TITLE
add unspendable key to path

### ISSUE THREAD

**Issue by adrienlacombe** [wizardsardine/liana#1250]
Hi, wondering if it is in the roadmap to be able to add an unspendable key to the paths easily in the GUI?
Thank you vm
Adrien

**Comment by pythcoiner** [comment]
for which purpose?

**Comment by adrienlacombe** [comment]
@pythcoiner to lock funds for a specific amount of time e.g. primary path is unspendable and then secondary only after n amount of blocks. Does that make sense?

**Comment by pythcoiner** [comment]
humm looks a hack to me, what you asking for in fine is to have a "wallet" where all the path are timelocked? right?

**Comment by adrienlacombe** [comment]
yes, why would you consider this a hack?

**Comment by pythcoiner** [comment]
well, there is no meaning to add an unspendable spending path, if you can just not add it

**Comment by nondiremanuel** [comment]
@adrienlacombe can you help me better understand the use case? Why would you need to not be able to spend for some time? Defense from a wrench attack, tax purposes, other?

**Comment by adrienlacombe** [comment]
@pythcoiner I thought it was mandatory to add a primary path in Liana, am I wrong?

@nondiremanuel wrench attack or even more sophisticated physical attacks, not being able to spend funds is a great feature.

**Comment by pythcoiner** [comment]
> @pythcoiner I thought it was mandatory to add a primary path in Liana, am I wrong?

yes it's a choice in the design, but if we choose do make it not mandatory, we can just drop the path, instead making this path unspendable.

**Comment by adrienlacombe** [comment]
> > @pythcoiner I thought it was mandatory to add a primary path in Liana, am I wrong?
> 
> yes it's a design choice, but if we choose do make it not mandatory, we can just drop the path, instead making this path unspendable.

Correct, I would be fine with this design too. Thank you.

**Comment by pythcoiner** [comment]
@adrienlacombe i think your request is related to #707 and maybe we can move the discussion there (and close this issue)?

**Comment by adrienlacombe** [comment]
> @adrienlacombe i think your request is related to #707 and maybe we can move the discussion there (and close this issue)?

it is related indeed but I guess multiple UX are possible, yes happy to move the discussion there if you prefer.
