### ISSUE TITLE
After reorg `Last payments` are not removed

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1260]
![image](https://github.com/user-attachments/assets/a854a4dd-449e-473c-bd03-5fc71506c379)

but they disapear on after Liana restart

**Comment by darosior** [comment]
Even when you leave home and come back? Surprising.

-------- Original Message --------

**Comment by pythcoiner** [comment]
i think it's because we keep the states of each panel

**Comment by darosior** [comment]
Ah, then it's a newly introduced bug in the gui. I was surprised cause i did remember testing this last year.

-------- Original Message --------

**Comment by pythcoiner** [comment]
i guess introduced in #959

**Comment by edouardparis** [comment]
It stays even if you click again on the panel title or if you leave home and come back ?

**Comment by pythcoiner** [comment]
yes
