### ISSUE TITLE
Don't overload the Electrum server

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#1292]
If we could reduce the lookahead at least (and possibly the gap limit?) it would be nice.

**Comment by pythcoiner** [comment]
i think it's the first step, but finally we should do like sparrow: subscriptions instead polling

**Comment by darosior** [comment]
I think we can just lower the lookahead to something like 20. So that's 30 + 20 = 50, times 2 for change. So a hundred addresses queried per poll if i'm not mistaken? Right now it's 230 times 2.

**Comment by nondiremanuel** [comment]
It was discussed that for v7 we need to understand what happens if a gap limit is hit and what could be the workaround.

**Comment by jp1ac4** [comment]
We'll try 200 gap limit and 30 for lookahead. I'll create a PR for this.

**Comment by darosior** [comment]
Addressed by #1311. Let's see how it goes now.
