### ISSUE TITLE
Self transfert should not have `Cancel transaction` button

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1297]
as the cancel transaction is a bump fee tx in this case (the recipient (self) is the same)
![image](https://github.com/user-attachments/assets/2eafc5db-3f2d-4cc2-a6fb-2075aa9bba5a)

**Comment by jp1ac4** [comment]
This is true if the self-transfer only involves one coin.

In case of more than one coin, the "bump fee" option would include all coins, whereas the "Cancel" option would only require at least one of the coins, so there would be a difference between the two.
