### ISSUE TITLE
HTTP error when spending a coin with Liana Connect

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1304]
Doing some regression testing with a signet wallet, I encountered this error that I've never seen before. My test case was to try and spend almost entirely a coin (leaving <5000 sats) and verifying that we warn the user about spending the dust.

- I started by selecting the coin to spend and choosing an amount very close to it (182000 sats on the 186357 available)

![image](https://github.com/user-attachments/assets/38933451-55df-49bd-9736-b3d28db87602)

- When I start typing the feerate, the following error appears:

![image](https://github.com/user-attachments/assets/9e3754ba-4161-4c5a-ba8b-c867c040f883)

I'm not sure if that's a regression since I can't reproduce this behavior with other coins. For example, the other coin, the one with 0.011 BTC seem to not have the same behavior. So I'm not sure why this applies only to such coin.

**Comment by edouardparis** [comment]
the error the liana-backend respond with:
```
  2024-09-09T13:52:17.726299Z  INFO liana_gui::lianalite::client::backend:748: "{\"error\":\"recipients.1 has an amount under the output value threshold\"}"
```

**Comment by darosior** [comment]
I think this was fixed with the upgrade of the `liana` dependency on the backend, right @edouardparis?

**Comment by edouardparis** [comment]
Yes
