### ISSUE TITLE
Edit Coldcard descriptor registration error message

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1343]
In the descriptor registration on the signing devices step, we currently don't check the firmware version of a Coldcard to tell the user that miniscript is supported only on the Edge one.

The temporary quick fix would be to add for all registration failures happening on Coldcard, independent from the firmware version, an informative note. The error message if the device is Coldcard would then become:

"Failed to register descriptor. Note: the Edge firmware is currently required for Miniscript support"

Is it possible to insert it in the v7 release? If not, I will modify this issue to properly check the firmware version in the following release (which is already WIP if I understood correctly).

**Comment by edouardparis** [comment]
I think it is a problem general to other hardware wallets like jade and bitbox. I am not sure it is a good idea to do one fix for only one device.

**Comment by nondiremanuel** [comment]
> I think it is a problem general to other hardware wallets like jade and bitbox. I am not sure it is a good idea to do one fix for only one device.

The difference with other devices is that users with coldcard could be unable to register even if their device is updated to the latest version. The fact that it is on an edge version of the firmware is specific to Coldcard. That was the reasoning for it. What do you think?

**Comment by nondiremanuel** [comment]
As per what we said during the meeting, we will check directly for the firmware version if it's not on edge we will throw the error: 
"Failed to register descriptor. You need to switch to the Edge firmware for Miniscript support"

**Comment by darosior** [comment]
Now that the PR is ready let's do it, but i don't think this should have been considered for v7. This is not a regression introduced since v6, strictly an enhancement. And we are supposed to be in feature freeze since 2 weeks ago. Sneaking new features in **after** having cut an rc and the very day we are supposed to release is unnecessarily risky in my opinion.

**Comment by edouardparis** [comment]
I tested and feel confident in the PR, but I agree with your feedback. I will include it in v7.
