### ISSUE TITLE
[GUI] Indicate wallet is syncing after creation

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#1361]
When the GUI first opens after creating a wallet, the wallet is not yet synced against the blockchain (its height is returned as 0 by `getinfo`).

We should indicate that the wallet is still syncing, which is especially important for users who've imported a wallet and expect to see transactions.

It may look something like this:
![image](https://github.com/user-attachments/assets/a7d2c630-0cc0-40fc-acd1-d2cc40d31d8d)

With the currently available information, this would be shown while the wallet height is 0 (this might mean on regtest a wallet is shown as syncing even if there is only the genesis block).

A follow-up would be to include the blockchain height in `getinfo` so that we can compare the wallet height with the blockchain height (which could be useful to detect that a wallet has not been opened for a while and needs to catch up).

Note that for users with a local bitcoind, a warning may also be shown regarding the need for a rescan (#804).

**Comment by nondiremanuel** [comment]
This issue covers points 1 and 3 of https://github.com/wizardsardine/ideas/issues/4
