### ISSUE TITLE
[GUI][Connect] Refresh cache more often while wallet height is 0

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#1363]
The cache is refreshed every 120 seconds when using Liana Connect as a backend compared to 10 seconds otherwise.

When first creating the wallet, we will indicate to the user in #1361 that the wallet is still syncing. For Liana Connect, the wallet may appear to be syncing even once this has completed due to the longer cache refresh period.

For Liana Connect backends, we could refresh the cache more often while the wallet is still performing its initial sync (i.e. its height is still 0) and then revert to the current frequency.

**Comment by edouardparis** [comment]
I agree this would be better UX :+1:

**Comment by pythcoiner** [comment]
#1421 have been merged, can we close this issue?

**Comment by nondiremanuel** [comment]
Sure, I forgot to close it.
