### ISSUE TITLE
Error 404 for website to check gpg signature

### ISSUE THREAD

**Issue by rya-sge** [wizardsardine/liana#1374]
**SECURITY.md**
The link behind the hypertext `his personal website` to check the gpg key return a 404 error.
I think it misses the extension ".asc" in the url
**TRY.md**
One of the hypertext (personal
website) points also to an invalid link.
Line: 67

**Comment by nondiremanuel** [comment]
Thanks for pointing this out. I encounter the same issues with those links. We'll need to fix them.
