### ISSUE TITLE
Change should not be shown as unconfirmed

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1375]
During the testing phase of v7, we realized that when sending a tx that doesn't spend the whole coin, the change is shown in the home screen as "Unconfirmed" until the tx is mined. This is not the expected behavior for change, since it should be considered already confirmed.

A first analysis was already performed. Quoting from the discussion we had: 

> GUI does not use the specific endpoint /refresh of the backend, because it uses the common interface with the daemon which is the generate_spend. 
So the change address is just added to the recipients. 
> The fix:
change the payload to pstbs/generate to include a field change_address, that takes the derivation index and the address generated by the gui.

**Comment by pythcoiner** [comment]
Looking into this, a send-to-self (multipath 0) output is also shown as unconfirmed (w/ a bitcoind backend), but should not if we follow the same idea i guess

**Comment by pythcoiner** [comment]
Note: anyway only confirmed coins [are added](https://github.com/wizardsardine/liana/blob/8fb74d1cf95b3bb8848f958cecba5b31e30c8716/gui/src/app/state/mod.rs#L166) to the confirmed balance

**Comment by pythcoiner** [comment]
sparrow behaviour when sending to self:
![image](https://github.com/user-attachments/assets/8fc3533f-71da-4de9-aa6f-4d23a781f765)
- Balance is updated
- Fee amount is unconfirmed unconfirmed

**Comment by nondiremanuel** [comment]
> Looking into this, a send-to-self (multipath 0) output is also shown as unconfirmed (w/ a bitcoind/liana_connect backend, not tested on electrum), but should not if we follow the same idea i guess

Yes, I too believe the send to self should be consistent with the change management.

**Comment by nondiremanuel** [comment]
> sparrow behaviour when sending to self: ![image](https://private-user-images.githubusercontent.com/124568858/376187390-8fc3533f-71da-4de9-aa6f-4d23a781f765.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODM0NTQsIm5iZiI6MTcyODk4MzE1NCwicGF0aCI6Ii8xMjQ1Njg4NTgvMzc2MTg3MzkwLThmYzM1MzNmLTcxZGEtNGRlOS1hYTZmLTRkMjNhNzgxZjc2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwOTA1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWI1MWViYWZmMjkzY2I1YThkMmQxODgwYjVlODJjMTlkOGU3ZmFlYjZmMzlmNWY4ODcwNTQ1ZGQ4MGY5ZWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OKDNg7OcJKmT15E-O8aEjzdtHTk50Td7pYFLkKwj6eI)
> 
>     * Balance is updated
> 
>     * Fee amount is unconfirmed unconfirmed

Electrum has the same behavior. It seems reasonable to me, we could replicate it.

**Comment by nondiremanuel** [comment]
Update after offline chat: let's keep this issue focused on the change management. We will tackle how to show the balance of self-transfers separately (see: https://github.com/wizardsardine/liana/issues/1378#issuecomment-2413350570)

**Comment by nondiremanuel** [comment]
> Update after offline chat: let's keep this issue focused on the change management. We will tackle how to show the balance of self-transfers separately (see: [#1378 (comment)](https://github.com/wizardsardine/liana/issues/1378#issuecomment-2413350570))

After the discussion related to v9 cycle activities, we decided to tackle both the change and unconfirmed self-transfer issues together. It is possible that they will have separate issues, but at the moment the discussion is on the same.

Updating the thread with what we discussed on other platforms:

> The idea is that, when a user broadcasts a tx to an external address which is not yet confirmed, the change should not be shown as unconfirmed since the ownership of that amount is not dependent on the confirmation of that transaction. 
> 
> A similar behavior should be adopted for the self-transfer, where the only unconfirmed part is the change (-X), which is also consistent with what other wallets show (we checked Sparrow and Electrum in particular, see: https://github.com/wizardsardine/liana/issues/1375#issuecomment-2413320681).
> For the self transfer, right now we show as unconfirmed the whole coin (see screenshot in which I refreshed my only coin), while the intended behavior will be to show just the fees as unconfirmed. 

![image](https://github.com/user-attachments/assets/4970e8e7-0201-4eb0-9d58-ea0cd2d22549)

> In the case of the screenshot the balance would be 0.00020877 with "- fees" shown as unconfirmed. The self transfer will continue to not be shown in the "Last payments" list.

The above is related to the case of self-transferring a confirmed coin. For the case in which a user self-transfers an unconfirmed coin, see: 

> I think from implementation point of view, the simplest thing will be to include in confirmed balance the values of all those unconfirmed coins that are fully owned by us. Note that for an unconfirmed coin, being fully owned by us means no unconfirmed ancestors depending on external transactions. So if we refresh an unconfirmed coin from an incoming payment, then the output of this self-transfer will not be owned by us either until the parent coin has been confirmed.
