### ISSUE TITLE
sent-to-self unconfirmed payment not displayed in home screen

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1378]
not displayed in `Home`:
![image](https://github.com/user-attachments/assets/7c8a5bba-da8c-4d71-a88d-486acba0a11a)

but the coin appear in `Coins` screen:
![image](https://github.com/user-attachments/assets/11868884-8f78-4e0b-ab04-f49acff25e2f)

i'm not sure if it's the intended behaviour

**Comment by nondiremanuel** [comment]
I personally think we should only show the fee output as unconfirmed. In the example of having a 1 btc wallet and doing a self transfer with fee 0.01, I would expect having still 1btc as balance and -0.01 as unconfirmed until the self transfer is confirmed. 
The alternative would be to show directly 0.99 as confirmed balance while still having the coin unconfirmed in the "Coin" section (similar to what Electrum does), but I think this would be less consistent.

**Comment by edouardparis** [comment]
Send to self transactions are not displayed in the home as they are not considered as payments.

**Comment by nondiremanuel** [comment]
> Send to self transactions are not displayed in the home as they are not considered as payments.

Yes, probably the issue title should be reviewed to indicate that the matter is about how we show the balance in self transfers. We can also use a different issue, as you prefer.
