### ISSUE TITLE
gui: Set a title and an icon to the window

### ISSUE THREAD

**Issue by edouardparis** [wizardsardine/liana#138]
https://github.com/iced-rs/iced/commit/9a037a23e9b32d9dbe7086a54d777b5f0550a660

**Comment by darosior** [comment]
Did you remove it from the fix list too?

**Comment by darosior** [comment]
I think you added a title already? It's fine for the first version to not have any icon as long as we have a title.

**Comment by pythcoiner** [comment]
i think this have been done

**Comment by darosior** [comment]
Thanks for the reminder, closing this.
