### ISSUE TITLE
Define and implement different templates for wallet setup

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1382]
We started the implementation of the UX/UI revamp with the following template choice:
- Inheritance template -> single sig as primary + single sig as recovery
- Custom setup

The implementation was done in a way in which adding new templates should be pretty straight forward. We need to decide which templates to add first and then effectively implementing them. Note that each of them, having the explanation step at the beginning, should have an svg representing the general keys scheme.

**Comment by pythcoiner** [comment]
i think this issue can be closed @nondiremanuel
