### ISSUE TITLE
Installer - "Apply" button sometimes not filled when setting up a key

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1402]
When trying to setup the keys in the different templates, sometimes the "Apply" button is not correctly formatted, missing the content and text:

![image](https://github.com/user-attachments/assets/77c58ada-f974-43ec-8cc7-bf79df59c318)

![image](https://github.com/user-attachments/assets/8f94a447-2b93-43ef-ac3d-41cd53356236)

**Comment by nondiremanuel** [comment]
As @edouardparis made me recognize, by increasing the size of the window, the text correctly appears:

![image](https://github.com/user-attachments/assets/8dee2299-7a99-43dc-8957-21b341b46f5c)

Can we still adapt the behavior to smaller window sizes?

**Comment by pythcoiner** [comment]
i think we can make the content scrollable

**Comment by jp1ac4** [comment]
I also found that I could not see the text entered in the alias text box until I made the window bigger, even though the text box was displayed on the screen.
