### ISSUE TITLE
Wording corrections for installer flow

### ISSUE THREAD

**Issue by nondiremanuel** [wizardsardine/liana#1418]
We had a joined discussion and this are the main wording points that can be worth tackling for this release. Other UX/UI improvements will be managed separately:

- Landing page: try to add "Liana" before "wallet" in both "Create a new wallet" and "Add an existing wallet" and see if it fits or if that's too long. This is to avoid confusion since a user reported that, since he wanted to use a hardware "wallet" already in his possess, he thought that "Add an existing wallet" was the right flow. Alternatively we could think of something like "+ new Liana wallet" and "+ existing Liana wallet"
- Choose wallet step: remove the sentence before the different template options since it is not very useful and clear.
- Change the name and description of the multisig template to: 
"Expanding Multisig
Two keys required to spend, with an extra key as a backup."
- Change the name of the custom template to: "Build your own"
- In the Simple Inheritance introduction page:
   - Add "Simple" before "Inheritance" to the title
   - Change the first sentence to: "For this setup you will need 2 keys: a Primary Key (for yourself) and an Inheritance Key (for your heir). For security reasons, we suggest you use a separate Hardware Wallet for each key."
   - Delete the "Give it to your heir(s) in order to be able to collect their inheritance." part in the second sentence
   - Change the svg with the new one: https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=580-5674&t=thV2HkmdCIiWt42U-4
   - Change the "Select" button to "Next"
- In the Expanding Multisig introduction page:
   - Change the title to "Expanding Multisig wallet"
   - Change the first sentence to: "For this setup you will need 3 keys: two Primary Keys and a Recovery Key.  For security reasons, we suggest you use a separate Hardware Wallet for each key."
   - Change the second sentence to: "The Primary Keys will compose a 2-of-2 multisig which will be always able to spend. In case one of your keys becomes unavailable, after a period of inactivity you will be able to recover your funds using the Recovery Key together with one of your Primary Keys (2-of-3 multisig)."
   - Change the svg with the new one: https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=528-5494&t=thV2HkmdCIiWt42U-4
   - Change the "Select" button to "Next"
- In the Build your own introduction page:
   - Change the title to "Build your own"
   - Change the sentences and svg according to the following mockup (@jp1ac4 feel free to edit some wording. I chose using the word "policy" because it seemed to be the most adapt to me): https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=1-11564&t=thV2HkmdCIiWt42U-4
   - Change the "Select" button to "Next"
- In the "Build your own" "Set keys" page:
   - Remove the introductory sentences to the paths and just leave the boxes with headings
   - Try editing the text of the "Add key" and "Add recovery path" to "Add another key" and "Add another recovery path" and see if they don't get too big (possible alternatives: just "+ Another key" and "+ Another recovery path")

**Comment by jp1ac4** [comment]
> * Landing page: try to add "Liana" before "wallet" in both "Create a new wallet" and "Add an existing wallet" and see if it fits or if that's too long. This is to avoid confusion since a user reported that, since he wanted to use a hardware "wallet" already in his possess, he thought that "Add an existing wallet" was the right flow. Alternatively we could think of something like "+ new Liana wallet" and "+ existing Liana wallet"

Another option is remove a/an, i.e "Create new Liana wallet" and "Add existing Liana wallet" depending on how it looks.

**Comment by pythcoiner** [comment]
> * Change the sentences and svg according to the following mockup (@jp1ac4 feel free to edit some wording. I chose using the word "policy" because it seemed to be the most adapt to me): https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=1-11564&t=thV2HkmdCIiWt42U-4

do you expect some works to be in bold in the gui like in figma @nondiremanuel ?
![image](https://github.com/user-attachments/assets/d8c00e2b-f8ec-4054-9ff6-553e304a7237)

**Comment by nondiremanuel** [comment]
> > * Change the sentences and svg according to the following mockup (@jp1ac4 feel free to edit some wording. I chose using the word "policy" because it seemed to be the most adapt to me): https://www.figma.com/design/HavLBX9PEXIKBbC5W5qUSx/Liana-Desktop?node-id=1-11564&t=thV2HkmdCIiWt42U-4
> 
> do you expect some works to be in bold in the GUI like in figma @nondiremanuel ? ![image](https://private-user-images.githubusercontent.com/124568858/382677290-d8c00e2b-f8ec-4054-9ff6-553e304a7237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDgzMDIsIm5iZiI6MTczMDcwODAwMiwicGF0aCI6Ii8xMjQ1Njg4NTgvMzgyNjc3MjkwLWQ4YzAwZTJiLWY4ZWMtNDA1NC05ZmY2LTU1M2UzMDRhNzIzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQwODEzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjEwZDkyOGNmZWY4YjgzNzFiZjQ1ZmU1MDgzNmU5NTE3MmM4ZGFiZGNhMTNkZDY1YjNkMDVlNjBiNTg5OTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lqCaWugj62AG9qCoDLqQbgZFn7x_8k5ZjnWGq07J9-0)

Not strictly required, but if quickly feasible it would be nice imho.
