### ISSUE TITLE
GUI should check the Liana daemon version at startup

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#1429]
When using an external daemon, we don't currently check its version when starting the GUI.

This issue came up in #1377 when the GUI started using a new `Option` field in the `getinfo` response.

It was suggested in https://github.com/wizardsardine/liana/pull/1421#discussion_r1827688881 that the external daemon should have the same version as the embedded daemon.

The task would then be to check the daemon version when the GUI starts (at least for an external daemon) and make sure it is the version corresponding to that used by the embedded daemon.

**Comment by pythcoiner** [comment]
looks like the same intend of #449 , wich issue we should keep?

**Comment by jp1ac4** [comment]
I'll close this in favour of the original #449.
