### ISSUE TITLE
BIP326 Anti-fee-sniping in taproot transactions

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1467]
if/when we decide to set taproot as default, we should consider implementing [BIP-0326](https://github.com/bitcoin/bips/blob/master/bip-0326.mediawiki) for fee sniping.

note: a [PR](https://github.com/bitcoin/bitcoin/pull/24128) is open on bitcoin-core about this topic

**Comment by pythcoiner** [comment]
@darosior this [TODO](https://github.com/wizardsardine/liana/blob/327f0ea665d57d564db93b58a98caf3b71a5e500/liana/src/spend.rs#L796) seems related, right?

**Comment by darosior** [comment]
Yes it is. But this issue is a duplicate of https://github.com/wizardsardine/liana/issues/45.

-------- Original Message --------

**Comment by pythcoiner** [comment]
i close this one then.
