### ISSUE TITLE
GUI: *actually* allow to connect to a running daemon (ie do not require lianad's config)

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#147]
If there is already an existing deployment.

```
$ ls ~/.liana/testnet/
lianad_rpc  lianad.sqlite3  lianad_watchonly_wallet
$ cargo run -- --testnet
# This spawns the installer, which in turn says there already is an existing datadir for testnet...
```

**Comment by edouardparis** [comment]
The Gui cannot start the daemon if it does not find ~/.liana/testnet/gui.toml.

**Comment by edouardparis** [comment]
path to the daemon.toml, and in your case, the path is not default one

**Comment by darosior** [comment]
I'm not sure i understand in my example above there is a testnet datadir at literally the default path:
https://github.com/revault/liana/blob/f03b617490fe701635307160accba14073e502c5/src/config.rs#L146-L172

**Comment by edouardparis** [comment]
> Can it be made to not require the path to the daemon configuration file? Would that be an unreasonable refactoring?

Yes we can make that the gui when connecting to a running Daemon need only the rpc socket. But in this case if it does not have access to config, then the all settings panel cannot display stuff about bitcoind.

**Comment by darosior** [comment]
This is very unfortunate but we should probably drop this from the release milestone.

**Comment by darosior** [comment]
Unfortunately this needs again slip to the next release..
