### ISSUE TITLE
GUI: sort coins when they are displayed

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#193]
We need to decide first how to sort them. cc @kloaec @edouardparis.

**Comment by kloaec** [comment]
IMHO basic is chronological:
1- block time
2- index in block

Then we can offer options to users by amount or whatever, but new events shouldn't appear in the middle of a section for no reason.
I think this is not controversial?

**Comment by darosior** [comment]
Ack for chronological order.
------- Original Message -------

**Comment by kloaec** [comment]
Screencast here showing the random sorting currently

[Screencast from 2022-12-15 11-39-12.webm](https://user-images.githubusercontent.com/15522963/207861569-4bea4940-70c2-4c88-b286-a145cc91c1ad.webm)

**Comment by darosior** [comment]
@edouardparis do you need more information to be stored in DB to tackle this too? If so it can be done at once along with #281.

**Comment by edouardparis** [comment]
No thanks, I already have the `outpoint` and the `block_height`
