### ISSUE TITLE
GUI: send-to-self transactions are incorrectly displayed

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#199]
See the attached screencast.

[Screencast from 2022-12-08 17-23-15.webm](https://user-images.githubusercontent.com/22457751/206678977-fa02aef4-93c1-4c72-bcad-e75f767d2a48.webm)

**Comment by darosior** [comment]
It's not incorrect but at the very least extremely confusing. @kloaec any suggestion on improving this?

**Comment by edouardparis** [comment]
Yeah I do not know what to do for this kind of transaction

**Comment by kloaec** [comment]
I'm still not a fan of this. Would appreciate a "Send to self" label instead of 0.0000

**Comment by darosior** [comment]
Status update: this will be addressed as part of a larger overhaul of the UI for 1.0.
