### ISSUE TITLE
At fresh daemon startup, setup first bitcoind before database

### ISSUE THREAD

**Issue by edouardparis** [wizardsardine/liana#20]
During a fresh install the bitcoind should be setup before installing the sqlite database,
because if done after and the bitcoind port in the config is wrong for example, the database and the datadir are already created which force user to remove it by hand before installing again with the good port number

**Comment by darosior** [comment]
Good point. But it would be the same the other way around with the watchonly wallet file. What we should probably do is:
- If this is a fresh directory
  - If there is an error in setting up the fresh directory
    - Catch the error, and remove the directory entirely

**Comment by edouardparis** [comment]
database setup requires only the read and write to the filesystem, but the watchonly requires the filesystem access AND a working connection to bitcoind.
That why it has more "case" to fail and should be done first.

No opinion yet on the clean process in case of failure

**Comment by darosior** [comment]
I'm assigning you to this issue. What we should do is what i detailed above: if there is an error in the setup of a fresh data dir, catch it remove the directory.
