### ISSUE TITLE
Functional test for importing a descriptor, rescanning, then sweeping

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#202]
https://github.com/revault/liana/pull/182 only introudces a very basic functional test for the recovery transaction creation. It would be nice to also test the typical flow of a user that recovers coins.

**Comment by Eunovo** [comment]
@darosior I'm interested in working on this, can you assign it to me?

**Comment by darosior** [comment]
For sure! Reach out for guidance or validating the approach if you feel the need.

**Comment by darosior** [comment]
Sorry for the delay in responding, i was traveling.

Your flow is correct. To simulate the startup of a new `lianad`, i think you could use the `restart_fresh` method: https://github.com/wizardsardine/liana/blob/0406085ed5a23bfcfb94eb36ac79a2734ae38a3d/tests/test_framework/lianad.py#L105-L115

I think a better place than `test_misc.py` is `test_chain.py`. You could draw some inspiration from the `test_rescan_edge_cases` test. https://github.com/wizardsardine/liana/blob/0406085ed5a23bfcfb94eb36ac79a2734ae38a3d/tests/test_chain.py#L172
