### ISSUE TITLE
GUI: display an estimate of time next to the number of blocks in the installer

### ISSUE THREAD

**Issue by mariabmont** [wizardsardine/liana#206]
if people don't understand bitcoin that well and want just a wallet, could we have next to the number of blocks the approximate time that corresponds to it?

**Comment by darosior** [comment]
Yeah we could at least display an approximation. However i'm afraid having the input itself in seconds would be confusing: it is also possible to have time-based timelocks in Bitcoin, and the units are multiples of 512 seconds (and not the typically expected 600 seconds interval between blocks).

**Comment by darosior** [comment]
@edouardparis i think this was addressed in 0.4? Please feel free to reopen if i'm wrong.
