### ISSUE TITLE
GUI: "pending" on the home for tx being sent -> should be "pending inclusion in a block"

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#230]
The home currently displays "pending" when a transaction is being SENT. Pending could mean a lot of things, when in this context it just means unconfirmed (but already signed and broadcast).
The tag should be clearer, "Pending inclusion in a block"

**Comment by kloaec** [comment]
![Screenshot from 2022-12-15 11-29-54](https://user-images.githubusercontent.com/15522963/207860711-c64c9c82-64f9-4a4f-b8f7-0076fd4329bd.png)

**Comment by darosior** [comment]
Or just "unconfirmed"? I think the current label was ported from Revault where it didn't make sense to have an "unconfirmed" label at this stage since the transaction wasn't broadcast before some time.

**Comment by darosior** [comment]
Related to #231. I think we should just get rid of the Revault terminology everywhere ("Pending", "Broadcast", ..) and just replace it with "unconfirmed" the way described here: https://github.com/wizardsardine/liana/issues/231#issuecomment-1354552317.
