### ISSUE TITLE
GUI: "Pending" for coins being received.

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#231]
We currently don't display unconfirmed deposit tx on the Home screen. This is debatable for some users, but good practice as a not confirmed tx does not belong to the user yet, and could never make it.

That said, the user can CPFP. The coin is therefore displayed in the "Coins" section. It currently does NOT show this coin as unconfirmed, which is pretty critical IMHO.

This issue is to add a "Pending inclusion in a block", and maybe even an infotip about CPFP for the users in coin selection.

**Comment by kloaec** [comment]
![image](https://user-images.githubusercontent.com/15522963/207860800-57c1561c-224e-4b4f-9667-cbcceb82999e.png)

**Comment by darosior** [comment]
@kloaec what do you think? I think it's one of the most pressing imperfections to tackle.
