### ISSUE TITLE
GUI: Psbt import in spend -> will be useful for airgapped signers and multisig flow later.

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#234]
I know this is already planned as part of the multisig release, but this issue is a tracker to avoid getting the same feedback duplicated: we know import psbt is important for many different reasons, and it'll come soon.
Discussions on specific use-cases are welcome here so it's implemented in a nice UX.

- Multiparty multisig
- Airgapped signers
- ?

**Comment by darosior** [comment]
I think this should be more precise. At the moment as far as i can tell only two signing devices are able to reasonably be used with Liana: Specter and Ledger. I know some others may allow signing but it's useless if for instance they can't check change, or generate receive addresses to be checked on the device.

**Comment by darosior** [comment]
Can this be closed now that the import of PSBTs was implemented along with the multisig support in the GUI?

**Comment by darosior** [comment]
I'll just close this for now. Feel free to re-open if you think it should be (and please explain why).
