### ISSUE TITLE
Feature: Cancel TX, and other replacement transactions (RBF)

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#236]
A cancel TX of an already broadcast (not mined) transaction would be a nice feature.
Automatically craft a transaction spending the inputs, select a higher fee(-rate), ask to sign and broadcast. Tracking of success/failure would also be very nice.

A generalization of this tx flow would also be very nice, allowing to EDIT an existing TX. It would allow changing amounts, potentially replacing inputs and outputs, and make a good fee estimation to actually follow RBF rules.
This is an advanced feature but would be pretty cool.

**Comment by darosior** [comment]
I don't think it should be that much configurable. A simple "cancel" button à-la Electrum seems better.

I don't think going as far as an EDIT button is a good idea. It would be a very brittle feature with a very poor UX: it would sometimes fail for no reason apparent to an unsuspecting user.

A cancel button is a good middle ground.

**Comment by darosior** [comment]
See also already opened #43 about this.

**Comment by darosior** [comment]
This is being tackled, but is on hold. See #43 and the coin selection / RBF pull requests.

**Comment by darosior** [comment]
Closing in favour of https://github.com/wizardsardine/liana/issues/43, where most of the discussion has been happening.
