### ISSUE TITLE
GUI: "unknown error" for low amount outputs

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#237]
I guess it's a dust threshold? Doesn't seem "unknown" to me :)
![image](https://user-images.githubusercontent.com/15522963/207909047-0deb7c0e-33c1-4ad8-b675-3fbd1ec5362b.png)

**Comment by darosior** [comment]
Yeah we should have a more specific error enum variant on the daemon side, and the GUI should match with a friendlier error message.

**Comment by edouardparis** [comment]
Gui should mark the recipient as invalid at the previous step

**Comment by darosior** [comment]
Right, that too.
------- Original Message -------
