### ISSUE TITLE
Display liana version in the gui

### ISSUE THREAD

**Issue by edouardparis** [wizardsardine/liana#243]
Required in order to provide support

**Comment by kloaec** [comment]
yes.
Probably the best place for it is in Settings. If we could also display Core version, and other potential support related info, it would be cool. (Let's discuss here what we need).

I originally was thinking to display it in small at the bottom of the GUI, but it's useless in normal days and potentially people who need support don't have the best sight.

**Comment by darosior** [comment]
We shouuld be able to access system information too using the Rust stdlib. Probably worth having too.
