### ISSUE TITLE
GUI: better error message when we try to use the recovery path before its available

### ISSUE THREAD

**Issue by mariabmont** [wizardsardine/liana#248]
When you do a spend and you sign with the ~~wallet~~ key from the recovery path before it is available it pops up an orange "unknown error", it should be explained why the error exists. 
![image](https://user-images.githubusercontent.com/118536288/208142251-736e46bf-6ea4-4de2-b45f-a99cecd3cf51.png)

**Comment by darosior** [comment]
Yes. But i think we should have an umbrella issue for all these cases where the internals (`lianad` or the Liana library) return an engineer-readable error that the GUI should translate into a user-readable one.

**Comment by pythcoiner** [comment]
this issue seems not relevant now, as we now display wich signature is missing and we don't let user try to broadcast if signatures are incomplete:
![image](https://github.com/user-attachments/assets/de495b2d-8b8b-4f94-8fe8-9b1b5a3755a0)
so i'll close this issue.
