### ISSUE TITLE
GUI: incorrect wording on greeting page

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#263]
![image](https://user-images.githubusercontent.com/22457751/208698726-2be16db6-cdb2-42a4-8683-a65831182f99.png)

1. It should not be "install on another network" if there is no network for which it is installed in the first place
2. Isn't "welcome *back*" incorrect if it's the first time we start Liana?

**Comment by darosior** [comment]
cc @kloaec

**Comment by edouardparis** [comment]
weird it should go in install mode directly

**Comment by edouardparis** [comment]
I tried and got directly the install when the datadir does not exist
I think your .liana directory did exist

**Comment by darosior** [comment]
Oh i routinely deleted network-specific datadirs to test the installer, so maybe it's that: it existed but was empty.
------- Original Message -------

**Comment by kloaec** [comment]
I guess it's a cool edge case: still "welcome back", but not "another network" :)

**Comment by trigger67** [comment]
I can confirm that this happens when the .liana directory exists, but without config for a specific network (empty directory).

I think an empty directory could be managed as no directory at all because : 
 - Why differentiate a clean uninstall and a "less clean" uninstall ?
 - Fewer cases to manage = less code and less bugs

 If agreed I can update this so that when there is no directory for specific network it will go in install mode.

**Comment by PaarthAgarwal** [comment]
Hi. I'm getting started with Liana and I'd like to work on this issue. Can you point me to the relevant files for this issue

**Comment by TChukwuleta** [comment]
Hello, @darosior  how about this, thought of something generic to cater to both new and existing users.

Let me know what you think, and if this is fine, then I can raise a PR

![image](https://github.com/wizardsardine/liana/assets/47084273/6df5fdb1-ea23-4c8e-9c87-8d705973dab4)

**Comment by pythcoiner** [comment]
> Hello, @darosior how about this, thought of something generic to cater to both new and existing users.
> 
> Let me know what you think, and if this is fine, then I can raise a PR

@darosior

**Comment by darosior** [comment]
I don't think this user is active anymore.

-------- Original Message --------

**Comment by pythcoiner** [comment]
> I can confirm that this happens when the .liana directory exists, but without config for a specific network (empty directory).
> 
> I think an empty directory could be managed as no directory at all because :
> 
> * Why differentiate a clean uninstall and a "less clean" uninstall ?
> * Fewer cases to manage = less code and less bugs
> 
> If agreed I can update this so that when there is no directory for specific network it will go in install mode.

agree with this point, can we go forward and follow this way? if @trigger67 is not interested in working on this I can handle it.

**Comment by trigger67** [comment]
Yep do it @pythcoiner

**Comment by pythcoiner** [comment]
adressed by #919
