### ISSUE TITLE
GUI: Incorrect text on recovery screen

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#265]
This is not the coin recoverable at the current blockheight, but those that will be spendable through the recovery path in the next block.

![image](https://user-images.githubusercontent.com/22457751/208699413-37a2b3d2-91ff-4142-9c5e-3595477ae69f.png)

![image](https://user-images.githubusercontent.com/22457751/208699365-67c72eb3-49e7-40f6-a9fb-32affec9367b.png)

**Comment by trigger67** [comment]
I started reworking this screen.

First thing I did is : 
 - Align the image and title
 - Change the text as mentioned in the issue 
 - Remove the "1/2" subtitle => I think it can be misleading, it was for me as I had 2 coins to recover, and thought it could mean it apply only for the first one.
 - Switched the two inputs: address and feerate

Should I continue working on that screen and open a PR ?

![image](https://user-images.githubusercontent.com/10185784/214432309-a8bd86e0-1c47-4bd2-af63-18ae3364bc89.png)

**Comment by edouardparis** [comment]
Nice !
Good job for finding your way in the entangled forest of components of the GUI.
From what you described, your changes should fix the current issue so feel free to open a PR with your current state.
Next screen after the recovery transaction generation will be radically changed by the new multisig PR #289, so no need to change it. 

In case you want to learn more about the iced framework, the documentation is quite missing but the [examples](https://github.com/iced-rs/iced/tree/master/examples) examples are a good way to start understand the `elm` architecture.
(I am myself still struggling to understand what are the good patterns and good practice).
Cheers

**Comment by trigger67** [comment]
Yes it reminds me the early days of Android development, I'm used to work with messy stuff :sweat_smile: 

OK thank you for all these info, I'll open a PR and look at these examples!

Cheers
