### ISSUE TITLE
Transaction or Address description

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#273]
It would be helpful to be able attach a small comment or description to a transaction or an address. Note this is different (and likely faster to implement) than labeling, see #59 for this.

Some open questions:
- In #59 i mention that Jimmy and @kloaec think it makes more sense to label by address instead of transaction. @edouardparis mentioned to me today he was thinking we should support both. Should we support attaching a description to a transaction? (As in a Bitcoin transaction, not as in a payment / financial transaction)
- Should we attach a description to our addresses? External addresses? Both? If so should we separate them somehow?

**Comment by darosior** [comment]
I think it makes sense to have a coin-oriented UI on the wallet. In this spirit it makes sense to be able to attach a small description to a coin. Alex pointed out it is useful to be able to effectively choose coins during the spend tx creation process.

**Comment by alexwaltz** [comment]
@darosior I really like this "coin-orientated" framing and i think it makes sense for Liana, more than any other wallet.

But let's say I labeled a coin as "Salary from January" and then I spend half of it, this will create a new change-coin.
Should this change coin still be labeled Salary from January?
Should it inherit this label, but with a greyed-out color?
Should the wallet add a change tag in front of it to know its change from "Salary from January"?

**Comment by darosior** [comment]
No i don't think labels should ever be arbitrarily transferred from a spent coin to a created coin in a transaction.

This does make me think perhaps we should label coins and not addresses. So you can attach a label to a coin in the coins list.

**Comment by darosior** [comment]
xref https://github.com/wizardsardine/liana/pull/605

**Comment by darosior** [comment]
We are going to have what we call "labelling" support in v3, but that's essentially what the OP describes: a small sentence describing an output, a transaction or an address. I'm going to close this, if we want to improve over the current situation let's revisit this in a new, updated, issue.
