### ISSUE TITLE
GUI: sort Spend transactions drafts

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#281]
Similar to  #193.

If we want to sort in chronological order, we'll need to have the creation date to be stored in the DB too.

**Comment by edouardparis** [comment]
I am thinking to name the new field: `stored_at`
Not `created_at` because if the user imported the psbt from another user, the time stored is not the real time of creation of the PSBT

**Comment by darosior** [comment]
Let's think of other sorting strategy before to make sure which one we wanna go for?
------- Original Message -------

**Comment by darosior** [comment]
Good suggestions. Let's split this between going from no sorting (current situation) to an acceptable sorting, and then improving the sorting.

So yeah i agree Edouard latest at the top seems the only reasonable small fix.

-------- Original Message --------

**Comment by edouardparis** [comment]
> So yeah i agree Edouard latest at the top seems the only reasonable small fix.

So a new field `stored_at` to listspendtxs response is required for the gui to sort the list

**Comment by darosior** [comment]
Yes. Can you take care of that? It shouldn't take long to add.

**Comment by darosior** [comment]
We decided to push this to v2.

**Comment by darosior** [comment]
Let's see if we can have this in 0.3.
