### ISSUE TITLE
GUI: multisig integration

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#283]
*(This is mostly notes after a call with Edouard, might be confusing and not well articulated)*

Users will have to share and import PSBTs not only for regular spend transactions, but also for recovery transactions. @edouardparis points out the software of the cosigner should detect whether it is a recovery spend. It is helpful to hint the user at using a specific device or as a general better feeling of the UI: if say in the future with #54 we have multiple timelocked path it would be confusing for the user to receive a PSBT and not know what device to use in order to sign it (or to sign it with the wrong device only to be told afterward the signature wasn't valid for the spending path the PSBT was created for).

We contemplated a few options. For instance Edouard mentioned relying on the BIP32 derivations as he had suggested already in #53. See my response there for why we discarded this option. We could rely on the nSequence value and the descriptor's timelocks to determine for which path the PSBT was created. But what if two paths have the same timelock? What if we have [nSequence-anti-fee-sniping once we have Taproot](https://github.com/wizardsardine/liana/blob/80fb0ecb01f65c15782f215fdda9bc99ad6c78d2/src/commands/mod.rs#L334-L335)?

I think the only reasonable solution to transmit this information (ie what path was intended to be used) along with the PSBT is to use a [BIP174 proprietary field](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#proprietary-use-type). I think it should be by input.

What if the PSBT mixes recovery and primary paths spendings? It's even more likely once we have multiple timelocked paths. Since a PSBT created with a nSequence for the `n`th path is also valid for all the previous paths. So for instance one participant may create a PSBT that uses the 3rd timelocked path, and other participants may satisfy the conditions of the 2nd path.

cc @edouardparis @kloaec.

**Comment by kloaec** [comment]
Recovery Transaction: any transaction that requires lapsing of a lock time / using any spending path that isn't the normal path.
(just for clarity for outsiders)

This is a really cool discussion topic! Sad i missed the call.

Without putting much thoughts into it, I think this should be a visual/client thing, not a PSBT thing.
We may be able to visually show who (what key) signed, and who (what key) didn't. This would allow mixing even different paths within a same PSBT if I understand how it would work correctly.

3(K1❌ K2❌ K3✅)
Or: CSV 200 and 3(K4✅ K5✅ K6❌ K7❌)
Or: CSV 999999 and K8❌

So no new field in PSBT, but good hint (assuming we can label keys) on the UI.
(maybe what i'm saying is invalidating the PSBT, but i don't think so?)
The client would say when a path is valid, and finalize with only the necessary sigs for it before broadcast.

**Comment by darosior** [comment]
You can't solve this by only showing the signatures as you propose since this might give the impression to the user they can satisfy any path. But in fact you set the nSequence when creating the PSBT so you make some paths unusable.

Hmm now i wrote that i'm thinking you may be right. We could just display the signatures for the paths that are usable with this transaction. That makes sense to me.

-------- Original Message --------

**Comment by edouardparis** [comment]
closed by #289
