### ISSUE TITLE
GUI installer: add a previous button

### ISSUE THREAD

**Issue by trigger67** [wizardsardine/liana#306]
Currently, when a wallet is already set, clicking on "Install Liana on another network" opens the installer, with no way to go back.
If you miss click, you have to close and open the app, that's bad.

Adding a previous button, only when the user came from the launcher screen, would fix this.

I tried but didn't find a way to do it, while keeping the current UI, with the 3 buttons staying in the center of the screen.
So either :
 - Find a way to do it probably by using another layout than Row or Column
 - Add the previous button in the middle of the screen too
 - Put everything on the top of the screen

![image](https://user-images.githubusercontent.com/10185784/216382903-b89c9652-436e-48da-95ed-ecf8bf7c47b7.png)

**Comment by darosior** [comment]
That certainly sounds desirable. Let's see what @edouardparis says about the feasibility.

I don't know what could be a good spot on the UI for the button.
