### ISSUE TITLE
GUI: trim whitespaces in inputs

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#323]
For instance it'd be nice for when importing a descriptor or a PSBT.

**Comment by tonyguesswho** [comment]
hey @darosior , Is this still open? I would like to work on this.

**Comment by darosior** [comment]
Hey. Thanks for your interest. @edouardparis has been working on this in https://github.com/wizardsardine/liana/pull/340, but only for descriptor inputs. 

@edouardparis do you think @tonyguesswho could start from your branch and apply this to all inputs, not only for descriptors? If so would you have a tip for them to do that in a general fashion? (I mean without having to copy paste the trimming code everywhere there is a text input.)

**Comment by delta1** [comment]
> would you have a tip for them to do that in a general fashion 

I'd recommend creating a new type like `Trimmed` that uses the type system to guarantee that creating the type ensures that it is trimmed. So for example the `Trimmed` type would be a newtype over `String`, and  the `Trimmed::new` function takes in a `String`, calls `trim` and returns the new type. 

Of course naming is the hard part so choose as you please :)

**Comment by darosior** [comment]
@tonyguesswho assigning you to this issue. Please let me know if you lose interest in working on this.

**Comment by darosior** [comment]
@tonyguesswho are you still working on this?

**Comment by kloaec** [comment]
This issue is also present in other input fields such as Addresses.
The fix should cover all input fields where a space or "return" begins or ends the field.

**Comment by jp1ac4** [comment]
Could this be done in a general way by using something like `form::Value<Trimmed>` instead of `form::Value<String>` for relevant input fields, where `Trimmed` would be the new type described above?

**Comment by edouardparis** [comment]
Yes, It is a good idea to have it a second type or add it as a method to the Form struct.
All the forms expect the ones concerning fingerprints labels and the new labels feature, require to have the inputs trimmed.

**Comment by jp1ac4** [comment]
That sounds good thanks. I could try working on this issue.
