### ISSUE TITLE
GUI: have a unique ID in the name of wallet imported on signing devices

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#324]
We currently always name it "Liana". It may lead to confusion on the device's screen if multiple Liana descriptors are imported there.

**Comment by kloaec** [comment]
Not sure if it impacts Core for the future Multi-Account feature as well, but i would guess it does.

**Comment by darosior** [comment]
I think on the Bitcoin Core side if we were to support multiple wallets we'd just import the descriptors in a single watchonly wallet.

Reminds me i need to fix this btw https://github.com/wizardsardine/liana/blob/e4d4fcd9fc13b33ee89be0662bab5107fd8493c4/src/bitcoin/mod.rs#L132-L137

**Comment by darosior** [comment]
@edouardparis i think this was implemented along with the Bitbox support? Can we close this isssue? Or maybe it's specific to the Bitbox.
