### ISSUE TITLE
Sats separator when displaying balance?

### ISSUE THREAD

**Issue by alexwaltz** [wizardsardine/liana#331]
Most of the amounts in "normal" users' wallets are going to be _zero point something bitcoins_, which makes it pretty hard to all digits crammed up together, especially when you have more TXs in the wallet

![Liana - Balances crammed up](https://user-images.githubusercontent.com/92048497/217060523-6c460f58-223f-451f-aae7-053504d16813.png)

Outside of Bitcoin, we solved this problem by adding a separator in the thousands 100,000 - one hundred thousand.

Why not have a separator for values <1?
₿0.00 271  828

The space separator is best, as it avoids confusion with , or .
Also is pretty unintrusive it may even get noticed.

Tradeoff - you have a space when you copy the value.

This is already used in the [JAM app](https://jamdocs.org/)
<img width="782" alt="Screenshot 2023-02-06 at 18 47 42" src="https://user-images.githubusercontent.com/92048497/217059089-64d21f5f-c273-4c85-bff1-a2a3604257c8.png">

**Comment by edouardparis** [comment]
Hello, thank you for your interest in the project. 
We totally agree with this design guideline and I am happy to answer that an equivalent change was done for `0.2-rc`.
![image](https://user-images.githubusercontent.com/6933020/217187624-18556348-0c59-4f9f-a085-e297bb1d5d1a.png)

**Comment by darosior** [comment]
This is now part of the 0.2 release. I think this can be closed. Feel free to re-open if you think something is still unaddressed.

PS: i didn't know about Jam. Looks cool.
