### ISSUE TITLE
GUI: Crash reports in log file

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#338]
We get a lot of crash reports from not, or less, technical users. Especially on non-Linux system. In many cases we don't have logs, which makes debugging tedious and time consuming.

If running the daemon, logs are written to a file in the datadir. In case of a panic, the backtrace is harvested through a panic hook and logged before stopping the process:
https://github.com/wizardsardine/liana/blob/579c4288251fedadecf837f52bb83d7e3797a785/src/lib.rs#L33-L64

It seems that when running the GUI there no log at all by default. Am i correct @edouardparis? We should log to a file continuously, and catch the backtrace in case of panic as we do in the daemon.

Thoughts? IMO it's a main priority for the next release.

**Comment by kloaec** [comment]
It will help. Also maybe more verbosity for RC versions by default?

**Comment by darosior** [comment]
Unfortunately this will have to slip to the next release..
