### ISSUE TITLE
GUI: Label devices instead of displaying fingerprint when label is available

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#339]
It's annoying when dealing with multiple similar devices to have to remember the fingerprint of which is which, when saving descriptors, signing, etc.

The issue is exacerbated by the current lack of support for multiple Ledger devices connected at the same time. I would like to know which is recognized, i might think it's the one I have in hand when it's actually the other one being "seen".

**Comment by darosior** [comment]
Where does the GUI not display the alias set? I though it was always displayed.

cc @edouardparis

**Comment by darosior** [comment]
Hmmm @edouardparis why did you mark this as completed via a402f85?

-------- Original Message --------

**Comment by edouardparis** [comment]
Yes !

**Comment by darosior** [comment]
Cool!
