### ISSUE TITLE
GUI: sanity check the value of `daemon` in lianad's config

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#348]
If the GUI tries to start a lianad that has `daemon = true` in its config it will get stuck in an apparent infinite loop until you kill it.

Sanity checking the lianad won't daemonize seems a trivial fix.

![image](https://user-images.githubusercontent.com/22457751/218428030-41e7ff61-dde4-43cd-a6aa-bafa9579b73c.png)

**Comment by darosior** [comment]
Now that we support connecting to the daemon via RPC, maybe it could start it as a daemon and connect via RPC instead of showing an error?

**Comment by pythcoiner** [comment]
just tested this:
- change `daemon=false` to `daemon=true` in daemon.toml
- Gui start well, no error

I close this issue, feel free to reopen if i miss something.
