### ISSUE TITLE
Couple `block_height` and `block_time` together in DB and Bitcoin interfaces

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#35]
In #29 we introduced the block time in addition to the block height in the `confirmed_coins` and `confirm_coins` result, as well as in the structures managing transaction (`GetTxRes` and `DbCoin` for instance).

Both fields are optional, but they should always either both be there or both not be. It would be cleaner to have a `BlockInfo` that itself is optional with `time` and `height` non-optional fields. So that we can avoid passing around confusing tuples, and avoid unwrapping on one field after we checked the other was present.

**Comment by darosior** [comment]
Part (but only part) of this was done in #63.

**Comment by darosior** [comment]
For instance an occurence is here https://github.com/revault/liana/blob/c98c520f06380e8d130d150ba2ce4573ed950919/src/database/mod.rs#L272-L276

**Comment by jp1ac4** [comment]
Hi @darosior, I'd be happy to work on this issue.

**Comment by darosior** [comment]
Hello @jp1ac4, sounds good!
