### ISSUE TITLE
Support for `rpcuser` / `rpcpassword` instead of cookie file auth for bitcoind RPC

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#356]
It was requested to me several times. I'd like to centralize the discussion in this issue.

Typically the situation where it could make sense is: you have a `bitcoind` running on your local network, and you'd rather reuse it instead of running another one on your laptop alongside Liana.

This is reasonable, however i think the usefulness of such a setup is overstated mainly due to 2 confusions:
1. It is *trivial* and *lightweight* to run bitcoind on your laptop. People still see `bitcoind` as a heavy process for some reason. You can trivially run a pruned bitcoind on your laptop. Once you've passed the IBD you'll barely notice it even on a low end machine. If you are not too concern about the bandwidth it's also the KISS solution to needing a bitcoind, instead of trying to over-optimize your setup so that all your process that need a bitcoind connect to a single box. 
2. The RPC interface is *not supposed to be accessed remotely*. Sure, it *might* be reasonable to connect to a box running bitcoind on your LAN. But then what, when you want to use your Liana wallet from outside your LAN you start doing SSH tunnels?... Meh. Back to step 1. It's over-optimization, just run `bitcoind` locally on your laptop and save yourself the configuration time and brain process.

Finally, sure, Electrum is an alternative. See https://github.com/wizardsardine/liana/issues/56. Ideally we'd have something like https://github.com/wizardsardine/liana/issues/101 and everybody wouldn't even notice they are running a full node locally.

**Comment by vincenzopalazzo** [comment]
Ok, your approach makes total sense to me.

I also need to access my remote machine with `user` and `password`, but I can run a bitcoind and connect only to my remote instances as well.

However, the syncing time can be a problem, so it would be great to have a fallback backend that allows me to work with the wallet and switch to Bitcoin when it is ready.

For the core lightning plugin, I have designed it in a way that when the bitcoind are in pruning mode or syncing, it will fetch the block from the network directly or with the nakamoto implementation (a fork of it). I have implemented this design in the following repository: https://github.com/coffee-tools/folgore.

It would also be helpful to have a similar design with liana and use a pure bitcoind backend, along with another pure Bitcoin backend for faster startup and not have electrum-like solution.

**Comment by darosior** [comment]
> However, the syncing time can be a problem, so it would be great to have a fallback backend that allows me to work with the wallet and switch to Bitcoin when it is ready.

Yeah i think the cleanest way forward for this is just to wait for assumeutxo. I'm hopeful we can have it by version 26 of Bitcoin Core.

See https://github.com/wizardsardine/liana/issues/101 for assumeutxo.

-------- Original Message --------

**Comment by vincenzopalazzo** [comment]
Oh, I am new to the `assumeutxo` I need to take a look thanks for sharing, there is any ongoing work in the bitcoin core regarding this?

**Comment by darosior** [comment]
Yes there is a link to the project in #101.
------- Original Message -------

**Comment by cbergqvist** [comment]
Leaving a vote for implementing this. People bought/built their Raspberry Pis and want to use them. Please consider either adding support for `rpcuser` / `rpcpassword` and ideally Tor, or integrate an SPV client into the Liana daemon. Keep the number of moving parts down for the user, especially if this wallet is meant to be usable by novices in multisig inheritance situations.

**Comment by kornpow** [comment]
I would also like to use `rpcuser` and `rpcpassword`. I get that it is really easy to run a signet node locally and have it sync super quickly, but for a lot of people they dont want to run it locally. Im trying to connect Liana to a remote MutinyNet (signet) and I dont want to have to set it up on my own machine.

**Comment by kdmukai** [comment]
For my "production" level home infra I'm running bitcoind in its own VM in Proxmox. Fulcrum: its own VM. Local mempool.space, Tor proxy, Specter Desktop, SeedSigner OS build environment, etc, etc all separated.

Any local bitcoind instance is taken up and down in regtest as needed. And even that I might set up as its own regtest bitcoind VM.

I'm writing this from TABConf where I've been tethering from my phone the last two days since there's no conference wifi. Who knows what my data overage charges will be. If I wanted to use Liana on mainnet and but had to start syncing a local node... forget it.

"cookie-only" is just an unnecessary hill to die on.

Let me run my infra the way that makes the most sense for me.

**Comment by darosior** [comment]
Given the level of support for this feature, i'm considering it for the next release (v5). Note however we should be using `-rpcauth` and not `-rpcuser`/`-rpcpassword` which have been deprecated for more than 8 years (!) now.

**Comment by kornpow** [comment]
Your terms are acceptable, excited to hear it. I do use `rpcauth` in my bitcoind config. But from the perspective of Liana, we are still passing it a username and password.

**Comment by darosior** [comment]
Closing this as https://github.com/wizardsardine/liana/pull/898 was merged which implements the possibility to auhenticate to `bitcoind` using username and password.

![image](https://github.com/wizardsardine/liana/assets/22457751/73b59002-7df0-4e39-b28c-ae636a334b5a)

**Comment by vincenzopalazzo** [comment]
uuuuh thanks @darosior this is really good

**Comment by darosior** [comment]
As @pythcoiner notes elsewhere this would be awkward to use without a change to how the watchonly wallet is stored. See https://github.com/wizardsardine/liana/issues/1059#issuecomment-2024875956.

**Comment by vincenzopalazzo** [comment]
Yesh it does @darosior 

Maybe improve the tracking of the wallet will help solo to move forward the nakamoto implementation
