### ISSUE TITLE
Spending error: "Hardware Wallet Error: status: IncorrectData"

### ISSUE THREAD

**Issue by Rob1Ham** [wizardsardine/liana#368]
Last night I set up a simple wallet with Liana, to try the recovery key path this morning after the timelock expired (5 blocks).

Here is my output desriptor:

```wsh(or_d(pk([63e37526/48'/0'/0'/2']xpub6Dz9nV9XNXtUxnSjtV5PUeVRxyVos5Zt6eDigMJpizeopHgFhwaNZRGDzAUDpEz8MFPikwR64MBy1dnRv2aZ9uiHoHZU5kZASWitLZKExx7/<0;1>/*),and_v(v:pkh([3758427a/48'/0'/0'/2']xpub6EXDAYGutqkCad7ybQBRe6x8x4VFdexcHT2bV6WUG7B2xs19KPAwaBUCTbkkFQwkuo3mr2jjHN4kcNMsMPrFSj5VmQWNVwdxgoA5Xeqg3Zr/<0;1>/*),older(5))))#6nh3cmyr```

Upon attempting to spend this morning though, for both my primary key and my recovery key (both ledgers), I get an error which prevents me from spending.

Here is a copy of the PSBT:

```cHNidP8BAF4CAAAAAS6KZ3qpJYjocqt/rq8ai4r9ArwxaTRfBIrVyOpPUmuOAQAAAAD9////AUwdAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQAAAAAAAEA/RcBAgAAAAABAf8khSdSRzMGY7al0Ws15vCIIYKS2w30bQMe1d6QTqWRAQAAAAD9////AiQnAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQXIgAAAAAAACIAINGTLG0VZ+5fE0Y45F6zHgbJ+UkG6snueieJdz4D1/o+AkgwRQIhAOUp6YDF3M8C5uZn5vPRzmziZ8EAStRXWx7ShNdmxNu8AiBQpzXn18sd+aJKsnP+Gk2hBm10JsiguxepmsBS20uFfwFBIQP9TJIM1YzF8L68FxLJaS3mYgRg0gJTv4WeCN+CHmJHm6xzZHapFJHu2m6JocFIkGLIgUKYN4VWpJKAiK1VsmgAAAAAAQErFyIAAAAAAAAiACDRkyxtFWfuXxNGOOResx4GyflJBurJ7noniXc+A9f6PgEFQSEC2jXO/6/bVaVr8Ktp8PcqssiyK+jdS/eg6UHLv1eAp6esc2R2qRSwHLw3v8tkEeHpZcJplZtEo/0VnYitVbJoIgYCu+Rg4+DH8/r9791qk6WGKQmts4Ybv/X9QONLWvcIK/4cN1hCejAAAIAAAACAAAAAgAIAAIABAAAAAQAAACIGAto1zv+v21Wla/CrafD3KrLIsivo3Uv3oOlBy79XgKenHGPjdSYwAACAAAAAgAAAAIACAACAAQAAAAEAAAAAAA==```

This is the error I get when attempting to spend through the original key path:

![image](https://user-images.githubusercontent.com/6456095/225922118-db1a2140-e7a1-4952-a101-17752cef6e77.png)

When I attempt to use the recovery path, I get the same error, here is that PSBT for reference:

```
cHNidP8BAF4CAAAAAS6KZ3qpJYjocqt/rq8ai4r9ArwxaTRfBIrVyOpPUmuOAQAAAAAFAAAAAdUeAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQAAAAAAAEA/RcBAgAAAAABAf8khSdSRzMGY7al0Ws15vCIIYKS2w30bQMe1d6QTqWRAQAAAAD9////AiQnAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQXIgAAAAAAACIAINGTLG0VZ+5fE0Y45F6zHgbJ+UkG6snueieJdz4D1/o+AkgwRQIhAOUp6YDF3M8C5uZn5vPRzmziZ8EAStRXWx7ShNdmxNu8AiBQpzXn18sd+aJKsnP+Gk2hBm10JsiguxepmsBS20uFfwFBIQP9TJIM1YzF8L68FxLJaS3mYgRg0gJTv4WeCN+CHmJHm6xzZHapFJHu2m6JocFIkGLIgUKYN4VWpJKAiK1VsmgAAAAAAQErFyIAAAAAAAAiACDRkyxtFWfuXxNGOOResx4GyflJBurJ7noniXc+A9f6PgEFQSEC2jXO/6/bVaVr8Ktp8PcqssiyK+jdS/eg6UHLv1eAp6esc2R2qRSwHLw3v8tkEeHpZcJplZtEo/0VnYitVbJoIgYCu+Rg4+DH8/r9791qk6WGKQmts4Ybv/X9QONLWvcIK/4cN1hCejAAAIAAAACAAAAAgAIAAIABAAAAAQAAACIGAto1zv+v21Wla/CrafD3KrLIsivo3Uv3oOlBy79XgKenHGPjdSYwAACAAAAAgAAAAIACAACAAQAAAAEAAAAAAA==
```

This error is present for both primary and recovery key paths, as well as if trying to spend using the recovery feature or the default spend path.

```
Device {
    command: 4,
    status: IncorrectData,
}
```

I went to sign the non-recovery PSBT manually using ledger's bitcoin_client_rs library with the command:

```
cargo run --package ledger_hwi -- \
sign --psbt \
"cHNidP8BAF4CAAAAAS6KZ3qpJYjocqt/rq8ai4r9ArwxaTRfBIrVyOpPUmuOAQAAAAD9////AUwdAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQAAAAAAAEA/RcBAgAAAAABAf8khSdSRzMGY7al0Ws15vCIIYKS2w30bQMe1d6QTqWRAQAAAAD9////AiQnAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQXIgAAAAAAACIAINGTLG0VZ+5fE0Y45F6zHgbJ+UkG6snueieJdz4D1/o+AkgwRQIhAOUp6YDF3M8C5uZn5vPRzmziZ8EAStRXWx7ShNdmxNu8AiBQpzXn18sd+aJKsnP+Gk2hBm10JsiguxepmsBS20uFfwFBIQP9TJIM1YzF8L68FxLJaS3mYgRg0gJTv4WeCN+CHmJHm6xzZHapFJHu2m6JocFIkGLIgUKYN4VWpJKAiK1VsmgAAAAAAQErFyIAAAAAAAAiACDRkyxtFWfuXxNGOOResx4GyflJBurJ7noniXc+A9f6PgEFQSEC2jXO/6/bVaVr8Ktp8PcqssiyK+jdS/eg6UHLv1eAp6esc2R2qRSwHLw3v8tkEeHpZcJplZtEo/0VnYitVbJoIgYCu+Rg4+DH8/r9791qk6WGKQmts4Ybv/X9QONLWvcIK/4cN1hCejAAAIAAAACAAAAAgAIAAIABAAAAAQAAACIGAto1zv+v21Wla/CrafD3KrLIsivo3Uv3oOlBy79XgKenHGPjdSYwAACAAAAAgAAAAIACAACAAQAAAAEAAAAAAA==" \
--name "Liana" --policy "wsh(or_d(pk([63e37526/48'/0'/0'/2']xpub6Dz9nV9XNXtUxnSjtV5PUeVRxyVos5Zt6eDigMJpizeopHgFhwaNZRGDzAUDpEz8MFPikwR64MBy1dnRv2aZ9uiHoHZU5kZASWitLZKExx7/<0;1>/*),and_v(v:pkh([3758427a/48'/0'/0'/2']xpub6EXDAYGutqkCad7ybQBRe6x8x4VFdexcHT2bV6WUG7B2xs19KPAwaBUCTbkkFQwkuo3mr2jjHN4kcNMsMPrFSj5VmQWNVwdxgoA5Xeqg3Zr/<0;1>/*),older(5))))" \
--hmac "6eca7963282ae398283ab82d0a1bdb347025a63ac120b64b3309fcb11e162b96"
```

and was able to get it to sign, with this output:

```
BVGbONrnREe3IVHzVMsTjKNZGl/4rIEyibGKAE4xMhYgbQ0+eDkmpT8aaW8ElE4DvENEDPR2hNmpWemNKt2FEPE=
1
DPh5BdJMa4lZekilcF/yHhfqVjK3MzfpDT+bDzhoEn8=
1
rrk8v/X6NGC96bVw8Ks311PJLneyQ0YYUmBUQxu0CEc=
Done!...



Writing...



BVGbONrnREe3IVHzVMsTjKNZGl/4rIEyibGKAE4xMhYgbQ0+eDkmpT8aaW8ElE4DvENEDPR2hNmpWemNKt2FEPEBDPh5BdJMa4lZekilcF/yHhfqVjK3MzfpDT+bDzhoEn8Brrk8v/X6NGC96bVw8Ks311PJLneyQ0YYUmBUQxu0CEe1M95lYMonASDIQP9OFW0+o3b/ClCnCHBlK72Xd0Hi627KeWMoKuOYKDq4LQob2zRwJaY6wSC2SzMJ/LEeFiuW
Wrote!
index: 0, key: 02da35ceffafdb55a56bf0ab69f0f72ab2c8b22be8dd4bf7a0e941cbbf5780a7a7, sig: 304402200dc8b4575b7fc025151472824f9f7db7be187943569b8f3bdf533083f7925a2e022051812d7372d19c845e2042c53ff43d04b6dccb8af8283a8f702caee2a1e3fe3001

```

I then took this output and updated the PSBT to:

```
cHNidP8BAF4CAAAAAS6KZ3qpJYjocqt/rq8ai4r9ArwxaTRfBIrVyOpPUmuOAQAAAAD9////AUwdAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQAAAAAAAEA/RcBAgAAAAABAf8khSdSRzMGY7al0Ws15vCIIYKS2w30bQMe1d6QTqWRAQAAAAD9////AiQnAAAAAAAAIgAgIdzMrAWMrxEkkKo0s7bQwM51pzz7Fb6hLAmx/vRsCoQXIgAAAAAAACIAINGTLG0VZ+5fE0Y45F6zHgbJ+UkG6snueieJdz4D1/o+AkgwRQIhAOUp6YDF3M8C5uZn5vPRzmziZ8EAStRXWx7ShNdmxNu8AiBQpzXn18sd+aJKsnP+Gk2hBm10JsiguxepmsBS20uFfwFBIQP9TJIM1YzF8L68FxLJaS3mYgRg0gJTv4WeCN+CHmJHm6xzZHapFJHu2m6JocFIkGLIgUKYN4VWpJKAiK1VsmgAAAAAAQErFyIAAAAAAAAiACDRkyxtFWfuXxNGOOResx4GyflJBurJ7noniXc+A9f6PiICAto1zv+v21Wla/CrafD3KrLIsivo3Uv3oOlBy79XgKenRzBEAiANyLRXW3/AJRUUcoJPn323vhh5Q1abjzvfUzCD95JaLgIgUYEtc3LRnIReIELFP/Q9BLbcy4r4KDqPcCyu4qHj/jABAQVBIQLaNc7/r9tVpWvwq2nw9yqyyLIr6N1L96DpQcu/V4Cnp6xzZHapFLAcvDe/y2QR4ellwmmVm0Sj/RWdiK1VsmgiBgK75GDj4Mfz+v3v3WqTpYYpCa2zhhu/9f1A40ta9wgr/hw3WEJ6MAAAgAAAAIAAAACAAgAAgAEAAAABAAAAIgYC2jXO/6/bVaVr8Ktp8PcqssiyK+jdS/eg6UHLv1eAp6ccY+N1JjAAAIAAAACAAAAAgAIAAIABAAAAAQAAAAAA
```

and was able to finalize the PSBT with this tx hex (haven't broadcasted it though):

```
020000000001012e8a677aa92588e872ab7faeaf1a8b8afd02bc3169345f048ad5c8ea4f526b8e0100000000fdffffff014c1d00000000000022002021dcccac058caf112490aa34b3b6d0c0ce75a73cfb15bea12c09b1fef46c0a840247304402200dc8b4575b7fc025151472824f9f7db7be187943569b8f3bdf533083f7925a2e022051812d7372d19c845e2042c53ff43d04b6dccb8af8283a8f702caee2a1e3fe3001412102da35ceffafdb55a56bf0ab69f0f72ab2c8b22be8dd4bf7a0e941cbbf5780a7a7ac736476a914b01cbc37bfcb6411e1e965c269959b44a3fd159d88ad55b26800000000
```

So it appears a bug with the GUI interacting with ledger which prevents this from being signed, even though it is a valid PSBT & output descriptor.

**Comment by Rob1Ham** [comment]
Hey @edouardparis , looking at my files right now, I don't even have a `~/.liana` directory. I was clicking through settings last night and setting up different wallets for testing, is it possible that filepath was deleted at some point?

Since I had previously registered the wallets, I skipped over this prompt:

![image](https://user-images.githubusercontent.com/6456095/225934025-6e25abdc-5265-4a61-b3ea-cd89f48d0431.png)


I wasn't aware that I'd have to re-regster the ledgers if I had already previously done the registration for the same output descriptor/ledgers.

Going through the whole flow again and re-registering the ledgers, it now worked as intended. Thanks for the help!

**Comment by darosior** [comment]
@edouardparis yeah it would be helpful to have a warning if a signer isn't registered when trying to sign. Opened https://github.com/wizardsardine/liana/issues/369 to track this.

I think this can be closed, feel free to reopen if something was left unaddressed.
