### ISSUE TITLE
Merge redundant code in `spent_coins`

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#37]
The code to get an entry from the cache is redundant and could be made into an inline function.

**Comment by darosior** [comment]
https://github.com/revault/liana/blob/c98c520f06380e8d130d150ba2ce4573ed950919/src/bitcoin/mod.rs#L220-L227

And

https://github.com/revault/liana/blob/c98c520f06380e8d130d150ba2ce4573ed950919/src/bitcoin/mod.rs#L238-L245

**Comment by pythcoiner** [comment]
it have been addressed in 62c4b9a01c16c60f66db99abab967efa4e0429dd, I close.
