### ISSUE TITLE
"Rotate your coins" on homepage

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#370]
Have a button on the homepage if some coins are close to expire that creates a send-to-self transaction with all those coins.

**Comment by kloaec** [comment]
Duplicate or at least related to https://github.com/wizardsardine/liana/issues/192

The process of already creating the tx without user involvement (except signing) is good IMHO

**Comment by darosior** [comment]
Oh, right. Thanks. :facepalm:
