### ISSUE TITLE
Signing fails if another process has an open connection with a Ledger. Maybe have a hint about it in the error?

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#381]
![image](https://user-images.githubusercontent.com/22457751/227725912-623b25ab-041a-4426-b533-06075c89fa36.png)

**Comment by darosior** [comment]
Same error on master
![image](https://user-images.githubusercontent.com/22457751/227726250-a6eb8c3e-e782-45d8-8757-a687fc73e403.png)

**Comment by darosior** [comment]
I'm just retarded: i had another wallet opened with the connection. Would be nice to have a hint in the error?

**Comment by darosior** [comment]
Or instead of hinting at it maybe we could fix it? Can't there be multiple connections opened to a signing device at once?

**Comment by darosior** [comment]
@pythcoiner encountered the same issue but this time it gave a different error
![image](https://github.com/wizardsardine/liana/assets/22457751/4a583839-46a4-4e73-a108-694e3cfd5340)

**Comment by pythcoiner** [comment]
i got 2 different errors using async-hwi:
 - Error: Device("Transport(\n Hid(\n HidApiError {\n message: \"hid_read_timeout: unexpected poll error (device disconnected)\",\n },\n ),\n)")
 - Error: Device("Transport(\n Hid(\n HidApiError {\n message: \"Cannot send after transport endpoint shutdown\",\n },\n ),\n)")
 
 I think the messages have been more detailled from the first time you encountered this issue.

**Comment by edouardparis** [comment]
> Can't there be multiple connections opened to a signing device at once?

Sadly I just tried with a ledger and multiple connections can be opened, even weirder the new connection is listening to the result of the first connection and gets its result which triggers then an error as the result was not the one expected.
I guess the root cause is the way of how the HID interface works and I have no way with my current knowledge to fix that.
I will dig more on it but a hint in the error would be a first good step.

**Comment by edouardparis** [comment]
[

![Image](https://github.com/wizardsardine/liana/assets/6933020/30fe1f94-082b-4f6c-984b-6c4cce6abce1)

](url)

**Comment by darosior** [comment]
Thanks for looking into this. Let's have a useful warning hinting at this issue upon a recognizable error.
