### ISSUE TITLE
Conflicting transaction shown in home

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#382]
![image](https://user-images.githubusercontent.com/22457751/227767450-9c34ba1c-8afd-4d31-a3ef-1e43e9f9a801.png)

I need to look into whether it resolves itself or we keep serving transactions that aren't in our mempool until the other gets confirmed.

**Comment by kloaec** [comment]
(in this screen, the first and last tx are conflicting. They are spending the same UTXO, but one was send from this PC, when another one was already broadcast from another PC)

**Comment by darosior** [comment]
Thanks for the context.

I'm pretty sure it wouldn't stay that way but i need to check.
