### ISSUE TITLE
Installer: do not make them check device registration of the descriptor if there is no device

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#400]
It keeps confusing people that use the wallet without a signing device.

**Comment by jp1ac4** [comment]
Hi @darosior, I could try working on this one.

**Comment by jp1ac4** [comment]
Do you have in mind something like the following?
```diff
diff --git a/gui/src/installer/view.rs b/gui/src/installer/view.rs
index 476fbdf..e9b85d8 100644
--- a/gui/src/installer/view.rs
+++ b/gui/src/installer/view.rs
@@ -695,7 +695,11 @@ pub fn register_descriptor<'a>(
                     .width(Length::Fill),
             )
             .push(checkbox(
-                "I have registered the descriptor on my device(s)",
+                if hws.is_empty() {
+                    "I do not wish to register the descriptor on a device"
+                } else {
+                    "I have registered the descriptor on my device(s)"
+                },
                 done,
                 Message::UserActionDone,
             ))
```
This seems to work nicely, although in case a device is connected it takes a second or two for the correct text to be displayed.

**Comment by darosior** [comment]
I think we shouldn't display the registration step at all if only hot keys were used. As to how to actually perform this check @edouardparis would know better.

**Comment by darosior** [comment]
Also @jp1ac4 i'd like to send you an email. I assume it's on purpose the one you've been using here is Github's no-reply. So i'm resorting to contact you through the issues haha. :)

If you're fine with that could you send a mail to antoine@wizardsardine.com?

**Comment by edouardparis** [comment]
This one will be not easy:
When the xpubs are retrieved from hardware wallet in the xpub modal and their fingerprints are stored in the installer context, then we should also store if the xpub is from an hardware wallet or not, then use the trait method `skip(&self, &Context)->bool` for the registration step to return true if no harware wallet was used.

**Comment by jp1ac4** [comment]
OK thanks, I'll see if I can get that working.

**Comment by jp1ac4** [comment]
Hi @edouardparis, would you suggest to add a field to the `KeySetting` struct and store this in `context.keys`?

**Comment by edouardparis** [comment]
Maybe not in the struct because we do not want to serialize it in settings.json , but use change the field as a tuple like this:
`pub keys: Vec<KeySetting, Option<DeviceKind>>`

**Comment by jp1ac4** [comment]
Thanks, @edouardparis, I'll give this a try.

**Comment by jp1ac4** [comment]
Hi @edouardparis, would it be possible to use a `bool` instead of `DeviceKind` to indicate if a hardware wallet is used? The logic would be similar to how `signer_is_used` is currently being set (`master_fingerprint == self.signer.fingerprint()`). I didn't manage to find a straightforward way to get the `DeviceKind` value, but I might be missing something. Thanks.

**Comment by edouardparis** [comment]
I am sorry this issue is kind of difficult and I hope in the future we could simplify all of this, but for the moment here is my opinion on how doing it:
 
The idea would be to store in the EditXpubModal the device kind when an hardware wallet is selected and remove it when hot_signer or the xpub text input is used, then pass it to the message::DefineKey::Edited
https://gist.github.com/edouardparis/f68b9c442540814398f33538e1c7e461
Then you will handle the message and certainly add the device_kind option to DescriptorKey, then in the apply check if some of the descriptorkey has a device_kind attached and store a bool in the context and then skip the step id the bool is false.

**Comment by jp1ac4** [comment]
Thanks, @edouardparis. I'll follow your suggested changes and will keep you posted.

I was also thinking it might be necessary to change the logic for `Installer::previous` so that it keeps track of any skipped steps, but not sure yet.

**Comment by jp1ac4** [comment]
Hi @edouardparis, regarding the `previous` logic, do you think the following approach could work:
```diff
diff --git a/gui/src/installer/mod.rs b/gui/src/installer/mod.rs
index 5e610e7..390b426 100644
--- a/gui/src/installer/mod.rs
+++ b/gui/src/installer/mod.rs
@@ -23,6 +23,7 @@ use step::{
 
 pub struct Installer {
     current: usize,
+    prev_steps: Vec<usize>,
     steps: Vec<Box<dyn Step>>,
 
     /// Context is data passed through each step.
@@ -31,8 +32,10 @@ pub struct Installer {
 
 impl Installer {
     fn previous(&mut self) {
-        if self.current > 0 {
-            self.current -= 1;
+        let current = self.current;
+        self.prev_steps.retain(|&p| p < current);
+        if let Some(prev_step) = self.prev_steps.iter().max() {
+            self.current = *prev_step;
         }
     }
 
@@ -43,6 +46,7 @@ impl Installer {
         (
             Installer {
                 current: 0,
+                prev_steps: vec![],
                 steps: vec![Welcome::default().into()],
                 context: Context::new(network, destination_path),
             },
@@ -63,6 +67,7 @@ impl Installer {
             .expect("There is always a step");
         if current_step.apply(&mut self.context) {
             if self.current < self.steps.len() - 1 {
+                self.prev_steps.push(self.current);
                 self.current += 1;
             }
             // skip the step according to the current context.

```
I've tested it going back and forth in the installer steps, changing from using a device to no device within the same installation, and the device registration step appears or not as expected. Thanks.

**Comment by edouardparis** [comment]
I think you can modify instead Installer::previous to skip the step while moving backward like Installer::next
see the code in installer/mod.rs Line 69
```rust
          // skip the step according to the current context.
            while self
                .steps
                .get(self.current)
                .expect("There is always a step")
                .skip(&self.context)
            {
                if self.current < self.steps.len() - 1 {
                    self.current += 1;
                }
            }
```

**Comment by jp1ac4** [comment]
Ah yes thanks, that's much better :)
