### ISSUE TITLE
RBF support for Spend transactions

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#43]
The biggest part is probably going to be the GUI's. Should we have a "bump fee" interface or a whole "replace by another Spend" interface?

**Comment by darosior** [comment]
I've made it part of the Minisafe v0 project and assigned the feature freeze milestone. But let's consider it a nice to have. If it slips to Minisafe v1 it's no big deal.

**Comment by darosior** [comment]
We won't have time to do this for v0.

**Comment by darosior** [comment]
I think this should take the form of:
1. A "bump fees" button
2. A "cancel" button

Also see the discussion in the duplicate #236.

**Comment by darosior** [comment]
Can't assign it to them using Github's feature for some reason but @jp1ac4 is going to take care of this. :rocket:

**Comment by jp1ac4** [comment]
Hi @darosior, as well as the "bump fees" and "cancel" buttons, would we also want an "enable RBF" toggle when creating a transaction? I see in https://github.com/wizardsardine/liana/blob/master/src/commands/mod.rs#L371 that RBF is currently always enabled.

**Comment by darosior** [comment]
Let's not have the option for now, i don't see any reasonable scenario where a user would disable it.

**Comment by jp1ac4** [comment]
OK yep that makes sense thanks.

Regarding bumping fees, do you think this should be done via the `bitcoin-cli bumpfee` command or should the replacement transaction be constructed manually as a new spend transaction?

**Comment by jp1ac4** [comment]
Yep, I think calling `createspend` with a higher feerate should work to begin with and then we can add checks to handle any special cases, e.g. if additional inputs are needed for the increased fee.

I tested this out a bit by broadcasting two transactions that differed only in the feerate. The higher feerate replaced the lower feerate as expected and the replaced PSBT was labelled as deprecated. (Conversely, when I broadcast the lower feerate after the higher feerate, which wouldn't be possible with the "bump fee" button, I got an error that the replacement was rejected due to insufficient fees.)

**Comment by darosior** [comment]
We also need to make sure the transaction has more fees (as in absolute fees, not feerate). See https://github.com/bitcoin/bitcoin/blob/master/doc/policy/mempool-replacements.md#current-replace-by-fee-policy for the replacement policy we need to make sure we respect.
-------- Original Message --------

**Comment by jp1ac4** [comment]
I was just testing a simple CLI command to bump fees and I noticed that possibly the `derivation_index_by_address` method isn't correctly flagging change addresses. If I use `.to_string()` as follows then it gives the value that I'm expecting:
```
self.db_address(address).map(|db_addr| {
            (
                db_addr.derivation_index,
                address.to_string() == db_addr.change_address.to_string(),
            )
        })
```
But I may be overlooking something?

**Comment by jp1ac4** [comment]
I think the problem was that the networks were different and these are also used in the comparison. I was testing on signet and had created an address using `self.config.bitcoin_config.network` as the network, which gave "signet", but the change address had network "testnet". I see this case is handled already in `validate_address` so I may have to do something similar although it's early days still.

**Comment by darosior** [comment]
Oh right the network serialization is the same for signet so PartialEq would fail between a signet and testnet address but no the serialization comparison.

By the way i think trying to work around `bumpfee` is a dead-end, it's pretty limited. For instance, iirc you can't change all outputs of a transaction to a single change output (to "Cancel").
------- Original Message -------

**Comment by jp1ac4** [comment]
> By the way i think trying to work around `bumpfee` is a dead-end, it's pretty limited. For instance, iirc you can't change all outputs of a transaction to a single change output (to "Cancel").

OK sure, I'll have a think about how best to approach it. My idea to begin with is to handle some simple cases via a CLI command and then see how to extend it to handle more complex cases. So far I'm using the transaction ID to recreate the original `createspend` arguments but with a higher fee rate.

**Comment by jp1ac4** [comment]
Hi @darosior, I've pushed some changes to this branch here: https://github.com/wizardsardine/liana/compare/master...jp1ac4:liana:add-rbf-support.

It still needs a lot of work, but you can get an idea of the approach I've taken so far. The `bumpfee` command attempts to recreate the transaction with a higher fee rate. My idea is then to add checks to make sure the replacement transaction meets the required criteria in the link you shared, and also make any changes required to the transaction, such as using additional inputs to cover the higher fee and adding a cancel option.

Please let me know if you think a different approach would be better.

**Comment by darosior** [comment]
It just occured to me that this work is tightly related to coin selection (https://github.com/wizardsardine/liana/issues/51)..

The algorithm i had in mind was we'd basically call `createspend` with an increasing feerate until all the criterions for replacements (link from above) would be met. But since `createspend` still needs all the outpoints to be provided this implies the caller has to do a coin selection.

To be honest i'm afraid this work is dependent on solving #51 first.

**Comment by jp1ac4** [comment]
The `create_spend` function has been updated in #560 to use either coin selection or specific outpoints. In order to use it for RBF purposes, I think we'll also need the following parameters:
- `min_fee: u64` - so that we can ensure the replacement transaction pays for original transactions.
- `use_additional: bool` - we need to call `createspend` with all the original coins (or at least one of them) in the `coins_outpoints` parameter and add additional coins if required to pay the higher fee. Currently, if we specify coins in `coins_outpoints`, only these coins are used in the transaction.
- `change_index: ChildNumber` ? - this one is only if we want to use the same change address in the replacement transaction.

Perhaps the `createspend` command itself won't need to have these additional parameters.

When checking total fees paid by original transactions, I think we can use bitcoin's `getmempoolentry` command to check both `descendantcount <= 100` and also to get the sum of fees paid by all descendants. Do you think it makes sense to add this to our bitcoin interface?

**Comment by darosior** [comment]
How about instead of adding all those parameters to the `createspend` command, we had a `rbfspend` command in the same fashion as `updatespend` or `broadcastspend`? We should probably name it `rbfpsbt` though, to make it clear it can be used for recovery txs as well.

This new command would take a txid and a feerate. It would fetch the PSBT from db, failing if it's not there or not yet broadcast. Determine whether it's got a change output from it and if so reused the same change address. Finally it would run the coin selection algorithm with all current inputs marked as mandatory (that's important when there is more than 1 RBF). Failing if it doesn't have sufficient funds. Then it would return the created PSBT without storing in DB in the same fashion as `createspend`.

Regarding the ancestor feerate of the transaction, i think it's important but also non trivial. We need to take into account for instance ancestor which were dropped from the mempool, or the size of the chain of unconfirmed transactions. We are already doing a bunch in this release so i would opt for implementing a more naive RBF which assumes all inputs are confirmed for now, and work on making it accurate for unconfirmed inputs in a second time (which may well be soon!).

**Comment by jp1ac4** [comment]
A new command for RBF makes sense. Do you think we'll need one command for bumping fees along the lines you describe and another for cancelling a transaction? The latter might need to remove all non-change outputs, for example, while the former would keep non-change outputs the same and possibly include additional inputs.

I think the new commands would need to reuse a lot of code from `create_spend` (such as creating the base transaction, fetching candidates from the DB and setting up the final PSBT), so we might want to extract some of that to a common utils function.

Using the terminlogy from https://github.com/bitcoin/bitcoin/blob/master/doc/policy/mempool-replacements.md#current-replace-by-fee-policy, my assumption for now is that the only directly conflicting transaction will be the `txid` we pass to the RBF command.

I think the `getmempoolentry` command calculates the descendant count (including descendants of descendants) and their total fees already, and from some quick tests it seemed to work this way. But for now I could assume that the transaction we are replacing has no descendants and in the worst case we would get an error when trying to broadcast it if the fees are not enough.

I haven't been considering any ancestors and their fees so far as I'm assuming any unconfirmed coins in the replacement spend would already be in the transaction we are replacing and any additional coins we include would be confirmed. From my understanding of the RBF policy, we only need to consider the fees of descendants when replacing a transaction.

**Comment by darosior** [comment]
@murchandamus pointed out to me something non-obvious about RBF. I already forgot it once, so gonna write it down here to keep a trace.

We need be careful if we ever allow adding new payments in a replacement transaction. There could be such a situation:
- Transaction `A` is created with (only) payment `x`
- Transaction `A` is RBF'd by transaction `A'` which includes an additional payment `y`
- Transaction `A` gets mined before the miner saw `A'`
- Transaction `B` is created to make payment `y` that the user is still willing to make
- The block in which Transaction `A` was mined is reorg and the miner which by now saw the higher fee-paying `A'` includes it instead
- The user made payment `y` twice :tada: 

Mark's suggestion would be to always add a new input when a payment is added in a replacement, and use this input as a source of conflict in a latter transaction which would make the same payment.

We don't have this issue (yet?) since we don't allow new payments to be created in replacements. But it's well worth keeping in mind. It's also IMO a good lesson to be conservative in our changes and only enable functionalities we thought through fully to avoid users shooting themselves in the foot.

**Comment by darosior** [comment]
> another for cancelling a transaction?

I think cancelling can be a parameter to `rbfpsbt`.

> extract some of that to a common utils function

Yes.

> I think the getmempoolentry command calculates the descendant count (including descendants of descendants) and their total fees already

Yes it does. For both ancestors and descendants. I think i replied assuming you were talking about unconfirmed ancestors, but this was already ruled out in https://github.com/wizardsardine/liana/pull/560#issuecomment-1784834125 right?

For descendants you are right using getmempoolentry seems like a low hanging fruit. If it's not found, we know it has no descendant. I think you should go for it.

> From my understanding of the RBF policy, we only need to consider the fees of descendants when replacing a transaction.

True, but the "real" feerate of the transaction is the feerate of the transaction plus its ancestors. But yes let's set that aside for now.

**Comment by darosior** [comment]
No, to satisfy the RBF rules you need to make sure the individual transaction's feerate is 1sat/vb greater than the replaced one. The ancestor feerate is only considered by miners. It's important too as it may be lower than the individual tx feerate. Basically what we are interested in is `max(individual feerate, ancestor feerate)`. I know it's confusing, that's because the RBF rules were implemented before ancestor-awareness in Bitcoin Core.

**Comment by darosior** [comment]
Regarding the implementation in the GUI, i'm thinking about the following.

In the transaction details, when clicking on an unconfirmed transaction.
![image](https://github.com/wizardsardine/liana/assets/22457751/251ab6df-1401-498c-b11b-0de138e5ab82)
Right below the fees and before the txid, have a new row with two buttons:
- Bump fees
- Cancel (with a tooltip "Best effort attempt at double spending an unconfirmed outgoing transaction")

Both buttons open a modal, with the same title in both cases: "Transaction replacement". The content itself depends on the chosen option:
- For Cancel, have a small text and a "Confirm" button. "Replace the transaction with one sending the coins back to us. There is no guarantee the original transaction won't get mined first. New inputs may be used for the replacement transaction."
- For Bump, have a small text, an input for the new feerate and a "Confirm" button. Any error may be shown right between the feerate input and the "Confirm" button. The text may be "Replace the transaction with one paying a higher feerate, to incentivize faster confirmation. New inputs may be used for the replacement transaction."

What do you think? @kloaec @jp1ac4

There is also the question of the labeling. This should be tackled separately. I'll open a separate issue to discuss this.

**Comment by kloaec** [comment]
Seems good for the transaction screen. We also need it on the "payment" view from the home screen.

The modal text is pretty good like @darosior suggested.
- For the cancel popup, i would add "with a higher fee rate" or a additional sentence with "It stills costs a Bitcoin transaction fee"
- in both Bump and Cancel, if possible, I would like to clearly display if new inputs are added, or not. Can this be done without too much work? Replacing the "new inputs may be used" by "no new inputs are used" or "/!\ new inputs are used" depending on the selected fee.

**Comment by jp1ac4** [comment]
It sounds good with the two buttons and modal on the transaction details screen. Would clicking "Confirm" then take the user to the PSBT screen?

If we keep track of the to-be-replaced txid while finalizing the replacement PSBT, I think we could check if the inputs have changed.

**Comment by darosior** [comment]
> Would clicking "Confirm" then take the user to the PSBT screen?

Yes, for the user to sign the tx.

**Comment by jp1ac4** [comment]
Regarding the placement of the buttons, another option would be on the same row where the date is shown. Currently, the date row is hidden if the transaction is unconfirmed, but nothing else on the page says the transaction is unconfirmed so perhaps the date could be shown as "Unconfirmed" and alongside it would be the two buttons.

**Comment by darosior** [comment]
Sounds good to display Unconfirmed. Kevin had pointed this out to me as well.
