### ISSUE TITLE
"Failed to register descriptor" message when get HidApiError{message: "success",}

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#450]
I was trying v0.4, then, at step for register descriptor on hardware wallet i get "Failed to register descriptor" message when getting => `Hardware Wallet: Transport(HID(HidApiError{message: "success",},),)`

I Guess is just about mislabeling.

(HW is Ledger nano S plus with 2.1.1 Firmware)

![image](https://user-images.githubusercontent.com/124568858/232339367-8c05cf80-79a6-447e-93a9-7c71749057ca.png)

I don't know how to check on the HW whether descriptor have been registered well or not.

**Comment by edouardparis** [comment]
Thank you for reporting the bug.
I successfully reproduced the error by disconnecting my ledger while registering the policy.
Hidapi is the library handling the communication between the GUI and the ledger, if an error is returned it means that the GUI failed to communicate with the device and failed to register the policy.
I agree that the `success` message is confusing and the interface should handle the hidapi error and provide a user-friendly message instead.

FYI: ledger does not store anywhere a policy in its memory, it will only provide the client an hmac attesting that the user did check the policy on the ledger screen and it is the role of the client to provide this hmac and the policy in all the future interactions with the device.

**Comment by pythcoiner** [comment]
ok so if i understand well, the purpose of the hmac is only to testify that the user have already check the policy so user don't need to recheck policy at every interaction, right?

**Comment by edouardparis** [comment]
Yes, exactly ! It is the reason we added the warning: `Registration is not a substitute for backing up the descriptor`, so user does not reset his laptop without having a proper backup thinking the hardware wallet has it.

**Comment by pythcoiner** [comment]
ok, just find out the way in settings for register policy, maybe it can be useful to inform user at the error time the steps to follow?
`[settings > wallet > Register on hardware wallet]`

**Comment by darosior** [comment]
Anything left to do here?

**Comment by pythcoiner** [comment]
let me have a try

**Comment by pythcoiner** [comment]
![image](https://github.com/wizardsardine/liana/assets/124568858/e882a75a-701a-4989-b5d4-af9c765b6f41)

new hint is clear, i close
