### ISSUE TITLE
UX/GUI: add renew/rotate/selfspend button in the Coins (utxo) window

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#471]
I think it can be useful to have a function for self spending coins, maybe checkboxes on every coin lines and one button for trigger the spending process?

**Comment by darosior** [comment]
Yes, this is what https://github.com/wizardsardine/liana/issues/371 is about. :)

**Comment by darosior** [comment]
We're also planning on having a "refresh all coins that are close to expiry". That's https://github.com/wizardsardine/liana/issues/192.

**Comment by darosior** [comment]
Closing as duplicate of #371.
