### ISSUE TITLE
GUI: Reduce the number of payments shown on home to 10

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#474]
See https://github.com/wizardsardine/liana/issues/459#issuecomment-1531473299

**Comment by pythcoiner** [comment]
I take a (quick) look into this:

https://github.com/wizardsardine/liana/blob/903328ffef8317b1f152633ac671ecd92071d8eb/gui/src/app/view/home.rs#L25

Here changing `HISTORY_EVENT_PAGE_SIZE` dont behave as expected, for instance w/ an history of 15 payments and `HISTORY_EVENT_PAGE_SIZE=10` i got only 6 payments displayed....

also i think it is a nit but `pending_events` types are differents in caller and callee:

https://github.com/wizardsardine/liana/blob/903328ffef8317b1f152633ac671ecd92071d8eb/gui/src/app/state/mod.rs#L65-L66

https://github.com/wizardsardine/liana/blob/903328ffef8317b1f152633ac671ecd92071d8eb/gui/src/app/view/home.rs#L32-L33

**Comment by pythcoiner** [comment]
there is something weird in the way we select the quantity of displayed coins, i actually have 1000 coins in my test wallet and there are around 100 or so displayed in home `Last payments` (instead of max 20 in theory)

**Comment by darosior** [comment]
> there is something weird in the way we select the quantity of displayed coins, i actually have 1000 coins in my test wallet and there are around 100 or so displayed in home `Last payments` (instead of max 20 in theory)

I believe this is because the 20 limit actually is applied to transactions, not payments? cc @edouardparis.

**Comment by edouardparis** [comment]
Do they have all the same block time ? In this case, we cannot paginate and the gui will ask for a larger batch of transactions.

**Comment by pythcoiner** [comment]
> Do they have all the same block time ? In this case, we cannot paginate and the gui will ask for a larger batch of transactions.

no, thats my point, they are all in a different block

**Comment by pythcoiner** [comment]
i close this as pagination have been refactored in #1359
