### ISSUE TITLE
Hot/Laptop signer (signing without a hardware signing device)

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#49]
For the first release of Liana, we plan to support the only two hardware signing devices supporting Miniscript: the Ledger and the Specter hardware wallets.

Some people using hot keys on their laptop at the moment might be willing to switch to Liana for, say, the inheritance planning but not be willing to start using a hardware signing device. For this usecase we could implement private key storage in the data directory and signing on the GUI directly without having to connect a signing device.
First, is there such an interest?

Second, if we decide to do it we need to discuss how to approach it. Do we want to encrypt it? Probably? How long do we keep it in memory? How do we mlock the secrets in a portable manner? Is [Rust going to be a footgun](https://benma.github.io/2020/10/16/rust-zeroize-move.html) when managing secrets?

Thoughs?

**Comment by darosior** [comment]
I don't think there is any reason for preventing user that are not using a (supported) hardware signing device today from using Liana (Minisafe). I actually think it should be a priority. I'm adding this to the v1 project.

Now the question is how to approach this. I'd rather not have the GUI handle private key material. And doing that in the daemon is really contrary to the design of the software. Maybe an additional process? That'd be a pain to make portable..

**Comment by darosior** [comment]
I've been thinking about this and i'm still on the fence about:
1. The approach
2. Whether we should prioritize this

Regarding the approach i was considering having a process. Say, `signerd` (or not `d` since it would not be a daemon) that you could invoke by giving it a configuration path and a command. You'd have for instance as commands `create`, `getxpub`, `sign` commands. The GUI could talk to it like it does with signing devices, but by spawning the process with some arguments. And then say read its stdout. Pretty much like Revault-GUI's dummy-signer but in a more reasonable fashion. But that seems hacky and brittle..
Another approach is burning down the watchonly approach and add commands to `lianad` that do exactly the above. But then it means communicating the mnemonics through the RPC socket.. I don't know.

Regarding the prioritization. Are we doing that for actual non-users of signing devices? Or is it for a simpler way to quickly try out Liana? Because if it's the latter we can just make a simple dummy signer that only supports test networks. If the former, is there actually a lot of "addressable market" there? Are we biased at thinking people actually use hardware signing devices (let alone multiple of them)?

Lots of questions, and food for thoughts. cc @edouardparis @kloaec

**Comment by kloaec** [comment]
Quick thoughts here, without considering much:
- hot key can be considered reasonably secure in a multisig situation i guess
- hot key will be useful when Liana has multi-wallet support, you can have a very low amount wallet "hot" if you want (same as a phone basically)
- hot key can be considered pretty secure in a offline / air-gapped set up. If Liana can sign offline, then we have a use for it.

Then obviously all the test examples.

How to implement isn't my expertise.

**Comment by darosior** [comment]
Process separation makes sense if the main process is doing something "dangerous" like being exposed to the internet. It's not the case of Liana. There could be an argument for planning ahead: if we ever add a way for Liana to make/receive connection through the internet (or doing anything else that could be considered "dangerous") in the future it would be better to have the secret-management in another process. But let's avoid early optimization.

So i'd say let's add a seed management capability to the daemon. Let's keep the responsibilities of commands separated:
- `generateseed` which takes a single `password` parameter. It generates a new seed, stores it encrypted in its datadir with the given password, and returns it as a mnemonic.
- `signpsbt` which takes a PSBT and appends a signature for all inputs it can sign.

If it's ever needed deleting the seed should be done manually, we shouldn't expose a footguny command.

@edouardparis what do you think about this plan? Could you lay-out something for the GUI?

**Comment by edouardparis** [comment]
I think using rpc commands to create a seed means that the daemon should be able to start without a wallet created yet, no ?

**Comment by darosior** [comment]
Yes? At least if i understand correctly your question.

The daemon can still be used only for the "wallet" (as in watching coins / creating transactions) responsibility. But in addition it would now be possible for it to assume the "signer" responsibility.

I don't think we should ever force people to use the signer functionalities?

-------- Original Message --------

**Comment by darosior** [comment]
I think there was a misunderstanding here. I've never suggested we make the descriptor-watching support of the daemon optional. I have suggested we add an opt-in support for signing transactions.

That is the daemon continues operating as usual, but it may now also create a seed and sign transactions using the proposed new RPCs.

And my question was about how you would integrate those new optional functionalities in the GUI. Because i reckon there would be an inter-dependency between the daemon and the installer here.

**Comment by darosior** [comment]
Had a call with Edouard to clear up misunderstandings on both sides and discuss the best way forward. We think it's best to keep the signer responsibility on the side of the client (whether it is the GUI, the CLI, or any other client of the JSONRPC interface).

We intend to implement the seed generation and transaction signing logic as part of the `lianad` codebase (using it as a SDK) and integrating it in the GUI. It can always be exposed as RPC commands if needed later on.

The BIP39 mnemonics would be stored as text in the corresponding network data directory. Compared to storing the seed as raw bytes this approach has the advantage of keeping the BIP39 checksum and being user-readable, at the cost of some more bytes.

Since for now this is mainly intended to make it easier to try out Liana, encryption wouldn't be supported in this first iteration. It can be added relatively easily later on.

**Comment by darosior** [comment]
We could actually derive multiple keys from the one seed stored in the data directory.

**Comment by mateusdeap** [comment]
Might not be a useful comment, but just to express my support for this. I was trying to do a quick setup of liana in order to contribute and got blocked on the specter simulator, which seems to be having issues compiling on M1 chips.

So, IMO, I think it's great to add this, at the very least to make setup and testing easier.

**Comment by mateusdeap** [comment]
Awesome. I'll try to take a look at the PR then and try out speculos for the setup

**Comment by darosior** [comment]
This was just released in 0.3: https://github.com/wizardsardine/liana/releases. The quick-try guide was also updated to not have to use a signing device simulator at all anymore.
