### ISSUE TITLE
Add minimum resize limit.

### ISSUE THREAD

**Issue by alexwaltz** [wizardsardine/liana#506]
When I drag the corner of that window to make it smaller, it has no limit so I can make it so small that you don't even see text at all.

Not sure if screenshot makes sense :)

<img width="167" alt="Screenshot 2023-05-12 at 20 32 01" src="https://github.com/wizardsardine/liana/assets/92048497/f5c9129a-e7ac-4bed-84ec-662eef0d230a">

**Comment by pythcoiner** [comment]
- i plan to do the same remark

**Comment by pythcoiner** [comment]
which minimum size should we adopt?
