### ISSUE TITLE
Replace "send-to-self" with "Self-transfer"

### ISSUE THREAD

**Issue by alexwaltz** [wizardsardine/liana#508]
I am not a native English speaker, so I am not 100% sure about this but I think the "proper" way to say this is self-transfer.

<img width="671" alt="Screenshot 2023-05-13 at 04 22 32" src="https://github.com/wizardsardine/liana/assets/92048497/2b689f3d-36e5-47fc-ab70-66f77d49566d">

**Comment by darosior** [comment]
Bingo! Thanks for the suggestion. Much better than "send-to-self" in any case.

**Comment by pythcoiner** [comment]
I think this issue can be close, right?
