### ISSUE TITLE
Spent label missaligned in PSBTs

### ISSUE THREAD

**Issue by alexwaltz** [wizardsardine/liana#509]
While in the PSBTs section, the Spent label does not alight at the same point for "send-to-selfs" as it does to "normal" spends.

Seems the reason is because the reference point is the text shown on top of the miner fee.

<img width="829" alt="Screenshot 2023-05-13 at 04 27 21" src="https://github.com/wizardsardine/liana/assets/92048497/4593203e-bdd4-40c3-b210-07d023483e40">

**Comment by pythcoiner** [comment]
maybe align to the left (at some distance of 'key' logo) or center in the block?

**Comment by alexwaltz** [comment]
> maybe align to the left (at some distance of 'key' logo) or center in the block?

Hmm, I think it would feel like the left side is too "heavy"?

**Comment by pythcoiner** [comment]
yeah maybe, so center or fixed position on the right might be better
