### ISSUE TITLE
Add options to add several hot keys when creating a wallet

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#512]
In the process of creating a wallet, it can be usefull to generate several hot keys (each one protect by a different passphrase)

**Comment by darosior** [comment]
What would be the usecase?

**Comment by pythcoiner** [comment]
first i had in mind is testing and learning purpose, but can be used for fun familly features: your 2 kids have a 2/2 wallet for spend their pocket money, they might to agree to spend it......
look like a fun feature instead a must feature

**Comment by darosior** [comment]
If there is a key per person, they need be generated separately. Otherwise there may as well be a single key.

I agree it'd be useful for testing purpose but we should optimize for real usage, not testing (unfortunately for us :p). A simple way to emulate this is to spawn multiple Lianas on different datadirs to generate multiple keys:
```
./liana-gui --datadir test_alice
./liana-gui --datadir test_bob
./liana-gui --datadir test_charlie
```

**Comment by pythcoiner** [comment]
> ```
> ./liana-gui --datadir test_alice
> ./liana-gui --datadir test_bob
> ./liana-gui --datadir test_charlie
> ```

maybe it can be useful to specify it in the doc?

**Comment by pythcoiner** [comment]
i noticed something when i was using 2 different instances of liana (using .liana2 and .liana3 as datadir) for build a test wallet (.liana2 used for the coordinator, .liana3 for make a second 'hot' key):
on the last step of registering the wallet, Liana crashed, i guess when loading twice the descriptor in bitcoins (i don't launch liana-gui in the terminal, so i don't have a traceback on the crash, and not yet take time to reproduce it).
Btw, this behavior might not happen on normal user use, so maybe it's not so important to care about.

**Comment by pythcoiner** [comment]
> Yeah, we could have a "tips and tricks" section in `TRY.md`.

assigned me if you want i handle that.

**Comment by darosior** [comment]
A crash is always important to care about. I'll open an issue about this. Reproduction instructions would be most welcome.

**Comment by edouardparis** [comment]
In case of crash you can find the logs in a file in `./liana2/installer.log`  or `./liana3/installer.log`
