### ISSUE TITLE
Wording in Hint Invalid amount (Send page)

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#515]
![image](https://github.com/wizardsardine/liana/assets/124568858/4397bb48-a846-4697-9b7f-a18cc4c184e4)
![image](https://github.com/wizardsardine/liana/assets/124568858/f4e38842-bc38-4f6a-b840-f3b89fd1c42f)

In the send page if user input too many decimals we get the Hint label for minimum amount instead of something like:
"Invalid amount. Too many decimals"

**Comment by darosior** [comment]
Yeah it should be changed for something like:
> Invalid amount. (Note amounts lower than 0.00005 BTC are invalid.)

**Comment by pythcoiner** [comment]
no, i think the hint is triggered because too many decimals (154863,2 sats) 
(on the second screenshot i delete one decimal and no hint (154863 sats)
so its not look as a wording issue, but need handle 2 different cases:
- amount < minimum amount
- precision < 1 sat

**Comment by darosior** [comment]
I understand that. But the rewording makes it so it doesn't imply that setting it too low would be the only way to make an amount invalid.
------- Original Message -------

**Comment by pythcoiner** [comment]
ok let me try handle that
