### ISSUE TITLE
Add feature for easily renew coins without consolidate

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#518]
if we want renew several coins in the same tx (with several outputs ), i think we actually have only 1 way => go pickup an adresses by hand into receive page then paste somewhere before go to the send page and craft our multi coins tx by hand.
Can we imagine some features:

-Simply add a "self" button ( or maybe "self" and "change"?) for automaticaly generate a new adress, that allow us to craft outputs one by one

-More advanced feature that build a 'renew'  tx with as many output as input (or as many as user choice?) in that case how to auto generate output amount? each output might to pay fees for 'hide' the consolidation? how to handle if input count != output count?

what you think about that guys?

**Comment by darosior** [comment]
It is already possible from the coins list. Click on a coin to see the details. There you've got a "refresh coin" button. This will create a self-transfer spending only this coin. See #371.

Happy to get any suggestion about how to make this clearer if it isn't.

**Comment by pythcoiner** [comment]
in my thought it was more about making a payjoin like tx

**Comment by darosior** [comment]
Happy to reopen if you feel like this was not addressed. Could you explain what you are thinking about? A payjoin involves multiple parties (the payer and the payee).

**Comment by pythcoiner** [comment]
my mean is act **like** a payjoin : several input => several output instead several tx, does it make sense (about privacy or at least fees?)
