### ISSUE TITLE
Installer packages for linux

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#519]
Should we build install packages for linux, for user can easily install liana (apt, dnf, yum, etc.... maybe snap?)
which one do you think is needed?

**Comment by darosior** [comment]
I think we could at least do a `.deb` and an arch package. Maybe an RPM as well?

**Comment by pythcoiner** [comment]
i made a try with .deb, i got something not bad...

 which task do we need to execute prior to install the package? (only remove old versions liana binaries if present? have a check if bitcoind installed on some standard location? check if bitcoind running for some kind autosettings about the node?)

during install of package i do this:
- copy binaries in /usr/bin/
- copy liana logo in opt/liana/
- build liana.desktop in /usr/share/applications/
- anything else to do?

do we need to do some cleanup when removing liana?

**Comment by darosior** [comment]
I've never created a `.deb` but that looks correct. I think you need to make sure the system's got the necessary dependencies (list [here](https://github.com/wizardsardine/liana/tree/master/gui)) installed. Another thing is maybe installing it for the user instead of system-wide? Like in `~/.local/bin` instead of `/usr/local/bin` and so on? Not sure. Is there any recommendation from the Debian doc?

**Comment by pythcoiner** [comment]
about the dependencies my though was they are needs at compile time, will check that.
about install the binaries into user's home folder i'll have a look on debian doc, but if i don't misunderstand, i read something that .deb installer cannot acces home folder (at least on uninstall process).

**Comment by pythcoiner** [comment]
> Another thing is maybe installing it for the user instead of system-wide? Like in `~/.local/bin` instead of `/usr/local/bin` and so on? Not sure. Is there any recommendation from the Debian doc?

I take little time looking at the debian doc about .deb packages, they don't mention locations, i think it's more about linux standards, i got a check about the app installed with apt on my ubuntu, they almost have the binaries (or symlink to the binaries) in /usr/bin.

In my mind, the home folder (~/) is reserved for user storage, i dont know if its the same thought for almost linux users?

**Comment by pythcoiner** [comment]
i'm thinking about to add a glibc version check prior to install package, i think it's a must?

**Comment by darosior** [comment]
You should be able to specify dependencies and their versions in the `.deb`, GLIBC is just one of them.
------- Original Message -------

**Comment by pythcoiner** [comment]
> You should be able to specify dependencies and their versions in the `.deb`, GLIBC is just one of them.

yes, found out that libc6 (>= 2.34) is the dependency we need

**Comment by pythcoiner** [comment]
the script i made for build .deb package is quite finnish, still some polishing to do;
what the script do:

- check the `release` binaries are presents
- ask for version trought stdin
- fetch local architecture with `dpkg-architecture `
- remove temporary folder and .deb if already present for the current arch/version
- build a new folder tree
- copy the binaries into the temp folder
- copy Liana logo (used for launcher icon)
- build the launcher file (`.desktop`)
- get the size of the folder tree
- build control file (using current `version`/`arch`/`size` data)
- build the `.deb` file
- cleanup

i ran (sucessfull) tests for this distros:
- `Ubuntu 22.04` ( udev might be manually installed prior .deb package)
- `Ubuntu 22.10`
- `Ubuntu 23.04`

i ran test on `Debian 11.7` but failed because of `GLIBC = 2.31`, `Debian 12` coming soon with upgraded `GLIBC`
should we find a solution for Debian < 12? 

you can check the script [there](https://github.com/pythcoiner/liana/blob/deb_package/build_package.py)

**Comment by darosior** [comment]
> you can check the script [here](https://github.com/pythcoiner/liana/blob/deb_package/build_package.py)

Cool, i think it's a good time to open a PR. :) You can opt for a draft if it still needs some cleanups.

**Comment by pythcoiner** [comment]
I got an idea for Debian < 11.7:
- craft a .deb that contains also the sources
- require `build` dependencies and install the last rustup version with rustup script (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh)
- build on the user system
- cleanup

can have one friction point: if the user already had cargo installed on his machine, the rustup install will fail
does it worth spend time on that?

**Comment by darosior** [comment]
No i dont think the install script should be compiling, nor do a `curl | sh` :)

-------- Original Message --------

**Comment by a7med12h** [comment]
How did you install yum package. When ever I tried to install it it gave me unable to locate . It is mean yum not there . When type yum ... etc . It gave error which is mran yum packege not installed yet . Please help to install right if u know

**Comment by pythcoiner** [comment]
yum has not yet been implemented, only the .deb is under PR
