### ISSUE TITLE
GLIBC issue on ubuntu 20.04.6

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#523]
Some user reporting on the telegram channel having issue for running liana on ubuntu 20.04.6, so i get a try on a fresh install VM:
the official build return this glibc error
```
./liana-gui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./liana-gui)
./liana-gui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./liana-gui)
```

then i compile from source, everything goes well until i quit liana-gui and try to restart it, liana crash with this output:
```
pythcoiner@pythcoiner:~/.liana$ cat crash.log 
pythcoiner@pythcoiner:~/liana/gui/target/release$ ./liana-gui 
  2023-05-14T03:42:29.156239Z  INFO winit::platform_impl::platform::x11::window:147: Guessed window scale factor: 1

2023-05-14T03:42:29.156275Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
liana-gui: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

the only way i find to make liana run next to that was reboot + recompile then liana can start only once then crash

**Comment by pythcoiner** [comment]
should we specify in TRY.md that official binary are likely to not  run with ubuntu < 22.04 or glibc < 2.34?

**Comment by pythcoiner** [comment]
seems that this issue can be linked with #414

**Comment by darosior** [comment]
Added more details to #414. 

> should we specify in TRY.md

Hmm we could have a note that binaries requires GLIBC >= 2.33 and that it rules out Ubuntu 20.04 (and lower) and Debian 10 (and lower). Although i wonder if you could install a more recent GLIBC on Ubuntu 20.

**Comment by pythcoiner** [comment]
Added more details to #414.

just had a try on debian 11.7 still GLIBC2.31 so debian might to be at least DEBIAN 12

**Comment by pythcoiner** [comment]
note: i just try to test pr630  on a Debian12 fresh install VM and it seems now liana-gui needs GLIBC2.38 (Debian12 is under 2.36)

**Comment by darosior** [comment]
I'm not sure what you are saying? Are you not able to compile and run #430?

`liana-gui` does not require a specific version of GLIBC per se. It's the version it's linked against in the release build environment that matters.
------- Original Message -------

**Comment by pythcoiner** [comment]
no, i had compile #630 from my laptop w/o issue, but when i send it to my resh install VM (Debian 12), cannot run because it seems now GLIBC3.8 is required but Debian12 is under 3.6, so i guess the same issue will happend with the .deb package on Debian12

**Comment by darosior** [comment]
Let's centralize glibc compatibility issues in #414.
