### ISSUE TITLE
GUI: Clear fingerprint value when changing device type on installer

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#531]
I noticed the following inconsistent fingerprint behaviour when setting the primary path on the installer:

Case 1: Change Specter to hot signer
- Set primary path -> choose Specter -> enter alias "spec" -> Apply
- Edit primary path -> Choose hot signer -> fingerprint value is cleared and placeholder shown:
![image](https://github.com/wizardsardine/liana/assets/121959000/81ce5b70-43d2-42a1-8973-ee29adb67803)

Case 2: Change hot signer to Specter
- Set primary path -> choose hot signer -> enter alias "hot_signer" -> Apply
- Edit primary path -> choose Specter -> "hot_signer" is still shown as value for fingerprint:
![image](https://github.com/wizardsardine/liana/assets/121959000/46b932c7-7b70-44b8-a387-b39270fbf559)

I was expecting Case 1 behaviour to apply also in Case 2 so that the fingerprint value would be cleared and the placeholder shown.

Possibly this can be made consistent with the following change:
```diff
diff --git a/gui/src/installer/step/descriptor.rs b/gui/src/installer/step/descriptor.rs
index 88ca8cf..58172f8 100644
--- a/gui/src/installer/step/descriptor.rs
+++ b/gui/src/installer/step/descriptor.rs
@@ -862,6 +862,7 @@ impl DescriptorEditModal for EditXpubModal {
                                 self.edit_name = false;
                             } else {
                                 self.edit_name = true;
+                                self.form_name.value = String::new();
                             }
                             self.form_xpub.valid = true;
                             self.form_xpub.value = key.to_string();
```

**Comment by pythcoiner** [comment]
instead of empty string, maybe it can be nice to include an `xpub template` as mentionned in #451? what do you think about?

**Comment by jp1ac4** [comment]
Hi @pythcoiner, I think that issue is about a different field. Here I'm referring to the fingerprint alias text box, which shows a placeholder "Alias" if no value has been set and otherwise shows its existing value. In Case 2 above, the value was still showing as "hot_signer" after switching to the Specter device. By setting its value to an empty string, the "Alias" placeholder should be shown again. The same thing is also being done in https://github.com/wizardsardine/liana/blob/master/gui/src/installer/step/descriptor.rs#L836, which I think is why Case 1 behaves differently (although I might be mistaken :) ).

**Comment by pythcoiner** [comment]
oh! you right i read too quickly!

**Comment by darosior** [comment]
Good spot, thanks. @edouardparis can you comment on this?

**Comment by jp1ac4** [comment]
Great thanks, I'll create a PR for that :)
