### ISSUE TITLE
GUI: Invalid response from descriptor registration on Specter device

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#532]
This issue might be more relevant to https://github.com/wizardsardine/async-hwi or https://github.com/cryptoadvance/specter-diy:

When registering the descriptor on Specter during installation, there's a prompt on the Specter device to Confirm or Cancel. If choosing Cancel, a green tick appears in Liana as if the registration has completed successfully, which is misleading.

From some initial debugging, I think that regardless of whether Confirm or Cancel is selected on the Specter device, the response from the device is the string `"error: User cancelled"`, although in the Confirm case the descriptor is indeed registered on the device.

**Comment by darosior** [comment]
I had noticed that at the time too. Thanks for opening the issue.

cc @edouardparis where should efforts be directed to fix this issue?

**Comment by edouardparis** [comment]
Thank you very much for opening the issue, it is a bug of on the https://github.com/wizardsardine/async-hwi side
I opened the issue here: https://github.com/wizardsardine/async-hwi/issues/34

**Comment by jp1ac4** [comment]
Thanks, @edouardparis. I'd be happy to work on that issue if you think it's not too complex to resolve, and I could also work on any changes that might be required in the Liana GUI to handle such cancellations.

**Comment by jp1ac4** [comment]
OK thanks, I'll add a comment in that issue.

**Comment by darosior** [comment]
https://github.com/cryptoadvance/specter-diy/issues/254 was fixed a couple days ago.

**Comment by jp1ac4** [comment]
This issue has now been resolved. See https://github.com/wizardsardine/async-hwi/issues/34#issuecomment-2152785197 for further details.
