### ISSUE TITLE
Improve UX for creating a new wallet with remote participants

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#542]
When you create a wallet importing Xpub from other remotes participants, it would be nice that after we already register one xpub (by example in the primary path) we can just have to 'select' the key in the signing devices list instead of paste its Xpub (maybe need to have a color scheme for differentiate hot/hardware/remote wallets?) .

here a quick example:
![image](https://github.com/wizardsardine/liana/assets/124568858/4b3bb3d8-f5e7-46dd-8b4e-498bff14eac4)
 `liana2` is my 'local' Liana hot key
`liana3` is a remote (hot) key (i already import xpub in primary path)
`liana4` is another remote (hot) key (i already import xpub in primary path)

when i add a key to the recovery path:
![image](https://github.com/wizardsardine/liana/assets/124568858/0f4f7cf4-d3b1-44a9-93f4-567c4dbc068d)
only liana2 is present in the signing device list (i think we need to display all the already imported key here)

**Comment by pythcoiner** [comment]
ok i think i got the point, because we cannot reuse the same derivation path (we cannot use twice the same xpub in the descriptor), but is it any way to derive only from a known Xpub (so that derivation can be done on the 'coordinator' side instead the remote guys need so send a batch of keys)?

**Comment by kloaec** [comment]
Great point. I just want to make sure we don't do anything stupid, but it seems perfectly doable, and a big improvement on the current UX for participants, and creator.

We would need to either to derive one more depth to have the different xpubs, or to have a way to "go back up" one step in the tree, to derive siblings to the first one.

We may want to get a (new) specific path for the xpub to be extracted/shared, to make sure one step higher isn't hardened if we go the siblings route.

Let's discuss this more, I think it's a very good ux improvement and should be implemented as soon as possible.

**Comment by darosior** [comment]
Yes indeed! Next time you should link it with using "Fixes #XXX" in the PR OP.
