### ISSUE TITLE
Add a remove wallet feature

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#543]
In case someone want to remove his wallet for create a new one, or just before uninstall.

**Comment by darosior** [comment]
The way to achieve this is to delete the data directory for this network. I agree having the possibility to do it directly from the GUI would be nice.

**Comment by darosior** [comment]
We could have a "cross" button next to the network name. This would open a scary confirmation modal and delete the datadir for this network if they proceed.

**Comment by edouardparis** [comment]
Maybe add the cross only for testnet, signet, regtest network setup and no cross for mainnet

**Comment by darosior** [comment]
I think that's useful for mainnet too. As long as we have a scary warning it should be fine. If you'd like we can make it scarier on mainnet?
