### ISSUE TITLE
Installer: convey in "Register descriptor" step that registration is not necessary if they are not using a signing device

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#545]
When you create a new wallet with only 'hot' keys  (local and remote), liana might NOT ask user to register descriptor on HW signing device, because customer don't have one...
![image](https://github.com/wizardsardine/liana/assets/124568858/31c224eb-ea7e-4a5f-b3c5-0f89f1219d59)

**Comment by darosior** [comment]
Hmm it should have been fixed in #470 already.

@jp1ac4 is there cases where we simply cannot detect they aren't using a signing device?

**Comment by jp1ac4** [comment]
Hi @darosior, I think this relates to participating in a shared setup and importing the descriptor. For now this has been set to always show the registration step, as per this comment: https://github.com/wizardsardine/liana/pull/470#issuecomment-1537444261. It might be tricky to work out if registration is required in this case, but I'm not sure.

**Comment by jp1ac4** [comment]
Would this wording change apply only in the case of importing a descriptor? When the page is shown in the installer case, we already know they need to register it, although it might be tricky having different wording in each case.

I think the main text `"To be used with the wallet, a device needs the descriptor. ..."` can remain unchanged as it already describes when a signing device is needed.

So we could change `"Select hardware wallet to register descriptor on"` and/or `"I have registered the descriptor on my device(s)"`. Perhaps something like https://github.com/wizardsardine/liana/issues/400#issuecomment-1517687171 can be applied here?

**Comment by pythcoiner** [comment]
> I think this relates to participating in a shared setup and importing the descriptor.

You're right

**Comment by kloaec** [comment]
Technically, a laptop is a device. If you have a multi-hot-key set up, you still need to "register" or import the descriptor to the participant devices too.
IMHO the wording is OK, but it might be confusing yes.
