### ISSUE TITLE
Have a CI job against the minimum supported Bitcoin Core version

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#548]
Since #541 we test againt Bitcoin Core 25.0. We could add a Cirrus job that for instance only runs `test_misc.py` to make (almost) sure we don't break backward compatibility.

**Comment by graychanee412** [comment]
It seems like you're discussing testing procedures related to Bitcoin Core 25.0. Testing against different versions of [Bitcoin](https://schoolofbitcoin.com/
) Core is crucial to ensure compatibility and avoid any potential backward compatibility issues. Adding a Cirrus job specifically for running the "test_misc.py" file is a great approach to further enhance testing coverage. By doing so, you can minimize the risk of breaking backward compatibility while ensuring the stability and reliability of the software. Testing is an integral part of software development, and incorporating comprehensive testing strategies helps maintain the integrity of the codebase.
