### ISSUE TITLE
Taproot support

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#55]
As Miniscript for Tapscript isn't formally specified yet, we are going to start without Taproot support. We need to have Taproot support as soon as possible, and for this i need to make progress on the C++ implementation of Tap-Miniscript.

Hopefully we'll have it in Bitcoin Core 25.0, in approximately 6 months from now. Alternately, maybe we can carve out something similar to what we used to do in revaultd before we had Miniscript support in bitcoind (watch by address)... But that's ugly :sob:

**Comment by darosior** [comment]
MiniTapscript is now specified https://github.com/sipa/miniscript/pull/134 and there is a PR implementing it into Bitcoin Core https://github.com/bitcoin/bitcoin/pull/27255.

**Comment by darosior** [comment]
Tapscript support for Miniscript got merged in Bitcoin Core and will be available from 26.

**Comment by darosior** [comment]
I think it would be good to implement it for the daemon first (let's say in v4?) before enabling it on the GUI once (some) signers support it.

**Comment by bigspider** [comment]
:)

**Comment by darosior** [comment]
Bitcoin Core 26.0 was now released, this should become a priority.

**Comment by darosior** [comment]
This was implemented in #985 and #986.
