### ISSUE TITLE
GUI: crash when importing a specific descriptor?

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#552]
Reported in https://github.com/wizardsardine/liana/issues/512#issuecomment-1568787779. Let's see if we can have some logs or more details about the config.

**Comment by pythcoiner** [comment]
just tried to reproduce it, i cannot (but happened 2 times during my testing on Monday) and unfortunately, already remove the .liana folder used for the test, so cannot get the log.

What I remember:
I was using 2 liana instances(.liana2 used for the coordinator, .liana3 for making a second 'hot' key), I finalize wallet on .liana2 by pressing the `start` button => everything OK.
When I finalize .liana3 by pressing `start` button => crash

Then I restart .liana3 instance, and get an error about cannot fetch the wallet data, so i went to check into .liana3/signet => only lianad.sqlite3 present there.

**Comment by darosior** [comment]
Thanks for the details

**Comment by darosior** [comment]
We haven't experienced this since, and there was a lot of churn in the descriptors logic. I think this can be closed. Feel free to reopen with more details if it re-appears.
