### ISSUE TITLE
GUI: display fee-rate in Transactions and PSBTs screens

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#558]
Currently only the absolute fee is shown, also displaying (while hovering or next to the fee) the fee-rate in sats/vbytes would be useful.

I got annoyed by a tx that wasn't getting mined, and I would like to know how far off i'm in terms of fee-rate.

![screenshot](https://github.com/wizardsardine/liana/assets/15522963/8c977aa3-c805-4d29-bc89-6a20d8c2d71d)

**Comment by jp1ac4** [comment]
In order to determine the fee rate for PSBTs, would the idea be to estimate the total transaction size once all inputs have been signed, e.g. using the descriptor's max satisfaction size? A similar thing is done when creating a new spend and estimating the amount left to be selected.

**Comment by darosior** [comment]
Good question. Yes the feerate should use the max satisfaction size. I think the simplest sufficient approach for now is to use it in all cases. (Eventually we could use the actual witness size for inputs that are already signed.) However i think we should convey to the user it's an estimate. Maybe with a `~`, or "estimated feerate: ".
