### ISSUE TITLE
Upload binaries to our website and make them accessible from wizardsardine.com/liana

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#571]
It's more user friendly than having to go in the Github releases and select the right platform.

**Comment by pythcoiner** [comment]
what about hosting `.deb` package on an APT repo?

**Comment by kloaec** [comment]
I think there is another issue for the linux distros, not sure. But i remember we talked about a pkgbuild for Arch too.

One reason why we want it on the website is to be able to have a clue about the number of downloads, as we don't track users and we don't know how many people have Liana currently.

**Comment by pythcoiner** [comment]
> I think there is another issue for the linux distros, not sure. But i remember we talked about a pkgbuild for Arch too.

[here](https://github.com/wizardsardine/liana/issues/519#issuecomment-1546660664) have been talked about `deb` / `arch` / `rpm`

I can try to take some time to dig into that, what is the deadline?

**Comment by pythcoiner** [comment]
> One reason why we want it on the website is to be able to have a clue about the number of downloads, as we don't track users and we don't know how many people have Liana currently.

I got the point

**Comment by darosior** [comment]
> I can try to take some time to dig into that, what is the deadline?

@pythcoiner thanks, i think the most effective way at this point would be to have [an appimage](https://appimage.org/) that runs on any distro. So we can punt down having to distribute packages adapted to every single distro. I don't even think we'd need to bundle any dependency.

Regarding the deadline, whenever you can. I'll let you know if we want to prioritize it and one of us would be doing it instead.

**Comment by pythcoiner** [comment]
> > I can try to take some time to dig into that, what is the deadline?
> 
> @pythcoiner thanks, i think the most effective way at this point would be to have [an appimage](https://appimage.org/) that runs on any distro. So we can punt down having to distribute packages adapted to every single distro. I don't even think we'd need to bundle any dependency.
> 
> Regarding the deadline, whenever you can. I'll let you know if we want to prioritize it and one of us would be doing it instead.

I will have a look at Appimages, don't have an opinion about that, the only ones I had run seem to have been standalone apps, but I'm not sure, I just wondering if in some way, it can cancel some benefits we can have using some `systemd` features (like I mention [there](https://github.com/wizardsardine/liana/issues/570#issuecomment-1637330441))

**Comment by pythcoiner** [comment]
PR #591 handles the AppImage build, I've tested against the distros we discussed, just feel free to tell me if you want me to test against some other.
@kloaec

**Comment by darosior** [comment]
Binaries are now available from https://wizardsardine.com/liana/!
