### ISSUE TITLE
auto-detect conf file at liana-cli launch

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#582]
Instead of passing the conf file path as an argument, it would be nice if `liana-cli` can detect if there is a `daemon.toml` file in the working dir first.

**Comment by pythcoiner** [comment]
another way to avoid entering the conf path file on Linux can be to check if `lianad` is running using a `ps -aux | grep lianad` call, then get the conf file path fetch.

**Comment by darosior** [comment]
I don't think we should have platform-specific code (or restrict it to a minimum), let alone calling utility programs.

**Comment by darosior** [comment]
I'm not a fan of scanning the current directory for a file with a given filename. There may be an argument to look into the default data directory for a daemon config file but:
1. That requires knowing the network
2. Requires a way of recognizing the daemon config file

I'm not sure that's worth it.
