### ISSUE TITLE
Installer: Updating xpub to tpub is not recorded

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#583]
Go to descriptor creation. Import an xpub. Apply it. Change the network from mainnet to regtest. You get an error that the key isn't for the right network. Click on Edit the key to update it to a tpub. Click apply. The key was not applied.

![image](https://github.com/wizardsardine/liana/assets/22457751/53efb714-1589-4b6b-8f92-148829648a46)
![image](https://github.com/wizardsardine/liana/assets/22457751/ce236c2d-9e0e-46d0-9355-d3f849294c8b)
![image](https://github.com/wizardsardine/liana/assets/22457751/090707d0-ef19-4dad-bd0a-af8c0ca39b07)

**Comment by pythcoiner** [comment]
i tested this, looks like we now  store/reload a separate state for each network, so i close this issue. feel free to reopen it.
