### ISSUE TITLE
Adding Liana to [https://whentaproot.org/](https://whentaproot.org/) listing

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#589]
Add Liana in the [listing](https://whentaproot.org/) of wallets available to send to taproot addresses.
@kloaec ( I checked their [GitHub](https://github.com/sbddesign/bech32m-adoption), they don't specify process to apply, I think should contact them directly)

**Comment by darosior** [comment]
We are already on the wiki page, but being listed there too is fine i guess.

> ( I checked their [GitHub](https://github.com/sbddesign/bech32m-adoption), they don't specify process to apply, I think should contact them directly)

I guess you can just submit a PR updating one or both of these lists:
- https://github.com/sbddesign/bech32m-adoption/blob/main/data/formatted/software-wallets.json
- https://github.com/sbddesign/bech32m-adoption/blob/main/data/formatted/support.json

**Comment by pythcoiner** [comment]
PR submit:
[https://github.com/sbddesign/bech32m-adoption/pull/42](https://github.com/sbddesign/bech32m-adoption/pull/42)

**Comment by pythcoiner** [comment]
PR merged, this can be closed
