### ISSUE TITLE
Add filters to the `listcoins` command

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#676]
Currently the [`listcoins` command](https://github.com/wizardsardine/liana/blob/master/doc/API.md#listcoins) is bulky. It would return all coins, even historical spent ones. It would be nice to be able to filter by status.

Also, it would be nice to be able to retrieve coins by their outpoints.

Therefore we could add two optional parameters to filter the result of `listcoins`:
- A list of status (which ones? I'm thinking of `unconfirmed`, `confirmed`, `spending` and `spent`.)
- A list of outpoints

**Comment by jp1ac4** [comment]
Regarding the statuses, I assume that we would take a union over those passed in the list. Would it be useful to also allow for the intersection, e.g. with a list of tuples?

In terms of the implementation, do you think we should extend the `CoinType` enum with additional statuses or rather introduce a new enum specifically for the CLI?

**Comment by darosior** [comment]
Well not always but maybe infrequent.

> I'm probably overcomplicating things :)

![image](https://github.com/wizardsardine/liana/assets/22457751/748b1bc6-835c-4fd6-b9e1-2c1c9a7a4648)

More seriously, if

**Comment by jp1ac4** [comment]
Do you think we can remove the `CoinType::All` enum value? We can get all coins by not passing any filters to the `listcoins` command and passing `None` as filter argument to related functions.

**Comment by darosior** [comment]
Sounds good to me.
------- Original Message -------

**Comment by jp1ac4** [comment]
Shall we also rename `CoinType` to `CoinStatus`? That would perhaps better reflect how we're thinking about it.

> I'm thinking of `unconfirmed`, `confirmed`, `spending` and `spent`

I'll keep `unspent` as one of the options from the existing `CoinType` enum to mean neither `spent` nor `spending`.

**Comment by darosior** [comment]
Hmm i think we've got a different thinking about this. That explains your previous suggestion about intersections too. My suggestion was for each status to be exclusive: a coin becomes as unconfirmed, then confirmed, then spending and finally spent. In my mind querying for `confirmed` (without adding `spending` for instance) would only return unspent coins. But maybe that's not clear enough?

**Comment by jp1ac4** [comment]
Ah yes, I see. I think that's clear enough. I'll include descriptions of each status in the API docs.
