### ISSUE TITLE
Installer: get rid of the final steps

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#679]
It seems like it's superfluous to have a summary step. In addition you need to click twice to get to the wallet. We should probably get rid of it, start the wallet immediately when clicking next after the bitcoind step, and do something like #620 to be able to inspect your setup.

Thoughts?

**Comment by pythcoiner** [comment]
agree on that point, less click = better

**Comment by darosior** [comment]
Edouard says we still need a screen to display any error that may occur when starting the daemon. So our thinking would be to simply display a load spinner when clicking "Next" after the Bitcoin Core setup step. We'd display any error there and otherwise would immediately move on to start the wallet (or sync) with no further click.

**Comment by jp1ac4** [comment]
I've made a simple change in https://github.com/wizardsardine/liana/commit/55e60b00af37e1037e8ee39296bcb211d155d72e to automatically install the wallet and start Liana on the final step. The config summary has been removed from the page and it only displays `Installing ...` and then `Installed !` before moving to the wallet sync screen. Any installation error will still be displayed. I could also remove all other contents from the page (such as the Previous button).

I've found examples of load spinners in https://github.com/iced-rs/iced/tree/master/examples/loading_spinners, which we might also want to use elsewhere (e.g. when managed bitcoind is starting). On the other hand, the `Installing ...` stage typically takes only 2-3 secs so I wanted to check if the load spinner is required before proceeding.

**Comment by darosior** [comment]
Yeah no need for the load spinner if it's only a couple seconds with an "Installing" message already.

**Comment by kloaec** [comment]
looking forward to try that, thanks @jp1ac4 ! It'll make the UI/UX much less scary.

**Comment by jp1ac4** [comment]
OK thanks, I'll skip the load spinner for now.

This final step is displayed like other steps in the installer (with `Previous` button and progress, e.g. `6 | 6`, in top right-hand corner). I could remove those so that it's empty with just `Installing ...` shown in the centre, although it might be clearer to the user to display it like other steps in order to understand it's still part of the installer.

I could change the title from "Final step" to something like "Finalize installation".

**Comment by darosior** [comment]
I think it's good to keep the "previous" if there is no reason to remove it.

Regarding the title either way is fine by me.
------- Original Message -------
