### ISSUE TITLE
Installer: incorrect assumptions when going back from the bitcoind installation step

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#701]
When clicking on "previous" while downloading Bitcoin Core:
![image](https://github.com/wizardsardine/liana/assets/22457751/b1449b77-913b-42e2-8900-910e2ebfa3d1)

**Comment by darosior** [comment]
It also happens if you go back without having pressed "Next". (Failed to find cookie file.)

**Comment by pythcoiner** [comment]
Tested today:
- press `Previous` while downloading => stop downloading and go to previous step.
- cannot press `Next` while downloading.
- press `Previous` after downloading and then press `Next` => bitcoind restart well.
- `Next` is greyed out until bitcoind start

This issue looks fixed, i close it.
