### ISSUE TITLE
[lianad] wrong message if try to launch with `--daemon` but `daemon = false` in daemon.toml 

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#708]
try to run this:
``` shell
 lianad --daemon --conf ~/.liana/signet/daemon.toml
```

got this
```
A TOML configuration file is required to run lianad. By default lianad looks for a 'config.toml' file in its data directory. A different one may be provided like so: '--conf <config file path>'.
A documented sample is available at 'contrib/lianad_config_example.toml' in the source tree (https://github.com/wizardsardine/liana/blob/v1.0/contrib/lianad_config_example.toml).
The default data directory path is a 'liana/' folder in the XDG standard configuration directory for all OSes but Linux ones, where it's '~/.liana/'.
```

the message let user guess that the toml file is missing, but in fact it's just about the .toml contain this line:

```
daemon = false
```

 shouldn't we instead apply a priority on the arg pass to cli instead param in toml file?

**Comment by darosior** [comment]
Your command is invalid, `lianad` takes only one argument. The `--conf`. All configuration parameters must be part of the file.

-------- Original Message --------

**Comment by pythcoiner** [comment]
so in that case shouldn't we inform user that `--conf` is an invalid argument?

**Comment by darosior** [comment]
`--conf` is not invalid.. This is the *only valid* argument. All others must be part of the config file pointed to by `--conf`.

-------- Original Message --------

**Comment by pythcoiner** [comment]
i mispelled, i mean shouldn't we inform user that no other than `--conf` is valid argument?

**Comment by darosior** [comment]
We could be clearer that `--conf` is the only accepted command line argument, yeah.
