### ISSUE TITLE
Installer: No message shown when starting already-installed Liana-managed bitcoind

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#714]
During installation, if the user chooses a Liana-managed Bitcoin node and a Liana-managed bitcoind is already installed (e.g. from having created a wallet on a different network), no message is shown while bitcoind is starting:

![image](https://github.com/wizardsardine/liana/assets/121959000/86398b8b-b366-4428-881b-e6e6b2b58ab6)

In the case of a newly installed bitcoind, "Starting..." is shown:

![image](https://github.com/wizardsardine/liana/assets/121959000/a82599b5-5d53-43a1-aba2-27b91dd61ada)

**Comment by darosior** [comment]
Adding to v3 roadmap, should be relatively trivial to fix.
