### ISSUE TITLE
GUI: display descriptor also in its template form

### ISSUE THREAD

**Issue by edouardparis** [wizardsardine/liana#727]
`wsh(and_or(@0/<0;1>/*, ...`

**Comment by darosior** [comment]
Could you elaborate?

**Comment by pythcoiner** [comment]
i think it's a this step:
![image](https://github.com/wizardsardine/liana/assets/124568858/e3d42fac-2291-46fd-8b54-e46778e12f1d)
very bad UX => we display the descriptor and ledger nano display the wallet policy

**Comment by pythcoiner** [comment]
Note:
- Ledger nano display wallet policy
- Colcard MK4 display wallet policy
- Specter (last version) display wallet policy (note @1, @2 are replaced by A, B)
- Jade display wallet policy
- I do not have Bitbox02 in hand.... can anyone check?

**Comment by pythcoiner** [comment]
if bitbox also display wallet policy i think we should only display the wallet policy instead descriptor at this step
