### ISSUE TITLE
qa: test Spend transaction RBF handling

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#73]
https://github.com/revault/minisafe/pull/29 added support for detecting a Spend transaction confirmation. In so doing it checked if a Spend we checked had been replaced.

However, this isn't currently tested. We should have a functional test for this.

**Comment by darosior** [comment]
I'm assigning you @edouardparis to this as a lower priority thing we need to do before the first release.

I'm keeping the "good first issue" label for now: anyone who'd want to work on this before Edouard gets to it please feel free to do so. Let us know by posting a message here.

**Comment by darosior** [comment]
I'm again moving this to the next milestone... It should be trivial to write a functional test for this that is similar to mine in #308.

**Comment by TChukwuleta** [comment]
Hello @edouardparis don't know if this has been worked on. Can I try my hands on this?

**Comment by edouardparis** [comment]
Please, go ahead ! :+1:

**Comment by darosior** [comment]
I've (inadvertently) taken care of this in #604. It's been a while anyways.
