### ISSUE TITLE
When importing mnemonic, words are not centered in field.

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#789]
![image](https://github.com/wizardsardine/liana/assets/124568858/9a745132-93e7-4ed5-9719-3cf9f6b62403)

**Comment by darosior** [comment]
Do you think it'd be better to center them? I think it would be weird.

**Comment by pythcoiner** [comment]
Or maybe reduce the with of the field? 
Depends length of longest word in 2048....
But if i'm the only one to notice, maybe we shouldn't change
