### ISSUE TITLE
GUI: Installer: Drop "backup descriptor" step when recovering from descriptor

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#791]
During restore wallet flow, we ask user to backup descriptor again just after he supplied it. It's weird, should we assume that he can restore this descriptor because he previously backed up it?

**Comment by darosior** [comment]
Good point. We can drop the "backup descriptor" step during recovery.

**Comment by darosior** [comment]
@jp1ac4 while you are tackling #866 would you address this one as well? They are pretty related and seem they could be tackled in the same PR.

**Comment by jp1ac4** [comment]
Looking at this again, do we need to change anything? There's currently only a "Register descriptor" step, but I think we still need this one as the user may no longer have the descriptor registered on any devices.

**Comment by pythcoiner** [comment]
humm, i think we already fix it in a previous commit, i close.

**Comment by jp1ac4** [comment]
Reopening as per @pythcoiner's findings in https://github.com/wizardsardine/liana_manual_testing/blob/master/tests/v5/v5-pre-rc1/pyth.md.

**Comment by jp1ac4** [comment]
This affects the "Participate in new wallet" steps.
