### ISSUE TITLE
In participate mode, let user backup the seed before share xpub.

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#794]
In participate mode, we should let the user backup hot seed before sharing it => what if crash and lost mnemonic (or just the not experienced user (grandma?) stop the flow there) and don't notice he don't have backup?

**Comment by kloaec** [comment]
Please tell grandma to not use hot keys :sob:

**Comment by nondiremanuel** [comment]
If I understand correctly this should have been addressed by @edouardparis's PR #1211 

I close this issue, but if I got it wrongly we can reopen it.
