### ISSUE TITLE
Something weird with coins display

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#796]
Something weird with coins display: in the Transaction page i have the 6 inputs of my tx but in ‘Coin’ page only 5 displayed:

![image](https://github.com/wizardsardine/liana/assets/124568858/acca7d0d-4670-4bef-8bce-58b297bde2e2)
![image](https://github.com/wizardsardine/liana/assets/124568858/dbca1392-ed38-46d6-b914-a29adee46a59)

**Comment by darosior** [comment]
That's weird. What did you do? Create a transaction paying to yourself in 6 outputs?

> in the Transaction page i have the 6 inputs

You meant "outputs" right?

**Comment by pythcoiner** [comment]
No its coins send from an other wallet

**Comment by kloaec** [comment]
Very weird. How did you generate all the addresses? Could it be the address doesn't belong to you?
Could it have been spent already?

I you can check that the address really belong to you, it'd be great. Then try to check if any outgoing tx went from there on an explorer.
Can you also try to send some coins again to that address?
We need to track this.

**Comment by pythcoiner** [comment]
All the coins have been send in batch in only one tx from sparrow, i'll try to find tx id

**Comment by pythcoiner** [comment]
ok, find out it's no an issue, the 'missing' coin is the change (0.00077950) to the sending wallet, it was confusing because I can label it.
Should we let user label the coins not owned?
