### ISSUE TITLE
Don't increment  address index on `receive` menu click

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#797]
Every time the user clicks on the `receive` menu button, a new address is generated and so the receive address index is incremented, we can instead generate a new address when the user clicks on the copy button, this avoids generating unused addresses.

In the case the user generates a batch of addresses, we could also change the address display color once the copy button is clicked.

I also wondering how we handle the receive/change index when Liana is used from several machines, do we update the index if we detect receive or change addresses w/ an index over the DB index have already coins?

**Comment by darosior** [comment]
I don't think the hassle would be worth it. The derivation index is incremented before the address is even passed to the GUI. The thinking is that no address should get out without us having increased our derivation index first. Better waste a few derivation indexes than risk reusing an address.

Yeah the derivation index is also adjusted based on onchain data: https://github.com/wizardsardine/liana/blob/d5b7a3a7de8fb36b5995bc25fc5171e425a22d8b/src/bitcoin/poller/looper.rs#L58-L66

**Comment by pythcoiner** [comment]
I just wonder if this can cause some coins to be forget during rescan, does core use a gap of adresses?

**Comment by kloaec** [comment]
There is a gap, it's should be large enough (100+ if i remember).

I understand it "feels weird" because we aren't used to that, but it really helps with the address reuse problem. People should see addresses as disposable, free to generate, things.

**Comment by darosior** [comment]
Bitcoind will use a "gap limit" of `1000`. On our end we use a look-ahead in the address->deriv index mapping of 200.

https://github.com/bitcoin/bitcoin/blob/2b3f43b96ef0b674bf350f50f317477b8d3e1e56/src/wallet/scriptpubkeyman.h#L54-L55

https://github.com/wizardsardine/liana/blob/d5b7a3a7de8fb36b5995bc25fc5171e425a22d8b/src/database/sqlite/utils.rs#L7

I'm going to close this, feel free to reopen if you think there is still something to be done here.

**Comment by pythcoiner** [comment]
should we let advanced user access LOOK_AHEAD_LIMIT, in .toml file by example?
