### ISSUE TITLE
Limit the send amout value field to 8 decimals

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#798]
Can the input field format be enforced in Iced to avoid users entering precision under 1 sat??
![image](https://github.com/wizardsardine/liana/assets/124568858/a634ca52-ee76-43a2-a2ce-8713787f2e71)

**Comment by darosior** [comment]
Good call, i guess whoever is interested in picking this up could look into [Iced](https://github.com/iced-rs/iced/) to check whether it's possible.

**Comment by pythcoiner** [comment]
@edouardparis i think we already talk about this message in some issue, but cannot find a record.
