### ISSUE TITLE
Add package size in .deb metadata

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#799]
Installing with ubuntu package manager, the size of package is not displayed, i think we can specify it in the package metadata 
Can we do something for the 'Potentially unsafe' hint?
![image](https://github.com/wizardsardine/liana/assets/124568858/bbcccf92-c466-4883-b995-a8b7295ddde7)

**Comment by darosior** [comment]
I guess it could be added to the metadata in the .deb archive in this repo? Feel free to take a shot at it.

Regarding the potentially unsafe, no idea.

**Comment by pythcoiner** [comment]
I've checked about the package `downloaded size` it appear its a metadata that should be store in the APT repository index and not in the `.deb` metadata, as the deb package is directly distributed through github/website, it seems normal what we have.
Closing issue.
