### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#803]
I need to compile a list of TODOs for publishing a new release. For myself and/or someone else who would take over in the future.

**Comment by darosior** [comment]
Sketch. WIP.

- Bump the version of `lianad` / Liana SDK in master. Keep the `-dev` suffix.
- Update the CHANGELOG.md for the new release in master.
- Update the GUI to the latest Liana SDK in master.
- Bump the version of the GUI in master.
-

**Comment by pythcoiner** [comment]
do you think it can be doable to make this process more automated?

**Comment by darosior** [comment]
Many of these steps seem to need a human double-check. Most of them also need a GPG signature. What do you have in mind?

**Comment by pythcoiner** [comment]
> Many of these steps seem to need a human double-check. Most of them also need a GPG signature. What do you have in mind?

I should run a full process to get a better idea but have in mind a semi-automated cli process.
How long does it currently take you to run the whole process?
