### ISSUE TITLE
Mismatch between selected and detected feerate

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#810]
While i was testing #563, found out that the detected feerate (5405sats/vb here) mismatch w/ user feerate (5001 sats/vb here):

![image](https://github.com/wizardsardine/liana/assets/124568858/4dddc86d-e1b8-4df0-92cd-40773bb65c26)

**Comment by darosior** [comment]
That's most likely because of the not-created change output. We should warn the user in this case (see https://github.com/wizardsardine/liana/issues/811). I don't think there is anything to be done here, please let me know if you disagree.

**Comment by pythcoiner** [comment]
it's fine with me, just want to notice it in case it can let room for error w/ fee calculations
