### ISSUE TITLE
Let coin selection use (some?) unconfirmed coins

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#826]
Currently, our automated coin selection only considers confirmed coins. Considering unconfirmed coins as well introduces new challenges and was left for future work (see https://github.com/wizardsardine/liana/pull/560#issuecomment-1784834125).

It would be nice to consider them though. Should we have a bias toward spending confirmed coins first? It's maybe part of a larger bias toward preferring to spend older coins (see https://github.com/wizardsardine/liana/issues/827)? Should we only consider unconfirmed coins we created ourselves (change) and not unconfirmed payments?

**Comment by pythcoiner** [comment]
What about running 3 rounds in coin selection:
 - first round only confirmed coins, if  match break
 - second round confirmed coins + our unconfirmed coins, if  match break
 - third round confirmed coins + all unconfirmed coins, if match at least notice user we will try spend unconfirmed coins

**Comment by darosior** [comment]
We keep stumbling upon new situations where https://github.com/wizardsardine/liana/issues/811 (i mean in the general sens of being able to pass warnings from the spend creation code to the GUI) would be useful.

**Comment by darosior** [comment]
I think it's only ever reasonable to spend our own unconfirmed change by default. We could allow to spend unconfirmed external deposits but only if the user explicitly ask for it, and i think we can leave this toggle to future work (they can already set them manually).

Note that if we ever implement this toggle, a later "safe" spend could spend one of our unconfirmed change which itself was created by and "unsafe" spend which spends an unconfirmed deposit. We should either check this or be explicit about it (maybe the toggle should be a global configuration option in this case).

**Comment by jp1ac4** [comment]
With regard to RBF, we currently consider as candidates those (possibly unconfirmed) input coins from the transaction to be replaced together with confirmed coins.

Policy 2 in https://github.com/bitcoin/bitcoin/blob/master/doc/policy/mempool-replacements.md#current-replace-by-fee-policy restricts which unconfirmed coins can be used in the replacement:
- If the transaction to be replaced is in the mempool, then this should be the only directly conflicting transaction with the replacement and so we would not be able to include any other unconfirmed coins, and so no changes are needed.
- In case the transaction to be replaced is not in the mempool and there is some other directly conflicting transaction, it may be that this other transaction is spending unconfirmed change that is not an input in the transaction to be replaced. According to the policy, I think we could include this unconfirmed change as a candidate in the replacement.

For now, I'll make the change for a regular new spend and consider RBF separately.

**Comment by darosior** [comment]
This is now done.
