### ISSUE TITLE
GUI: list but grey out devices incompatible with address verification

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#830]
Some hardware signing devices do not support address verification via USB. Currently post #819 those would not be listed when a user clicks on "Verify address on hardware device". This can be quite confusing for the user. Instead we should list them but grey them out. Maybe with a tooltip telling them to derive it manually on the device themselves using the provided derivation index.

We could also grey out devices which aren't part of our descriptor, but that should be part of a wider issue to do so in all cases (signing, desc import, etc..). See https://github.com/wizardsardine/liana/issues/831 about this.

**Comment by pythcoiner** [comment]
i think we should grey out, but as specter has a manual address verification feature, we should display the derivation index of each address on the receive page

**Comment by darosior** [comment]
The derivation index is displayed on the address verification screen precisely for this purpose.

**Comment by pythcoiner** [comment]
on the UX POV, isn't it better if we avoid 2 click there?
![image](https://github.com/wizardsardine/liana/assets/124568858/c2ab3cf2-2ee1-4c20-872a-dee54ea0de0d)
maybe we can display it here?
