### ISSUE TITLE
Add index in address QR Code

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#838]
Specter support address verification via QR Code, but we currently not put the index in the QR data so we get this error scanning the qr:
![image](https://github.com/wizardsardine/liana/assets/124568858/0ee622f3-b4fb-4669-92c0-03080e1462fc)

Is there some reasons to NOT add the address id into? (some other signer/wallet compatibility?)

Here some notes about what specter expect when scanning an address:

![image](https://github.com/wizardsardine/liana/assets/124568858/0a1df3e2-9211-4cc6-84d3-d7353fb4b3a6)

https://github.com/cryptoadvance/specter-diy/blob/master/docs/communication.md

**Comment by darosior** [comment]
I'm not aware of any reason not to do this. Good suggestion!
