### ISSUE TITLE
Refresh the state of the wallet after broadcasting a transaction

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#887]
This is in view of having a nicer UX when sending a transaction in the GUI. Our [broadcast command](https://github.com/wizardsardine/liana/blob/48feee16f5180a505c21b037c0d716791c67e97b/src/commands/mod.rs#L618-L642) should trigger the poller to do a round of updates. I'm not sure how best to update [the poller](https://github.com/wizardsardine/liana/blob/48feee16f5180a505c21b037c0d716791c67e97b/src/bitcoin/poller/looper.rs#L328-L336) to be listening for such requests, or to otherwise be able to trigger a single round of updates.

**Comment by kloaec** [comment]
this is much needed, it is frustrating to click home knowing it's displaying a past state but the poller is just taking its time.

**Comment by edouardparis** [comment]
If we have the table `transactions` cache, the broadcast command could do:
- set the coins as spending (set the spend_txid) in database
- store the transaction in the table
- create change coins

Then no need to call for a poller update,

**Comment by darosior** [comment]
I'd rather not share the same responsibility over multiple pieces of code..

**Comment by darosior** [comment]
Also of course there is more to updating the database: we have some invariants which would be nice to not break just for the sake of not reusing the poller (what for?). For instance consistency with the chain tip. Trying to make these invariants hold would boil down to simply rewriting the poller's logic.
