### ISSUE TITLE
GUI: refresh homepage after broadcasting a transaction

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#888]
Currently, after broadcasting a transaction, the payment isn't shown on the wallet homepage until the daemon has polled it from bitcoind  (see https://github.com/wizardsardine/liana/issues/887) and the GUI has refreshed the homepage to be in sync with the daemon. It would be nice if a payment which was just performed was shown immediately when getting back on the homepage.

**Comment by darosior** [comment]
I'm putting this in "Nice to have"s because it's not clear to me how involved it would be. Maybe @edouardparis can shed some lights on this.

**Comment by edouardparis** [comment]
the command broadcast psbt could mark the coins as spending by setting the spend_txid of those coins and could create the change coin (currently both are done by the poller). By doing so, the list_pending_transactions command would list automatically the spend without waiting for the next poll.
But, it would still require that the transaction be returned by the bitcoind node through the bitcoind command get_transaction <txid>. If the node broadcasted it, we can expect that it is able to respond to this request.

**Comment by darosior** [comment]
What about the GUI? It's what i was asking about (the other is #887). But thinking more about it now, if we don't return from the `broadcast` command before the poller is done updating the state of the wallet i *think* the GUI would show the latest state when exiting the send screen. Am i right?

> the command broadcast psbt could mark the coins as spending by setting the spend_txid of those coins and could create the change coin (currently both are done by the poller)

Precisely. And i'd prefer to not duplicate code and share responsibilities. I think it's better to trigger the poller. Or at least to reuse one of its functions.

**Comment by edouardparis** [comment]
>  if we don't return from the broadcast command before the poller is done updating the state of the wallet i think the GUI would show the latest state when exiting the send screen. Am i right?

I believe yes.

**Comment by darosior** [comment]
#1010 was opened which makes the `broadcastspend` command update our state before returning. This should ensure the GUI shows up to date information after every transaction broadcast.

**Comment by darosior** [comment]
Fixed by #1018.
