### ISSUE TITLE
RBF: warn the user if they are about to shoot them in the foot.

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#903]
If a user spends the unconfirmed change output from their transaction A in a later transaction B we should prevent them from RBF'ing A (and thereby invalidating B).

**Comment by jp1ac4** [comment]
Should we just warn the user when creating the replacement or prevent them from doing so?

In case the transaction to be replaced is not in the mempool, I'll apply the check to any directly conflicting transactions. I could check these directly conflicting transactions for any outputs that are coins in our database that are being spent (in case this conflicting transaction is paying to one of our receive addresses or more than one change address).

**Comment by darosior** [comment]
I'm leaning toward asking confirmation. If they don't know what they are doing they wouldn't confirm. And an experienced user can still proceed.

I'm not sure i understood the latter part. How i was thinking about it was: if we get a request to replace a tx `A`, we check in database if it has a change output and if it's marked as `spending` in the DB (ie we have a tx `B` chained onto our own change). We would return an error with the txid in this case.

Thinking through it, making it a confirmation instead of an error would be more work (would probably have to include another parameter, like `force`). A warning could work but it's maybe too "soft"?

**Comment by jp1ac4** [comment]
> I'm not sure i understood the latter part. How i was thinking about it was: if we get a request to replace a tx A, we check in database if it has a change output and if it's marked as spending in the DB (ie we have a tx B chained onto our own change). We would return an error with the txid in this case.

My thinking was that this check should apply to the directly conflicting transactions of the replacement transaction, which may or may not be `A`. If `A` is in the mempool, then this will be the only directly conflicting transaction, but if not, then there may be one or more other directly conflicting transactions. Also, it's possible that one of the outputs of these directly conflicting transactions is a non-change coin in our DB, so I was thinking that we could check for any outputs that are coins marked as spending, not just for change outputs.

> I'm leaning toward asking confirmation. If they don't know what they are doing they wouldn't confirm. And an experienced user can still proceed.

I agree we should allow the user to proceed. If there's a clear warning of some kind, then we can assume they know what they're doing.

> Thinking through it, making it a confirmation instead of an error would be more work (would probably have to include another parameter, like force). A warning could work but it's maybe too "soft"?

Perhaps we can already show a warning in the modal before they click "confirm", which would have to be generated by the GUI. Even after generating the replacement PSBT, they still need to sign and broadcast it, so there would be a chance to show any warnings from `rbfpsbt` in the modal before they click on "go to replacement". I don't think a warning like this would be too soft, at least to start with. We could make it stricter later depending on user feedback.

**Comment by darosior** [comment]
I see. I think it's even more edgy a case and fine to not cover for now. Feel free to have a look and if it's a small diff do it in the same PR, otherwise you can open a separate issue to track this.

Ack for going the warning route.

**Comment by jp1ac4** [comment]
I don't think checking for directly conflicting transactions in general will add any complexity as we already have the `mempool_spenders()` method.

We can assume that if an unconfirmed output is being spent, then the corresponding coin must already be in our DB (but possibly not yet marked as spending). In that case, we can look up all DB coins created by one of these directly conflicting transactions and then use `mempool_spenders()` on the outpoints of these coins to check if any of them are being spent.

**Comment by pythcoiner** [comment]
> Thinking through it, making it a confirmation instead of an error would be more work (would probably have to include another parameter, like `force`). A warning could work but it's maybe too "soft"?

confirmation looks better to me

**Comment by jp1ac4** [comment]
It should be fairly straightforward to check in the GUI using just DB coins if there are any descendant transactions that would be dropped (assuming that all spending coins have already been marked as spending). This could be used for a preliminary warning when opening the RBF modal.

In addition, I plan to build on #905 and generate warnings in the `rbfpsbt` command for any descendant transactions that would be dropped by the replacement. These warnings would use mempool data and would catch anything missed by the preliminary warning in the modal.

Assuming `rbfpsbt` also returns any warnings from the lib `create_spend` function, there may be other warnings also returned by the command, e.g. regarding a change amount added to the fee, and so perhaps these warnings should all be shown together on the PSBT screen rather than in the RBF modal (how we will show these spend warnings in the GUI is still to be decided).

**Comment by jp1ac4** [comment]
It might make sense to run the GUI check each time the PSBT screen is opened to see the latest unconfirmed transactions that would be dropped by broadcasting it. This way, the warnings would still be there if the replacement is not signed immediately. Even though a PSBT that would cause other transactions to be dropped could only be created by the `rbfpsbt` command, we could run this check against all PSBTs using DB coin info, as it should be fairly quick and we don't currently track which PSBTs are generated as replacements.

**Comment by darosior** [comment]
This makes sense to me. We already have a confirmation dialog for broadcasting a PSBT. This could be part of it.

> we could run this check against all PSBTs using DB coin info

This would translate to use the `listcoins` command, right? Upon clicking on "broadcast" we'd:
1. Detect the change output, if any, from the PSBT
2. Call `listcoins` with parameters `outpoints=[change_outpoint]` and `status=["spending"]`
3. If it returns any transaction, warn the user in the dialog.

**Comment by jp1ac4** [comment]
> This would translate to use the `listcoins` command, right? Upon clicking on "broadcast" we'd:
>     1. Detect the change output, if any, from the PSBT
>     2. Call `listcoins` with parameters `outpoints=[change_outpoint]` and `status=["spending"]`
>     3. If it returns any transaction, warn the user in the dialog.

I think it would be slightly different if we're checking a not-yet-broadcast PSBT:

1. For all input coins of the PSBT, check if any are already spending and get their `spend_txid`. These are the directly conflicting transactions.
2. Check if there are any coins in the DB created by these directly conflicting transactions, and check if any of these coins are being spent. These coins would probably be change outputs, but any such coins would be dropped by broadcasting the PSBT, whether change or not, so I don't think we'd need to limit the check to change outputs only.

For this, it would be useful to implement https://github.com/wizardsardine/liana/issues/677 and possibly also add the ability to filter DB coins by txid.

**Comment by darosior** [comment]
Oh, right, you'd need to check the *inputs*.

You are right regarding not limiting the check to change outputs in this case. In fact we could also just stop at 1. List the `spend_txid`s, if any, as conflicting and mention "any potential child transaction would be evicted" (not sure about the formulation here.

-------- Original Message --------

**Comment by jp1ac4** [comment]
> In fact we could also just stop at 1. List the `spend_txid`s, if any, as conflicting and mention "any potential child transaction would be evicted" (not sure about the formulation here.

That's true. If this is a general check performed on the PSBT screen rather than the RBF modal, then I think it would make sense to show the directly conflicting transactions and just mention about any child transactions also being evicted.

> Even though a PSBT that would cause other transactions to be dropped could only be created by the `rbfpsbt` command

 I think I was wrong before, as the two PSBTs could be created before either is broadcast, rather than the second PSBT being created once the first has already been broadcast. This would be another reason to check on the PSBT screen rather than the RBF modal.

Perhaps for now we don't need to add any warnings to the `rbfpsbt` command and can just add a check for directly conflicting transactions in the GUI PSBT screen (and maybe also a check in the RBF modal for any conflicting descendant transactions).

**Comment by jp1ac4** [comment]
I think this issue can be closed now that warnings have been added to the GUI.

We could additionally add a warning in the `rbfpsbt` command, but I think the GUI warnings should be enough for now.
