### ISSUE TITLE
`startrescan` allows timestamps before genesis block on test networks

### ISSUE THREAD

**Issue by edouardparis** [wizardsardine/liana#904]
Entered a 2015 date as rescan date for a signet setup.
Rescan stopped at 100%, no errors handled by the GUI, only an error in logs:
`2024-01-03T15:09:04.881557Z ERROR liana::bitcoin::poller::looper:289: Could not retrieve block height for timestamp '1421020800'`

**Comment by darosior** [comment]
To fix this, i think we can simply query the time of the genesis block from bitcoind instead of using a hardcoded constant which is mainnet-specific:
https://github.com/wizardsardine/liana/blob/15b1f0c789d251dc3d420de50e859b6dd4bfda75/src/commands/mod.rs#L870-L880

**Comment by darosior** [comment]
xref #956
