### ISSUE TITLE
GUI: Show blockchain sync progress as percentage to 2 decimal places

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#907]
Currently, the percentage is shown to 2 decimal places, but the second decimal is always 0:

![image](https://github.com/wizardsardine/liana/assets/121959000/45822a5a-03e3-45e4-8b31-e0fa6bf60204)

I think this can be resolved by increasing the number of decimal places of the `"sync"` entry in Liana's `getinfo` command to 4.

**Comment by kloaec** [comment]
@darosior can you tag this one "good first issue"? It should be a super easy one :)

**Comment by AnmolSirola** [comment]
@jp1ac4 Can I take this one ?

**Comment by jp1ac4** [comment]
Sure, that would be great thanks. Please note that it might not be possible to update the GUI's `liana` dependency yet as its rust-bitcoin dependency needs to be updated to v0.31 still, but it should be enough for this issue to update the "sync" entry as mentioned above and then the GUI's `liana` dependency will be updated elsewhere.

**Comment by edouardparis** [comment]
We need to update liana-gui with liana master then

**Comment by pythcoiner** [comment]
> We need to update liana-gui with liana master then

@thomask7b can you do this?

**Comment by nondiremanuel** [comment]
> @nondiremanuel In #1386, the sync progress is shown on the home screen to 1 decimal place. Following #1457, we can now show it to 2 decimal places. Shall we use 2 decimal places on both the loading screen (for IBD) and home page (for existing wallets)?

If it's not too complicated, I agree to align the behavior. Not a major priority though.
