### ISSUE TITLE
[GUI] Always stop Liana-managed bitcoind when closing GUI?

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#915]
This applies when running the embedded Liana daemon from the GUI. For an external Liana daemon, the GUI does not attempt to start any managed bitcoind (see [gui/src/loader.rs#L122](https://github.com/wizardsardine/liana/blob/d8a5e1d78027837b561739730296db8a6928606b/gui/src/loader.rs#L122)).

It could happen that the Liana-managed bitcoind on the chosen network is already running when opening the GUI. This could be either because the user started it manually or the GUI didn't close properly before and bitcoind was left running.

In such cases, we currently assume the user has started bitcoind. We log a message ([gui/src/loader.rs#L504](https://github.com/wizardsardine/liana/blob/d8a5e1d78027837b561739730296db8a6928606b/gui/src/loader.rs#L504)) that it's already running and continue, and then leave it running when closing the GUI later on.

Should the GUI rather assume that the managed bitcoind is already running due to an error and attempt to stop it the next time the GUI closes? This seems better for those users who would not otherwise realise that their managed bitcoind was still running.

**Comment by pythcoiner** [comment]
I thinks its better to keep actual behavior, but not strong opinion.

Pros:
 - If bitcoind have been started by user, there is no reason to close it (some other software can rely on it).

Cons:
 - If liana crashed w/o closing bitcoind (this is not very likely to happen i guess) we will have a 'standalone' running bitcoind (but i don't think it's a big threat, right?)

**Comment by pythcoiner** [comment]
find #916 while thinking aroud this

**Comment by jp1ac4** [comment]
I think it would be reasonable to say that as long as bitcoind is managed by Liana, it will be stopped/started by Liana, and so if the user wants to start it manually, they should be prepared for this, and should otherwise migrate to using their own node.

If the managed bitcoind is left running when Liana is closed, there's a risk that pruning will cause the user to miss transactions without realising the next time they open Liana. So I think there's more risk leaving the managed bitcoind running than there is stopping it.

**Comment by pythcoiner** [comment]
> If the managed bitcoind is left running when Liana is closed, there's a risk that pruning will cause the user to miss transactions without realising the next time they open Liana.

Very good point

**Comment by darosior** [comment]
I don't think we'd miss transactions in this scenario. They would be recorded in the wallet, pruned from the node and we'd poll them from the wallet upon next startup.

**Comment by pythcoiner** [comment]
> I don't think we'd miss transactions in this scenario. They would be recorded in the wallet, pruned from the node and we'd poll them from the wallet upon next startup.

you mean the `bitcoind` watchonly wallet?

**Comment by darosior** [comment]
Yes.

-------- Original Message --------

**Comment by jp1ac4** [comment]
> I don't think we'd miss transactions in this scenario. They would be recorded in the wallet, pruned from the node and we'd poll them from the wallet upon next startup.

Ah I see, so leaving it running would not be so bad, although I think it would still be reasonable to stop it given that it's the managed node.

Another option if the managed bitcoind is already running would be to show a prompt when the user closes the GUI asking if they'd like bitcoind to be stopped.

**Comment by darosior** [comment]
I think it's better to just stop it (as we do now) than to ask a potentially confusing question to the user.

**Comment by pythcoiner** [comment]
I think now we don't stop it
