### ISSUE TITLE
[ Win10 VM] Crash at Liana startup

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#918]
I've try to run Liana on a fresh installed Windows 10 Virtual Machine (QEMU/KVM), i got a crash on Liana startup.
When i try to launch from cmd/powershell i have no log or error message, w/ GitBash i got this:

![image](https://github.com/wizardsardine/liana/assets/124568858/51d3026a-73de-43f6-8989-44d4a4199087)

i've try w/ all graphic drivers i can, but still got the issue:

![image](https://github.com/wizardsardine/liana/assets/124568858/68354eda-0b66-420d-8ad0-12741e50ce5b)

try to build Liana from this machine also not solve this, also had the same issue trying run V2.0 & V3.0

so expecting it's something around iced, i try to build `tour` [example](https://github.com/iced-rs/iced/tree/master/examples/tour) => tour.exe run well.....

Is there any way to get more logs? 

I already try to set LOG_LEVEL environment var introduced by #859 but have no effect:

![image](https://github.com/wizardsardine/liana/assets/124568858/17589e47-46a0-46ff-94ac-45426db4eed6)

**Comment by darosior** [comment]
If you build from source dropping this line before building might help getting more info.

https://github.com/wizardsardine/liana/blob/501dce4372b5a5164b6c69ad9bf16056418218e2/gui/src/main.rs#L1

**Comment by pythcoiner** [comment]
will try, thx for the 2 minutes response time!

**Comment by pythcoiner** [comment]
just tryed, but no more details... 

note: i got many warnings on build (have 0 while building on linux)
![image](https://github.com/wizardsardine/liana/assets/124568858/28a6b793-8ffc-42b4-b9f8-04f65bf2f1e2)

**Comment by pythcoiner** [comment]
Closed it as it fixed since we switch to Iced 12.1, tested for Windows & MacOS VMs.
