### ISSUE TITLE
spend: bump bdk_coin_select dependency to 0.3.0

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#923]
This will enable us to revert the temporary fix from https://github.com/wizardsardine/liana/pull/867.

Note that the min change value is no longer inclusive (see https://github.com/bitcoindevkit/coin-select/pull/14#discussion_r1439665103) and so the min value we set in the change policy will need to be decreased by 1.

**Comment by jp1ac4** [comment]
We can wait until the changes relating to RBF have also been released: https://github.com/bitcoindevkit/coin-select/pull/19.

**Comment by darosior** [comment]
They still haven't been released? Could you open a PR upstream which bumps the version in the Cargo.toml and kindly ask them to publish to crates.io?

**Comment by jp1ac4** [comment]
v0.3.0 has now been released :tada:
