### ISSUE TITLE
[GUI] Installer: going back to change the Network on the installer doesn't change the network connection directory.

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#946]
![image](https://github.com/wizardsardine/liana/assets/15522963/850b5a92-404b-46f8-b131-38bbcf5c9a9b)

If from this screen i go back to change the network, once i'm back here it's still "testnet3" also I selected another one.

**Comment by jp1ac4** [comment]
Did this happen following https://github.com/wizardsardine/liana/pull/932? For me, the address and cookie path are now updating when I change network.

**Comment by kloaec** [comment]
Oh, yes on V4. Great to see you guys fixed it already

**Comment by pythcoiner** [comment]
just tested, seems fixed on master, closing issue
