### ISSUE TITLE
Liana Crate not up to date on crates.io

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#948]
![image](https://github.com/wizardsardine/liana/assets/124568858/c70e2d38-7587-4c01-be4d-5cb0dce34c41)

**Comment by nondiremanuel** [comment]
I think the issue was solved, since I now see the correct version:


![Image](https://github.com/wizardsardine/liana/assets/63922722/7c687f55-6324-40a3-ad3d-13afe52f7616)


If it is not present yet, we could maybe add this check in a post-release checklist (if such list is present at all)

**Comment by pythcoiner** [comment]
right!
