### ISSUE TITLE
QRCode displayed only for last address

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#949]
lurking kevin [here](https://youtu.be/7F-ibKh7fEU?t=4911), it appear that the QRCode cannot be dispayed on oldest address if we generate several, should be good to add 'dispay qr code' button i think.

**Comment by pythcoiner** [comment]
or what about moving QRCode into the address 'card'?

**Comment by darosior** [comment]
@edouardparis states elsewhere:
> I want to remove the receive QrCode and move it into a modal that is displayed when user clicks on "Show Qr code" button next to "verify address"
Because it feels weird to not be able to show Qrcode of previously generated address, especially when generating a few in a batch
