### ISSUE TITLE
GUI: it seems the GUI is considering OP_RETURN outputs from coinbase tx as incoming payments

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#960]
To be confirmed but from what @kloaec is showing me on a call it seems the witness commitment output from the coinbase tx are listed in the home page as incoming payments.

**Comment by pythcoiner** [comment]
try to reproduce it on regtest, they first coins op_return appear in GUI in my side:

![image](https://github.com/wizardsardine/liana/assets/124568858/130f030b-2a2c-4af0-9dcb-b6f9590702d5)

![image](https://github.com/wizardsardine/liana/assets/124568858/6db6ba34-2829-409f-99f4-1212e2ced005)

![image](https://github.com/wizardsardine/liana/assets/124568858/266ff23a-c507-44ea-ae3e-6d70b8dded09)

what i hit instead, is that halvings seems coming quickly and the coinbase came to 0 sats after few thousands blocks:

![image](https://github.com/wizardsardine/liana/assets/124568858/2d9b203d-fbe4-40a5-87f0-f1a8bf42428e)

**Comment by pythcoiner** [comment]
so i guess the real issue is @kloaec is a greedy regminer :smile:

**Comment by darosior** [comment]
Ok, thanks for testing.
