### ISSUE TITLE
Display `broadcasted` status after a tx is

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#978]
![image](https://github.com/wizardsardine/liana/assets/124568858/5543c2a7-3914-43b7-940b-b631c8de78d6)

**Comment by darosior** [comment]
I don't think it's important, as soon as we exit the popup the status of the draft will be updated. I think it's overkill at this point to try and update a draft in the background of a temporary popup which is not misleading the user in any way?

**Comment by pythcoiner** [comment]
btw, `Broadcast` button is not displayed afterbroadcast, so user have a way to know it have been broadcast, so i close this issue.
