### ISSUE TITLE
[GUI] Rename recovery panel to sweep

### ISSUE THREAD

**Issue by jp1ac4** [wizardsardine/liana#994]
Recovery panel could be renamed sweep and the primary path added to the list of recovery paths.
Wording can be:

2 paths are accessible next block, please select one
- The primary path
  - Signatures from Ed and Antoine can move 11 coins totalling 1.2334 BTC 
-  Recovery path:
   - Signatures from Ed can move 4 coins totalling 0.6244 BTC

_Originally posted by @edouardparis in https://github.com/wizardsardine/liana/issues/546#issuecomment-1634184717_

**Comment by edouardparis** [comment]
Now that the max button was implemented, I am not sure it still makes sense.
User can use the max button now to do a sweep through the spend panel and the current recovery settings is still only about recovery.

**Comment by jp1ac4** [comment]
That's true. I'll close this issue for now then and we can re-open it if need be.
